Repository gocd/gocd, pull requests merged in 2018-07, with the labels that each got.

#4891 Remove templates API v4 from rails.
  server/src/main/java/com/thoughtworks/go/server/SparkOrRailsToggle.java
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/src/test-fast/java/com/thoughtworks/go/server/SparkOrRailsToggleTest.java
  server/webapp/WEB-INF/rails.new/app/controllers/api_v4/admin/templates_controller.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/admin/templates/pipeline_config_summary_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/admin/templates/template_config_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/admin/templates/template_summary_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/admin/templates/templates_config_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/environment_variable_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/approval_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/artifact_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/job_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/plugin_configuration_property_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/plugin_configuration_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/property_config_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/stage_authorization_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/stage_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/tab_config_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/tasks/ant_task_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/tasks/base_task_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/tasks/exec_task_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/tasks/fetch_task_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/tasks/nant_task_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/tasks/on_cancel_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/tasks/pluggable_task_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/tasks/rake_task_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/shared/stages/tasks/task_representer.rb
  server/webapp/WEB-INF/rails.new/config/routes.rb
  server/webapp/WEB-INF/rails.new/spec/controllers/api_v4/admin/templates_controller_spec.rb
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v4/admin/templates/pipeline_config_summary_representer_spec.rb
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v4/admin/templates/template_config_representer_spec.rb
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v4/admin/templates/template_summary_representer_spec.rb
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v4/admin/templates/templates_config_representer_spec.rb
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v4/shared/environment_variable_representer_spec.rb
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v4/shared/stages/approval_representer_spec.rb
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v4/shared/stages/artifact_representer_spec.rb
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v4/shared/stages/job_representer_spec.rb
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v4/shared/stages/property_config_representer_spec.rb
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v4/shared/stages/stage_authorization_representer_spec.rb
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v4/shared/stages/stage_representer_spec.rb
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v4/shared/stages/task_representer_spec.rb
  server/webapp/WEB-INF/urlrewrite.xml
Labels: apis

#4901 Add material name field for dependency material in pipeline creation wizard.
  server/webapp/WEB-INF/rails.new/app/views/admin/pipelines/materials/_dependency_form.html.erb
Labels: bug

#4877 Update pluggable SCM checkout status on console log.
  common/src/main/java/com/thoughtworks/go/domain/materials/MaterialAgentFactory.java
  common/src/main/java/com/thoughtworks/go/domain/materials/scm/PluggableSCMMaterialAgent.java
  common/src/test/java/com/thoughtworks/go/domain/materials/scm/PluggableSCMMaterialAgentTest.java
Labels: bug, enhancement

#4882 Handling encryption of pluggable publish/fetch artifact config proper…
  config/config-api/src/main/java/com/thoughtworks/go/config/BasicCruiseConfig.java
  config/config-api/src/main/java/com/thoughtworks/go/config/CruiseConfig.java
  config/config-api/src/test/java/com/thoughtworks/go/config/BasicCruiseConfigTest.java
  config/config-api/src/test/java/com/thoughtworks/go/security/ResetCipher.java
  config/config-server/src/main/java/com/thoughtworks/go/config/GoConfigCloner.java
  config/config-server/src/main/java/com/thoughtworks/go/config/MagicalGoConfigXmlLoader.java
  config/config-server/src/test/java/com/thoughtworks/go/config/GoConfigClonerTest.java
  config/config-server/src/test/java/com/thoughtworks/go/config/MagicalGoConfigXmlLoaderTest.java
  config/config-server/src/test/resources/data/config_with_pluggable_artifacts_store.xml
  config/config-server/src/test/resources/data/pipeline_group_snippet_with_pluggable_artifacts.xml
  config/config-server/src/test/resources/data/pluggable_artifacts_with_params.xml
  server/src/main/java/com/thoughtworks/go/config/FullConfigSaveFlow.java
  server/src/main/java/com/thoughtworks/go/config/GoConfigDao.java
  server/src/main/java/com/thoughtworks/go/config/GoFileConfigDataSource.java
  server/src/main/java/com/thoughtworks/go/server/service/GoConfigService.java
  server/src/main/java/com/thoughtworks/go/server/service/TemplateConfigService.java
  server/src/test-integration/java/com/thoughtworks/go/config/CachedGoConfigIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/config/FullConfigSaveFlowTestBase.java
  server/src/test-integration/java/com/thoughtworks/go/config/FullConfigSaveMergeFlowIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/config/FullConfigSaveNormalFlowIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/GoConfigServiceIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/PipelineConfigsServiceIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/builders/BuilderFactoryIntegrationTest.java
  server/src/test-shared/java/com/thoughtworks/go/util/GoConfigFileHelper.java
  server/webapp/WEB-INF/rails.new/app/controllers/admin/package_repositories_controller.rb
  server/webapp/WEB-INF/rails.new/app/controllers/admin/pipeline_groups_controller.rb
  server/webapp/WEB-INF/rails.new/app/controllers/admin/pipelines_controller.rb
  server/webapp/WEB-INF/rails.new/app/controllers/admin/pipelines_snippet_controller.rb
  server/webapp/WEB-INF/rails.new/app/controllers/api_v1/admin/internal/material_test_controller.rb
  server/webapp/WEB-INF/rails.new/lib/java_imports.rb
  server/webapp/WEB-INF/rails.new/spec/controllers/admin/pipelines_controller_spec.rb
  server/webapp/WEB-INF/rails.new/spec/support/util/config_save_stubbing.rb
Labels: artifacts

#4908 [CSS] Fix css for artifacts tab in job details.
  server/webapp/WEB-INF/rails.new/app/assets/stylesheets/new-theme.scss
  server/webapp/WEB-INF/rails.new/app/views/admin/jobs/_artifact_configs.html.erb
  server/webapp/WEB-INF/rails.new/app/views/admin/jobs/_external_artifact_form.html.erb
Labels: artifacts

#4919 Rename usage_data_last_reported_time to last_usage_data_reporting_check_time
  server/webapp/WEB-INF/rails.new/spec/webpack/models/shared/usage_data_reporter_spec.js
  server/webapp/WEB-INF/rails.new/webpack/models/shared/usage_data_reporter.js
Labels: metrics-collection

#4913 Remove Jobs from JobPlans If the pipeline is deleted after it is scheduled (But the jobs are still unassigned) (#3390)
  server/src/main/java/com/thoughtworks/go/server/service/BuildAssignmentService.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/BuildAssignmentServiceTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/BuildAssignmentServiceIntegrationTest.java
Labels: pipeline configuration, scheduling

#4779 Bump up version of Config Repo target_version and add migration
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/configrepo/ConfigRepoMigrator.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/configrepo/JsonMessageHandler1_0.java
  plugin-infra/go-plugin-access/src/main/resources/config-repo/contexts/3.json
  plugin-infra/go-plugin-access/src/main/resources/config-repo/migrations/3.json
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/configrepo/ConfigRepoDocumentMother.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/configrepo/ConfigRepoMigratorTest.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/configrepo/JsonMessageHandler1_0Test.java
  plugin-infra/go-plugin-access/src/test/resources/v2_with_fetch_external_artifact_task.json
  plugin-infra/go-plugin-access/src/test/resources/v2_with_fetch_tasks.json
  plugin-infra/go-plugin-access/src/test/resources/v3_comprehensive.json
  plugin-infra/go-plugin-access/src/test/resources/v3_with_fetch_external_artifact_task.json
  plugin-infra/go-plugin-access/src/test/resources/v3_with_fetch_tasks.json
Labels: artifacts

#4921 Show view from plugin by default when there's only one plugin installed.
  server/webapp/WEB-INF/rails.new/app/views/admin/jobs/_artifact_configs.html.erb
  server/webapp/WEB-INF/rails.new/app/views/admin/jobs/_external_artifact_form.html.erb
  server/webapp/WEB-INF/rails.new/spec/views/admin/jobs/artifacts_html_spec.rb
Labels: artifacts

#4893 Remove artifact extension feature toggle.
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/java/com/thoughtworks/go/server/service/tasks/TaskViewService.java
  server/src/main/java/com/thoughtworks/go/server/web/GoVelocityView.java
  server/src/main/resources/available.toggles
  server/src/test-fast/java/com/thoughtworks/go/server/service/tasks/TaskViewServiceTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/web/GoVelocityViewTest.java
  server/webapp/WEB-INF/rails.new/app/helpers/application_helper.rb
  server/webapp/WEB-INF/rails.new/app/views/new_navigation_elements/_dropdown_admin.html.erb
  server/webapp/WEB-INF/rails.new/app/views/shared/_dropdown_admin.html.erb
  server/webapp/WEB-INF/rails.new/spec/views/shared/_application_nav_html_spec.rb
  server/webapp/WEB-INF/vm/shared/_dropdown_admin.vm
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/spring/InitialContextProvider.java
  spark/spark-spa/src/main/java/velocity_implicit.vm
  spark/spark-spa/src/main/resources/velocity/new_navigation_elements/_dropdown_admin.vm
  spark/spark-spa/src/test/java/com/thoughtworks/go/spark/spa/spring/InitialContextProviderTest.java
Labels: artifacts

#4924 Use FilenameUtils.separatorsToUnix to convert all the '\\' to '/' which is a valid name seperator character in the URI (#4923)
  plugin-infra/go-plugin-domain/build.gradle
  plugin-infra/go-plugin-domain/src/main/java/com/thoughtworks/go/plugin/domain/analytics/AnalyticsData.java
  plugin-infra/go-plugin-domain/src/test/java/com/thoughtworks/go/plugin/domain/analytics/AnalyticsDataTest.java
Labels: analytics

#4911 Improve API related error messages.
  api/api-base/src/main/java/com/thoughtworks/go/api/representers/JsonReader.java
  api/api-base/src/main/java/com/thoughtworks/go/api/util/HaltApiMessages.java
  api/api-base/src/main/java/com/thoughtworks/go/api/util/HaltApiResponses.java
  api/api-encryption-v1/src/test/groovy/com/thoughtworks/go/apiv1/admin/encryption/EncryptionControllerDelegateTest.groovy
  api/api-pipeline-selection-v1/src/test/groovy/com/thoughtworks/go/apiv1/pipelineselection/representers/PipelineSelectionsRepresenterTest.groovy
Labels: apis

#4934 Fixed issue with update-check notification not showing up when user c…
  server/webapp/WEB-INF/rails.new/app/assets/javascripts/version_updater.js
  server/webapp/WEB-INF/rails.new/app/views/layouts/single_page_app.html.erb
  server/webapp/WEB-INF/rails.new/app/views/navigation_elements/_footer.html.erb
  server/webapp/WEB-INF/rails.new/app/views/shared/_head.html.erb
  server/webapp/WEB-INF/rails.new/spec/javascripts/version_updater_spec.js
  server/webapp/WEB-INF/rails.new/spec/webpack/models/shared/version_updater_spec.js
  server/webapp/WEB-INF/rails.new/spec/webpack/views/data_sharing_settings/data_sharing_settings_widget_spec.js
  server/webapp/WEB-INF/rails.new/webpack/models/shared/version_updater.js
  server/webapp/WEB-INF/rails.new/webpack/single_page_apps/version_update_checker_for_rails.js
  server/webapp/WEB-INF/rails.new/webpack/views/data_sharing_settings/toggle_consent_widget.js.msx
  server/webapp/WEB-INF/vm/shared/_footer.vm
  server/webapp/WEB-INF/vm/shared/_header.vm
Labels: metrics-collection

#4951 Do not Set Usage Data Last Reported At Time on usage data initialization
  server/src/main/java/com/thoughtworks/go/server/service/datasharing/DataSharingUsageStatisticsReportingService.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/datasharing/DataSharingUsageStatisticsReportingServiceIntegrationTest.java
Labels: metrics-collection

#4957 Add agent hostname to analytics modal header
  server/webapp/WEB-INF/rails.new/spec/webpack/views/agents/agent_row_widget_spec.js
  server/webapp/WEB-INF/rails.new/webpack/views/agents/agent_analytics_widget.js.msx
Labels: analytics

#4958 Do not apply basic auth on web hook apis in at filter level
  server/src/main/java/com/thoughtworks/go/server/newsecurity/filterchains/AuthenticationFilterChain.java
  server/src/test-fast/java/com/thoughtworks/go/server/newsecurity/filterchains/AuthenticationFilterChainTest.java
Labels: apis

#4954 Refactored publish artifact view
  server/webapp/WEB-INF/rails.new/app/assets/javascripts/publish_artifact.js
  server/webapp/WEB-INF/rails.new/app/views/admin/jobs/_artifact_configs.html.erb
  server/webapp/WEB-INF/rails.new/app/views/admin/jobs/_external_artifact_form.html.erb
  server/webapp/WEB-INF/rails.new/spec/javascripts/publish_artifact_spec.js
  server/webapp/WEB-INF/rails.new/spec/views/admin/jobs/artifacts_html_spec.rb
Labels: artifacts

#4960 Update usage data remote server url
  base/src/main/java/com/thoughtworks/go/util/SystemEnvironment.java
Labels: metrics-collection

#4968 Using a different public key for data-sharing.
  api/api-data-sharing-usage-data-v1/src/main/java/com/thoughtworks/go/apiv1/datasharing/usagedata/UsageStatisticsControllerV1Delegate.java
  api/api-data-sharing-usage-data-v1/src/test/groovy/com/thoughtworks/go/apiv1/datasharing/usagedata/UsageStatisticsControllerV1DelegateTest.groovy
  api/api-data-sharing-usage-data-v1/src/test/resources/datasharing-public.pem
  server/src/main/resources/datasharing-public.pem
  server/webapp/WEB-INF/rails.new/spec/webpack/views/data_sharing_settings/data_sharing_settings_widget_spec.js
  server/webapp/WEB-INF/rails.new/webpack/views/data_sharing_settings/toggle_consent_widget.js.msx
Labels: metrics-collection

#4972 Pass along encrypted data while reporting to the data sharing server
  server/webapp/WEB-INF/rails.new/spec/webpack/models/shared/usage_data_reporter_spec.js
  server/webapp/WEB-INF/rails.new/webpack/models/shared/usage_data_reporter.js
Labels: data-sharing
