Repository gocd/gocd, pull requests merged in 2018-04, with the labels that each got.

#4593 Bugfix: Validation of Build and Test Artifacts with same src and dest
  common/src/test/java/com/thoughtworks/go/domain/ArtifactConfigsTest.java
  config/config-api/src/main/java/com/thoughtworks/go/config/ArtifactConfigs.java
  config/config-api/src/main/java/com/thoughtworks/go/config/BuildArtifactConfig.java
  config/config-api/src/main/java/com/thoughtworks/go/config/BuiltinArtifactConfig.java
  config/config-api/src/main/java/com/thoughtworks/go/config/TestArtifactConfig.java
  config/config-api/src/test/java/com/thoughtworks/go/config/BuildArtifactConfigTest.java
  domain/src/main/java/com/thoughtworks/go/domain/ArtifactPlan.java
  server/src/test-fast/java/com/thoughtworks/go/config/ConfigConverterTest.java
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v1/admin/authorization/authorization_config_representer_spec.rb
Labels: artifacts

#4576 Artifact Store Apis and Entity commands
  api/api-artifact-store-config-v1/build.gradle
  api/api-artifact-store-config-v1/src/main/java/com/thoughtworks/go/apiv1/artifactstoreconfig/ArtifactStoreConfigControllerDelegate.java
  api/api-artifact-store-config-v1/src/main/java/com/thoughtworks/go/apiv1/artifactstoreconfig/representers/ArtifactStoreRepresenter.java
  api/api-artifact-store-config-v1/src/main/java/com/thoughtworks/go/apiv1/artifactstoreconfig/representers/ArtifactStoresRepresenter.java
  api/api-artifact-store-config-v1/src/main/java/com/thoughtworks/go/apiv1/artifactstoreconfig/spring/ArtifactStoreConfigController.java
  api/api-artifact-store-config-v1/src/test/groovy/com/thoughtworks/go/apiv1/artifactstoreconfig/ArtifactStoreConfigControllerDelegateTest.groovy
  api/api-artifact-store-config-v1/src/test/groovy/com/thoughtworks/go/apiv1/artifactstoreconfig/representers/ArtifactStoreRepresenterTest.groovy
  api/api-artifact-store-config-v1/src/test/groovy/com/thoughtworks/go/apiv1/artifactstoreconfig/representers/ArtifactStoresRepresenterTest.groovy
  api/api-base/src/main/java/com/thoughtworks/go/api/representers/ConfigurationPropertyRepresenter.java
  api/api-base/src/test/groovy/com/thoughtworks/go/api/representers/ConfigurationPropertyRepresenterTest.groovy
  api/api-roles-config-v1/src/main/java/com/thoughtworks/go/apiv1/admin/security/representers/PluginRoleConfigRepresenter.java
  config/config-api/src/main/java/com/thoughtworks/go/config/ArtifactConfigs.java
  config/config-api/src/main/java/com/thoughtworks/go/config/PluggableArtifactConfig.java
  config/config-api/src/main/java/com/thoughtworks/go/config/PluginProfile.java
  server/src/main/java/com/thoughtworks/go/config/update/ArtifactStoreConfigCommand.java
  server/src/main/java/com/thoughtworks/go/config/update/CreateArtifactStoreConfigCommand.java
  server/src/main/java/com/thoughtworks/go/config/update/DeleteArtifactStoreConfigCommand.java
  server/src/main/java/com/thoughtworks/go/config/update/UpdateArtifactStoreConfigCommand.java
  server/src/main/java/com/thoughtworks/go/server/service/ArtifactStoreService.java
  server/src/main/java/com/thoughtworks/go/server/service/EntityHashingService.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/ArtifactStoreConfigCommandTest.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/CreateArtifactStoreConfigCommandTest.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/DeleteArtifactStoreConfigCommandTest.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/UpdateArtifactStoreConfigCommandTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/ArtifactStoreServiceTest.java
  server/webapp/WEB-INF/applicationContext-global.xml
  server/webapp/WEB-INF/urlrewrite.xml
  settings.gradle
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: artifacts

#4526 Pipeline pause message div is present when pipeline is not paused (resolved)
  server/webapp/WEB-INF/rails.new/spec/webpack/views/dashboard/pipeline_widget_spec.js
  server/webapp/WEB-INF/rails.new/webpack/views/dashboard/pipeline_operations_widget.js.msx
Labels: dashboard

#4517 Skipping the empty pipeline groups from pipeline selection response
  api/api-pipeline-selection-v1/src/main/java/com/thoughtworks/go/apiv1/pipelineselection/representers/PipelineSelectionsRepresenter.java
  api/api-pipeline-selection-v1/src/test/groovy/com/thoughtworks/go/apiv1/pipelineselection/representers/PipelineSelectionsRepresenterTest.groovy
Labels: dashboard

#4605 Edit 106.xsl to add the xsl transform to convert pluggable artifact to type external.
  config/config-server/src/main/resources/upgrades/106.xsl
  server/src/test-integration/java/com/thoughtworks/go/config/GoConfigMigrationIntegrationTest.java
Labels: artifacts

#4586 Shows auto suggestions in trigger with options modal even when exact SHA is pasted.
  server/webapp/WEB-INF/rails.new/webpack/views/dashboard/trigger_with_options/material_search_results_widget.js.msx
Labels: dashboard

#4615 Render bad request if the representer throws an exception while serializing or deserializing unsupported properties for resources.(#4608)
  server/webapp/WEB-INF/rails.new/app/presenters/api_v1/base_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v2/base_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v3/base_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v4/base_representer.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v5/base_representer.rb
Labels: bug

#4579 Show tooltip for the disabled elements on the new dashboard
  server/webapp/WEB-INF/rails.new/app/assets/new_stylesheets/frameworks.scss
  server/webapp/WEB-INF/rails.new/app/assets/stylesheets/foundation_and_overrides.scss
  server/webapp/WEB-INF/rails.new/spec/webpack/models/dashboard/pipeline_spec.js
  server/webapp/WEB-INF/rails.new/spec/webpack/views/dashboard/dashboard_widget_spec.js
  server/webapp/WEB-INF/rails.new/spec/webpack/views/dashboard/pipeline_widget_spec.js
  server/webapp/WEB-INF/rails.new/webpack/helpers/form_helper.js.msx
  server/webapp/WEB-INF/rails.new/webpack/models/dashboard/pipeline.js
  server/webapp/WEB-INF/rails.new/webpack/views/dashboard/dashboard_widget.js.msx
  server/webapp/WEB-INF/rails.new/webpack/views/dashboard/pipeline_header_widget.js.msx
  server/webapp/WEB-INF/rails.new/webpack/views/dashboard/pipeline_operations_widget.js.msx
Labels: dashboard

#4557 Plugin settings api refactoring
  common/src/main/java/com/thoughtworks/go/server/service/result/DefaultLocalizedOperationResult.java
  common/src/main/java/com/thoughtworks/go/server/service/result/HttpLocalizedOperationResult.java
  common/src/main/java/com/thoughtworks/go/server/service/result/LocalizedOperationResult.java
  common/src/main/java/com/thoughtworks/go/server/service/result/SubsectionLocalizedOperationResult.java
  config/config-api/src/main/java/com/thoughtworks/go/config/builder/ConfigurationPropertyBuilder.java
  config/config-api/src/main/java/com/thoughtworks/go/domain/config/ConfigurationProperty.java
  plugin-infra/go-plugin-domain/src/main/java/com/thoughtworks/go/plugin/domain/common/PluginInfo.java
  plugin-infra/go-plugin-infra/src/main/java/com/thoughtworks/go/plugin/infra/DefaultPluginManager.java
  plugin-infra/go-plugin-infra/src/main/java/com/thoughtworks/go/plugin/infra/PluginManager.java
  plugin-infra/go-plugin-infra/src/test/java/com/thoughtworks/go/plugin/infra/DefaultPluginManagerTest.java
  server/src/main/java/com/thoughtworks/go/server/domain/PluginSettings.java
  server/src/main/java/com/thoughtworks/go/server/service/PluginService.java
  server/src/main/java/com/thoughtworks/go/server/service/plugins/processor/pluginsettings/PluginSettingsRequestProcessor.java
  server/src/test-fast/java/com/thoughtworks/go/server/domain/PluginSettingsTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/PluginServiceTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/plugins/processor/pluginsettings/PluginSettingsRequestProcessorTest.java
  server/webapp/WEB-INF/rails.new/app/controllers/api_v1/admin/plugin_settings_controller.rb
  server/webapp/WEB-INF/rails.new/app/presenters/api_v1/config/plugin_settings_representer.rb
  server/webapp/WEB-INF/rails.new/spec/controllers/api_v1/admin/plugin_settings_controller_spec.rb
  server/webapp/WEB-INF/rails.new/spec/presenters/api_v1/config/plugin_settings_representer_spec.rb
  server/webapp/localize.xml
Labels: apis

#4525 Trigger with revisions issues (resolved)
  server/webapp/WEB-INF/rails.new/.babelrc
  server/webapp/WEB-INF/rails.new/app/assets/new_stylesheets/single_page_apps/new_dashboard.scss
  server/webapp/WEB-INF/rails.new/package.json
  server/webapp/WEB-INF/rails.new/spec/webpack/models/dashboard/material_spec.js
  server/webapp/WEB-INF/rails.new/spec/webpack/models/dashboard/trigger_with_options_info_spec.js
  server/webapp/WEB-INF/rails.new/spec/webpack/views/dashboard/model/material_search_vm_spec.js
  server/webapp/WEB-INF/rails.new/spec/webpack/views/dashboard/trigger_with_options/material_info_widget_spec.js
  server/webapp/WEB-INF/rails.new/spec/webpack/views/dashboard/trigger_with_options/material_search_results_widget_spec.js
  server/webapp/WEB-INF/rails.new/spec/webpack/views/dashboard/trigger_with_options/materials_widget_spec.js
  server/webapp/WEB-INF/rails.new/webpack/models/dashboard/material.js
  server/webapp/WEB-INF/rails.new/webpack/models/dashboard/trigger_with_options_info.js
  server/webapp/WEB-INF/rails.new/webpack/views/dashboard/pipeline_operations_widget.js.msx
  server/webapp/WEB-INF/rails.new/webpack/views/dashboard/trigger_with_options/material_info_widget.js.msx
  server/webapp/WEB-INF/rails.new/webpack/views/dashboard/trigger_with_options/material_search_results_widget.js.msx
  server/webapp/WEB-INF/rails.new/webpack/views/dashboard/trigger_with_options/materials_widget.js.msx
  server/webapp/WEB-INF/rails.new/webpack/views/dashboard/trigger_with_options/modal_body.js.msx
  server/webapp/WEB-INF/rails.new/yarn.lock
  tools/.eslintrc.json
  tools/package.json
  tools/yarn.lock
Labels: dashboard

#4551 Add a loading spinner to analytics frames in the analytics dashboard
  server/webapp/WEB-INF/rails.new/app/assets/new_stylesheets/shared/_analytics-common.scss
  server/webapp/WEB-INF/rails.new/app/assets/new_stylesheets/single_page_apps/analytics.scss
  server/webapp/WEB-INF/rails.new/app/assets/new_stylesheets/single_page_apps/new_dashboard.scss
  server/webapp/WEB-INF/rails.new/app/controllers/analytics_controller.rb
  server/webapp/WEB-INF/rails.new/webpack/views/analytics/global_metrics.js.msx
  server/webapp/WEB-INF/rails.new/webpack/views/analytics/pipeline_metrics.js.msx
  server/webapp/WEB-INF/rails.new/webpack/views/dashboard/pipeline_analytics_widget.js.msx
  server/webapp/WEB-INF/rails.new/webpack/views/shared/analytics_iframe_widget.js.msx
Labels: analytics

#4676 Consider DST in serverTimezoneUTCOffset data variable passed to all the SPAs (#4675)
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/spring/InitialContextProvider.java
Labels: dashboard

#4678 Show Pipeline analytics on each pipeline only when analytics plugin supports at least one pipeline level analytics
  server/webapp/WEB-INF/rails.new/webpack/single_page_apps/new_dashboard.js
Labels: analytics

#4693 Add artifact stores css to the assets precompile list.
  server/rails.gradle
  server/webapp/WEB-INF/rails.new/config/initializers/assets.rb
Labels: artifacts
