Repository gocd/gocd, pull requests merged in 2018-06, with the labels that each got.

#4808 Append context path only when given url does'n not have it.
  server/webapp/WEB-INF/rails.new/app/assets/javascripts/dashboard_global.js
  server/webapp/WEB-INF/rails.new/app/assets/javascripts/old_application.js
  server/webapp/WEB-INF/rails.new/app/assets/javascripts/pipeline.js
  server/webapp/WEB-INF/rails.new/app/assets/javascripts/pipeline_history.js
  server/webapp/WEB-INF/rails.new/spec/javascripts/pipeline_history_spec.js
Labels: bug

#4831 Fixed positioning of footer on stage settings page
  server/webapp/WEB-INF/rails.new/app/views/layouts/pipelines/stage.html.erb
Labels: bug, ui / ux

#4850 Do not throw an error if `attributes` is not passed for ant, nant, rake, exec tasks.
  api/api-shared-v6/src/main/java/com/thoughtworks/go/apiv6/shared/representers/stages/tasks/AntTaskRepresenter.java
  api/api-shared-v6/src/main/java/com/thoughtworks/go/apiv6/shared/representers/stages/tasks/ExecTaskRepresenter.java
  api/api-shared-v6/src/main/java/com/thoughtworks/go/apiv6/shared/representers/stages/tasks/FetchTaskRepresenter.java
  api/api-shared-v6/src/main/java/com/thoughtworks/go/apiv6/shared/representers/stages/tasks/NantTaskRepresenter.java
  api/api-shared-v6/src/main/java/com/thoughtworks/go/apiv6/shared/representers/stages/tasks/PluggableTaskRepresenter.java
  api/api-shared-v6/src/main/java/com/thoughtworks/go/apiv6/shared/representers/stages/tasks/RakeTaskRepresenter.java
  api/api-shared-v6/src/main/java/com/thoughtworks/go/apiv6/shared/representers/stages/tasks/TaskRepresenter.java
  api/api-shared-v6/src/test/groovy/com/thoughtworks/go/apiv6/shared/representers/stages/tasks/AntTaskRepresenterTest.groovy
  api/api-shared-v6/src/test/groovy/com/thoughtworks/go/apiv6/shared/representers/stages/tasks/ExecTaskRepresenterTest.groovy
  api/api-shared-v6/src/test/groovy/com/thoughtworks/go/apiv6/shared/representers/stages/tasks/NantTaskRepresenterTest.groovy
  api/api-shared-v6/src/test/groovy/com/thoughtworks/go/apiv6/shared/representers/stages/tasks/RakeTaskRepresenterTest.groovy
Labels: apis

#4868 Fixed infinite redirect issue for authentications.
  server/src/main/java/com/thoughtworks/go/server/newsecurity/controllers/AuthenticationController.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/filters/BasicAuthenticationWithRedirectToLoginFilter.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/filters/ReAuthenticationWithRedirectToLoginFilter.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/filters/UserEnabledCheckFilterWithRedirectToLoginPage.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/providers/AbstractPluginAuthenticationProvider.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/utils/SessionUtils.java
  server/src/test-fast/java/com/thoughtworks/go/server/newsecurity/controllers/AuthenticationControllerTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/newsecurity/filters/BasicAuthenticationWithRedirectToLoginFilterTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/newsecurity/filters/ReAuthenticationWithRedirectToLoginFilterTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/newsecurity/filters/UserEnabledCheckFilterWithRedirectToLoginPageTest.java
Labels: authentication, bug

#4792 Publish external artifact view
  config/config-api/src/main/java/com/thoughtworks/go/config/ArtifactConfigs.java
  config/config-api/src/main/java/com/thoughtworks/go/config/PluggableArtifactConfig.java
  config/config-api/src/main/java/com/thoughtworks/go/domain/config/Configuration.java
  config/config-api/src/main/java/com/thoughtworks/go/domain/config/ConfigurationProperty.java
  config/config-api/src/test/java/com/thoughtworks/go/config/ArtifactConfigsTest.java
  config/config-api/src/test/java/com/thoughtworks/go/domain/config/ConfigurationTest.java
  plugin-infra/plugin-metadata-store/src/main/java/com/thoughtworks/go/plugin/access/artifact/ArtifactMetadataStore.java
  server/src/main/java/com/thoughtworks/go/config/update/PipelineConfigCommand.java
  server/src/main/java/com/thoughtworks/go/config/update/TemplateConfigCommand.java
  server/src/main/java/com/thoughtworks/go/server/service/ArtifactStoreService.java
  server/src/main/java/com/thoughtworks/go/server/service/ExternalArtifactsService.java
  server/src/main/java/com/thoughtworks/go/server/service/plugins/builder/DefaultPluginInfoFinder.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/CreatePipelineConfigCommandTest.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/UpdatePipelineConfigCommandTest.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/UpdateTemplateConfigCommandTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/ExternalArtifactsServiceTest.java
  server/webapp/WEB-INF/rails.new/app/assets/new_stylesheets/shared/_go-variables.scss
  server/webapp/WEB-INF/rails.new/app/assets/stylesheets/new-theme.scss
  server/webapp/WEB-INF/rails.new/app/controllers/admin/jobs_controller.rb
  server/webapp/WEB-INF/rails.new/app/views/admin/jobs/_artifact_configs.html.erb
  server/webapp/WEB-INF/rails.new/app/views/admin/jobs/_builtin_artifact_form.html.erb
  server/webapp/WEB-INF/rails.new/app/views/admin/jobs/_external_artifact_form.html.erb
  server/webapp/WEB-INF/rails.new/app/views/admin/jobs/artifacts.html.erb
  server/webapp/WEB-INF/rails.new/app/views/admin/shared/_form_submit.html.erb
  server/webapp/WEB-INF/rails.new/lib/java_imports.rb
  server/webapp/WEB-INF/rails.new/lib/services.rb
  server/webapp/WEB-INF/rails.new/spec/controllers/admin/jobs_controller_view_spec.rb
  server/webapp/WEB-INF/rails.new/spec/support/java_spec_imports.rb
  server/webapp/WEB-INF/rails.new/spec/views/admin/jobs/artifacts_html_spec.rb
Labels: artifacts

#4886 Update template API - validate fetch and publish config in the context of the associated pipelines.
  config/config-api/src/main/java/com/thoughtworks/go/config/FetchPluggableArtifactTask.java
  config/config-api/src/main/java/com/thoughtworks/go/config/PipelineTemplateConfig.java
  config/config-api/src/main/java/com/thoughtworks/go/config/PluggableArtifactConfig.java
  config/config-api/src/test/java/com/thoughtworks/go/config/PipelineTemplateConfigTest.java
  server/src/main/java/com/thoughtworks/go/config/update/TemplateConfigCommand.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/UpdateTemplateConfigCommandTest.java
Labels: apis, templates

#4870 Introduce usagedata encryption API
  api/api-base/src/main/java/com/thoughtworks/go/api/ApiController.java
  api/api-data-sharing-usage-data-v1/src/main/java/com/thoughtworks/go/apiv1/datasharing/usagedata/UsageStatisticsControllerV1Delegate.java
  api/api-data-sharing-usage-data-v1/src/main/java/com/thoughtworks/go/apiv1/datasharing/usagedata/spring/UsageStatisticsControllerV1.java
  api/api-data-sharing-usage-data-v1/src/test/groovy/com/thoughtworks/go/apiv1/datasharing/usagedata/UsageStatisticsControllerV1DelegateTest.groovy
  api/api-data-sharing-usage-data-v1/src/test/resources/private_key.pem
  api/api-data-sharing-usage-data-v1/src/test/resources/public_key.pem
  server/src/main/java/com/thoughtworks/go/server/util/RSAEncryptionHelper.java
  server/src/test-fast/java/com/thoughtworks/go/server/util/RSAEncryptionHelperTest.java
  server/src/test-fast/resources/rsa/private_key.pem
  server/src/test-fast/resources/rsa/public_key.pem
  spark/spark-base/src/test/groovy/com/thoughtworks/go/api/mocks/MockHttpServletResponseAssert.groovy
Labels: metrics-collection
