Repository gocd/gocd, pull requests merged in 2018-12, with the labels that each got.

#5396 Ship the windows installer with OpenJDK instead of Oracle's JRE 8
  buildSrc/src/main/groovy/com/thoughtworks/go/build/WindowsPackagingTask.groovy
  installers/windows-shared/JavaHome.ini
  installers/windows-shared/windows-installer-base.nsi
  installers/windows.gradle
Labels: installers

#5494 Config Repo Plugin Configuration
  server/webapp/WEB-INF/rails/webpack/models/config_repos/config_repos_crud.ts
  server/webapp/WEB-INF/rails/webpack/models/config_repos/spec/config_repos_crud_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/config_repos/types.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/config_repos/modals.tsx
Labels: config repo

#5501 BugFix: KeyValuePair component should render number value properly
  server/webapp/WEB-INF/rails/webpack/views/components/key_value_pair/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/key_value_pair/spec/index_spec.tsx
Labels: bug

#5513 Remove Config Repo pipelines from Scheduler on delete
  server/src/main/java/com/thoughtworks/go/server/service/PipelineScheduler.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/PipelineSchedulerTest.java
Labels: config repo

#5516 Fix VSM pipeline error message styles (#5514)
  server/webapp/WEB-INF/rails/app/assets/javascripts/vsm_renderer.js
  server/webapp/WEB-INF/rails/app/assets/stylesheets/module.scss
Labels: bug, vsm

#5515 Add running jobs information to drain mode info API (#5190)
  api/api-server-drain-mode-v1/src/main/java/com/thoughtworks/go/apiv1/serverdrainmode/ServerDrainModeControllerV1.java
  api/api-server-drain-mode-v1/src/main/java/com/thoughtworks/go/apiv1/serverdrainmode/representers/DrainModeInfoRepresenter.java
  api/api-server-drain-mode-v1/src/test/groovy/com/thoughtworks/go/apiv1/serverdrainmode/ServerDrainModeControllerV1Test.groovy
  api/api-server-drain-mode-v1/src/test/groovy/com/thoughtworks/go/apiv1/serverdrainmode/representers/DrainModeInfoRepresenterTest.groovy
  server/src/main/java/com/thoughtworks/go/server/dao/JobInstanceDao.java
  server/src/main/java/com/thoughtworks/go/server/dao/JobInstanceSqlMapDao.java
  server/src/main/java/com/thoughtworks/go/server/service/JobInstanceService.java
  server/src/main/resources/com/thoughtworks/go/server/dao/maps/JobInstance.xml
  server/src/test-fast/java/com/thoughtworks/go/server/service/JobInstanceServiceTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/dao/JobInstanceSqlMapDaoTest.java
Labels: drain-mode

#5520 Remove config_repos_ui toggle
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/java/com/thoughtworks/go/server/web/GoVelocityView.java
  server/src/main/resources/available.toggles
  server/webapp/WEB-INF/rails/app/helpers/application_helper.rb
  server/webapp/WEB-INF/rails/app/views/shared/_body_data_attrs.html.erb
  server/webapp/WEB-INF/rails/app/views/shared/_dropdown_admin.html.erb
  server/webapp/WEB-INF/rails/webpack/helpers/spa_base.tsx
  server/webapp/WEB-INF/rails/webpack/single_page_apps/header_footer_shim.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/site_menu/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/site_menu/spec/index_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/partials/site_header.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/partials/spec/site_header_spec.tsx
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/ConfigReposDelegate.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/spring/SpaControllers.java
  spark/spark-spa/src/main/resources/velocity/layouts/component_layout.vm
  spark/spark-spa/src/main/resources/velocity/layouts/single_page_app.vm
  spark/spark-spa/src/test/groovy/com/thoughtworks/go/spark/spa/ConfigReposDelegateTest.groovy
Labels: technical-debt

#5524 Add `name` attribute to Header Icon and use it for `data-test-id`
  server/webapp/WEB-INF/rails/webpack/views/components/header_icon/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/config_repos/config_repos_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/elastic_profiles/elastic_profiles_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_plugins/plugin_widget.tsx
Labels: ui / ux

#5527 Show the first personalization tab pipelines on dashboard load (#5512)
  server/webapp/WEB-INF/rails/webpack/single_page_apps/new_dashboard.js
Labels: bug, dashboard

#5536 Remove unnecessary IE8 check from VSM controller
  server/webapp/WEB-INF/rails/app/controllers/value_stream_map_controller.rb
  server/webapp/WEB-INF/rails/app/helpers/pipelines_helper.rb
  server/webapp/WEB-INF/rails/spec/controllers/value_stream_map_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/helpers/pipelines_helper_spec.rb
Labels: technical, vsm

#5535 Fix links pointing to pipeline dependency graph (#5406)
  server/webapp/WEB-INF/rails/app/helpers/pipelines_helper.rb
  server/webapp/WEB-INF/rails/app/views/shared/_build_cause.html.erb
  server/webapp/WEB-INF/rails/spec/helpers/pipelines_helper_spec.rb
  server/webapp/WEB-INF/rails/spec/views/shared/_build_cause_html_spec.rb
  server/webapp/WEB-INF/rails/spec/views/shared/_build_cause_popup_html_spec.rb
  server/webapp/WEB-INF/rails/spec/webpack/views/dashboard/trigger_with_options/material_revision_widget_spec.js
  server/webapp/WEB-INF/rails/webpack/views/dashboard/trigger_with_options/material_revision_widget.js.msx
Labels: bug

#5532 Fix Dashboard rendering bug
  server/webapp/WEB-INF/rails/webpack/single_page_apps/new_dashboard.js
  server/webapp/WEB-INF/rails/webpack/views/dashboard/models/personalization_vm.js
Labels: bug, dashboard

#5545 Add Artifact Stores to menu
  server/webapp/WEB-INF/rails/webpack/views/components/site_menu/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/site_menu/spec/index_spec.tsx
Labels: ui / ux

#5546 Fix minor alignments on dashboard
  server/webapp/WEB-INF/rails/app/assets/new_stylesheets/single_page_apps/pipeline_configs/_dashboard_view_tabs.scss
  server/webapp/WEB-INF/rails/app/assets/new_stylesheets/single_page_apps/pipeline_configs/_personalize_views_editor.scss
Labels: bug, dashboard, ui / ux

#5549 Drain Mode enable/disable API (#5190)
  api/api-server-drain-mode-v1/src/main/java/com/thoughtworks/go/apiv1/serverdrainmode/ServerDrainModeControllerV1.java
  api/api-server-drain-mode-v1/src/test/groovy/com/thoughtworks/go/apiv1/serverdrainmode/ServerDrainModeControllerV1Test.groovy
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: drain-mode

#5556 Merge drain mode settings information with info API (#5190)
  api/api-server-drain-mode-v1/src/main/java/com/thoughtworks/go/apiv1/serverdrainmode/ServerDrainModeControllerV1.java
  api/api-server-drain-mode-v1/src/main/java/com/thoughtworks/go/apiv1/serverdrainmode/representers/DrainModeInfoRepresenter.java
  api/api-server-drain-mode-v1/src/main/java/com/thoughtworks/go/apiv1/serverdrainmode/representers/DrainModeSettingsRepresenter.java
  api/api-server-drain-mode-v1/src/test/groovy/com/thoughtworks/go/apiv1/serverdrainmode/ServerDrainModeControllerV1Test.groovy
  api/api-server-drain-mode-v1/src/test/groovy/com/thoughtworks/go/apiv1/serverdrainmode/representers/DrainModeInfoRepresenterTest.groovy
  api/api-server-drain-mode-v1/src/test/groovy/com/thoughtworks/go/apiv1/serverdrainmode/representers/DrainModeSettingsRepresenterTest.groovy
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: drain-mode

#5567 Support for placeholder on textfield component
  server/webapp/WEB-INF/rails/webpack/views/components/forms/input_fields.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/config_repos/modals.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/kitchen_sink.tsx
Labels: ui / ux

#5506 Send an email notification when job is cancelled due to timeout (#5370)
  domain/src/main/java/com/thoughtworks/go/domain/Stage.java
  domain/src/main/java/com/thoughtworks/go/domain/StageState.java
  domain/src/main/java/com/thoughtworks/go/server/domain/StageStatusHandler.java
  server/src/main/java/com/thoughtworks/go/server/messaging/JobStatusListener.java
  server/src/main/java/com/thoughtworks/go/server/service/StageService.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/StageServiceTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/messaging/JobStatusListenerTest.java
Labels: bug

#5581 Fix UI issues (#5464)
  server/webapp/WEB-INF/rails/webpack/views/pages/elastic_profiles/modals.tsx
Labels: ui / ux

#5586 Make Profile Usage modal large size
  server/webapp/WEB-INF/rails/webpack/views/pages/elastic_profiles/index.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/elastic_profiles/index.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/elastic_profiles/modals.tsx
Labels: SPA

#5590 Show spinner while loading Edit/Clone modal on Elastic Profiles SPA
  server/webapp/WEB-INF/rails/webpack/views/pages/elastic_profiles.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/elastic_profiles/index.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/elastic_profiles/index.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/elastic_profiles/modals.tsx
Labels: SPA

#5591 #5559 - Fixed ajax-poller causing performance issue
  server/webapp/WEB-INF/rails/webpack/helpers/ajax_poller.ts
Labels: performance

#5597 Stop loading cruise-config.xml from fileSystem during drain mode(#5190)
  server/src/main/java/com/thoughtworks/go/config/CachedGoConfig.java
  server/src/test-fast/java/com/thoughtworks/go/config/CachedGoConfigTest.java
  server/src/test-fast/java/com/thoughtworks/go/config/GoFileConfigDataSourceTest.java
  server/src/test-shared/java/com/thoughtworks/go/util/GoConfigFileHelper.java
Labels: drain-mode

#5601 Delete old elastic profiles page
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/webapp/WEB-INF/rails/app/assets/new_stylesheets/single_page_apps/elastic_profiles.scss
  server/webapp/WEB-INF/rails/spec/webpack/models/elastic_profiles/elastic_profiles_spec.js
  server/webapp/WEB-INF/rails/spec/webpack/views/elastic_profiles/elastic_profiles_widget_spec.js
  server/webapp/WEB-INF/rails/webpack/single_page_apps/elastic_profiles.tsx
  server/webapp/WEB-INF/rails/webpack/views/elastic_profiles/elastic_profile_modal_body.js.msx
  server/webapp/WEB-INF/rails/webpack/views/elastic_profiles/elastic_profile_widget.js.msx
  server/webapp/WEB-INF/rails/webpack/views/elastic_profiles/elastic_profiles_widget.js.msx
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/spring/SpaControllers.java
  spark/spark-spa/src/main/resources/velocity/elastic_profiles/index.vm
Labels: SPA, technical-debt

#5606 Remove page specific vm layouts of componentized pages
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/ConfigReposController.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/DrainModeController.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/ElasticProfilesController.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/KitchenSinkController.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/PluginsController.java
  spark/spark-spa/src/main/resources/velocity/config_repos/index.vm
  spark/spark-spa/src/main/resources/velocity/drain_mode/index.vm
  spark/spark-spa/src/main/resources/velocity/elastic_profiles/index.vm
  spark/spark-spa/src/main/resources/velocity/plugins/index.vm
Labels: SPA

#5612 Remove drain mode feature toggle
  api/api-server-drain-mode-v1/src/main/java/com/thoughtworks/go/apiv1/serverdrainmode/ServerDrainModeControllerV1.java
  api/api-server-drain-mode-v1/src/test/groovy/com/thoughtworks/go/apiv1/serverdrainmode/ServerDrainModeControllerV1Test.groovy
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/DrainModeController.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/spring/SpaControllers.java
Labels: drain-mode

#5623 Moving artifact store spa to typescript - #5605
  .gitignore
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/webapp/WEB-INF/rails/webpack/helpers/spark_routes.ts
  server/webapp/WEB-INF/rails/webpack/models/artifact_stores/artifact_stores_crud.ts
  server/webapp/WEB-INF/rails/webpack/models/artifact_stores/artifact_stores_new.ts
  server/webapp/WEB-INF/rails/webpack/models/artifact_stores/spec/artifact_stores_crud_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/artifact_stores/spec/artifact_stores_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/artifact_stores/spec/test_data.ts
  server/webapp/WEB-INF/rails/webpack/models/shared/configuration.ts
  server/webapp/WEB-INF/rails/webpack/models/shared/plugin_infos_new/extensions.ts
  server/webapp/WEB-INF/rails/webpack/models/shared/plugin_infos_new/spec/test_data.ts
  server/webapp/WEB-INF/rails/webpack/single_page_apps/artifact_stores.js
  server/webapp/WEB-INF/rails/webpack/single_page_apps/artifact_stores.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/forms/input_fields.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/modal/entity_modal.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/artifact_stores.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/artifact_stores/artifact_store_modal_body.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/artifact_stores/artifact_stores_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/artifact_stores/modals.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/artifact_stores/spec/artifact_store_modal_body_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/artifact_stores/spec/artifact_stores_widget_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/artifact_stores/spec/test_helper.tsx
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/ArtifactStoresController.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/spring/SpaControllers.java
Labels: SPA

#5632 Auth config spa fixes
  server/webapp/WEB-INF/rails/webpack/models/auth_configs/auth_configs_crud.ts
  server/webapp/WEB-INF/rails/webpack/models/auth_configs/auth_configs_new.ts
  server/webapp/WEB-INF/rails/webpack/views/components/modal/entity_modal.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/modal/index.scss
  server/webapp/WEB-INF/rails/webpack/views/components/modal/index.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/auth_configs.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/auth_configs/auth_config_modal_body.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/auth_configs/modals.tsx
Labels: SPA

#5630 Moving roles SPA to typescript
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/webapp/WEB-INF/rails/webpack/helpers/spark_routes.ts
  server/webapp/WEB-INF/rails/webpack/models/auth_configs/auth_configs_new.ts
  server/webapp/WEB-INF/rails/webpack/models/roles/roles_crud.ts
  server/webapp/WEB-INF/rails/webpack/models/roles/roles_new.ts
  server/webapp/WEB-INF/rails/webpack/models/roles/spec/roles_crud_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/roles/spec/roles_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/shared/plugin_infos_new/spec/test_data.ts
  server/webapp/WEB-INF/rails/webpack/single_page_apps/roles.js
  server/webapp/WEB-INF/rails/webpack/single_page_apps/roles.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/artifact_stores/spec/artifact_store_modal_body_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/artifact_stores/spec/artifact_stores_widget_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/auth_configs/spec/auth_configs_widget_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/roles.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/roles/index.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/roles/index.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/roles/modals.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/roles/role_modal_body.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/roles/role_modal_body_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/roles/roles_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/roles/spec/role_modal_body_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/roles/spec/roles_widget_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/roles/spec/test_data.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/roles/users_widget.tsx
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/RolesController.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/spring/SpaControllers.java
Labels: SPA

#5634 Show error on delete when artifact store is referred in pipelines
  server/webapp/WEB-INF/rails/webpack/views/pages/artifact_stores.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/artifact_stores/modals.tsx
Labels: SPA
