Repository gocd/gocd, pull requests merged in 2019-05, with the labels that each got.

#6232 [Reattempt] Encrypt publish-artifact secure-plugin-properties when configured from admin/cruise-config.xml tab
  config/config-server/src/test/java/com/thoughtworks/go/config/MagicalGoConfigXmlLoaderTest.java
  config/config-server/src/test/resources/data/pluggable_artifacts_with_params.xml
  server/src/main/java/com/thoughtworks/go/config/FullConfigSaveNormalFlow.java
  server/src/test-integration/java/com/thoughtworks/go/config/CachedGoConfigIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/config/FullConfigSaveFlowTestBase.java
  server/src/test-shared/java/com/thoughtworks/go/util/GoConfigFileHelper.java
Labels: artifacts, bug-fix

#6231 Introduce plugin infos api v6
  .gitignore
  api/api-plugin-infos-v6/build.gradle
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/PluginInfosControllerV6.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/ExtensionRepresenterResolver.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/MetadataRepresenterResolver.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/PluggableInstanceSettingsRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/PluginInfoRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/PluginInfosRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/AnalyticsPluginInfoRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/ArtifactPluginInfoRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/AuthorizationExtensionRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/ConfigRepoExtensionRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/ElasticAgentExtensionRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/ExtensionRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/NotificationPluginInfoRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/PackageMaterialExtensionRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/SCMExtensionRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/SecretsExtensionRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/TaskExtensionRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/metadata/MetadataRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/metadata/MetadataWithPartOfIdentityRepresenter.java
  api/api-plugin-infos-v6/src/main/java/com/thoughtworks/go/apiv6/plugininfos/representers/metadata/PackageMaterialMetadataRepresenter.java
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/PluginInfosControllerV6Test.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/ExtensionRepresenterResolverTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/Helper/PluginInfoMother.java
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/MetadataRepresenterResolverTest.java
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/PluginInfoRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/PluginInfosRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/AnalyticsPluginInfoRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/ArtifactPluginInfoRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/AuthorizationExtensionRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/ConfigRepoExtensionRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/ElasticAgentExtensionRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/ExtensionRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/NotificationPluginInfoRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/PackageMaterialExtensionRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/SCMExtensionRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/SecretConfigExtensionRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/extensions/TaskExtensionRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/metadata/MetadataRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/metadata/MetadataWithPartOfIdentityRepresenterTest.groovy
  api/api-plugin-infos-v6/src/test/groovy/com/thoughtworks/go/apiv6/plugininfos/representers/metadata/PackageMaterialMetadataRepresenterTest.groovy
  server/webapp/WEB-INF/applicationContext-global.xml
  settings.gradle
Labels: apis

#6239 Do not build alpine-3.6 based docker gocd agent image
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy
Labels: agents, docker-images

#6238 Encrypt publish-artifact secure-plugin-properties for templates
  config/config-api/src/main/java/com/thoughtworks/go/config/BasicCruiseConfig.java
  config/config-api/src/main/java/com/thoughtworks/go/config/CachedFetchPluggableArtifactTasks.java
  config/config-api/src/main/java/com/thoughtworks/go/config/CachedPluggableArtifactConfigs.java
  config/config-api/src/main/java/com/thoughtworks/go/config/PipelineConfig.java
  config/config-api/src/main/java/com/thoughtworks/go/config/PipelineTemplateConfig.java
  config/config-api/src/main/java/com/thoughtworks/go/config/PluggableArtifactConfig.java
  config/config-api/src/test/java/com/thoughtworks/go/config/BasicCruiseConfigTest.java
  config/config-api/src/test/java/com/thoughtworks/go/config/PipelineConfigTest.java
  config/config-api/src/test/java/com/thoughtworks/go/config/PluggableArtifactConfigTest.java
  config/config-server/src/main/java/com/thoughtworks/go/config/GoConfigCloner.java
  config/config-server/src/test/java/com/thoughtworks/go/config/GoConfigClonerTest.java
Labels: artifacts, bug-fix, templates

#6240 Encrypt secure plugin properties of plugin role configuration
  config/config-api/src/main/java/com/thoughtworks/go/config/BasicCruiseConfig.java
  config/config-api/src/main/java/com/thoughtworks/go/config/PluginRoleConfig.java
  config/config-api/src/main/java/com/thoughtworks/go/config/Role.java
  config/config-api/src/main/java/com/thoughtworks/go/config/RoleConfig.java
  config/config-api/src/test/java/com/thoughtworks/go/config/BasicCruiseConfigTest.java
  config/config-api/src/test/java/com/thoughtworks/go/config/PluginRoleConfigTest.java
  server/src/main/java/com/thoughtworks/go/config/update/RoleConfigCommand.java
  server/src/main/java/com/thoughtworks/go/config/update/RoleConfigDeleteCommand.java
  server/src/main/java/com/thoughtworks/go/server/service/RoleConfigService.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/RoleConfigCommandTest.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/RoleConfigCreateCommandTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/RoleConfigServiceTest.java
Labels: auth and role configuration, bug-fix

#6245 Do not extend pluginProfileService for elasticProfileService
  server/src/main/java/com/thoughtworks/go/config/update/ElasticAgentProfileCommand.java
  server/src/main/java/com/thoughtworks/go/config/update/ElasticAgentProfileCreateCommand.java
  server/src/main/java/com/thoughtworks/go/config/update/ElasticAgentProfileDeleteCommand.java
  server/src/main/java/com/thoughtworks/go/config/update/ElasticAgentProfileUpdateCommand.java
  server/src/main/java/com/thoughtworks/go/server/service/ElasticProfileService.java
  server/src/main/java/com/thoughtworks/go/server/service/plugins/validators/elastic/ElasticAgentProfileConfigurationValidator.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/ElasticAgentProfileCreateCommandTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/ElasticProfileServiceTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/ElasticProfileServiceIntegrationTest.java
Labels: technical, technical-debt

#6244 Simplified Add Pipeline page for new trial experience
  server/webapp/WEB-INF/rails/webpack/models/mixins/new_validatable_mixin.ts
  server/webapp/WEB-INF/rails/webpack/models/mixins/new_validatable_mixin_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/pipeline_configs/job.ts
  server/webapp/WEB-INF/rails/webpack/models/pipeline_configs/nameable_set.ts
  server/webapp/WEB-INF/rails/webpack/models/pipeline_configs/pipeline_config.ts
  server/webapp/WEB-INF/rails/webpack/models/pipeline_configs/spec/job_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/pipeline_configs/spec/nameamble_set_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/pipeline_configs/spec/stage_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/pipeline_configs/stage.ts
  server/webapp/WEB-INF/rails/webpack/views/components/forms/_awesomplete-import.scss
  server/webapp/WEB-INF/rails/webpack/views/components/forms/autocomplete.scss
  server/webapp/WEB-INF/rails/webpack/views/components/forms/autocomplete.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/components/forms/autocomplete.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/forms/input_fields.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/forms/spec/autocomplete_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/components.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/non_scm_material_fields.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/spec/task_editor_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/task_editor.tsx
Labels: improve-trial-experience

#6257 Support for username, password and encrypted password in config repo material contract.
  plugin-infra/go-plugin-config-repo/src/main/java/com/thoughtworks/go/plugin/configrepo/contract/material/CRGitMaterial.java
  plugin-infra/go-plugin-config-repo/src/main/java/com/thoughtworks/go/plugin/configrepo/contract/material/CRHgMaterial.java
  plugin-infra/go-plugin-config-repo/src/main/java/com/thoughtworks/go/plugin/configrepo/contract/material/CRP4Material.java
  plugin-infra/go-plugin-config-repo/src/main/java/com/thoughtworks/go/plugin/configrepo/contract/material/CRScmMaterial.java
  plugin-infra/go-plugin-config-repo/src/main/java/com/thoughtworks/go/plugin/configrepo/contract/material/CRSvnMaterial.java
  plugin-infra/go-plugin-config-repo/src/main/java/com/thoughtworks/go/plugin/configrepo/contract/material/CRTfsMaterial.java
  plugin-infra/go-plugin-config-repo/src/test/java/com/thoughtworks/go/plugin/configrepo/contract/CRPipelineTest.java
  plugin-infra/go-plugin-config-repo/src/test/java/com/thoughtworks/go/plugin/configrepo/contract/material/CRGitMaterialTest.java
  plugin-infra/go-plugin-config-repo/src/test/java/com/thoughtworks/go/plugin/configrepo/contract/material/CRHgMaterialTest.java
  plugin-infra/go-plugin-config-repo/src/test/java/com/thoughtworks/go/plugin/configrepo/contract/material/CRP4MaterialTest.java
  plugin-infra/go-plugin-config-repo/src/test/java/com/thoughtworks/go/plugin/configrepo/contract/material/CRSvnMaterialTest.java
  plugin-infra/go-plugin-config-repo/src/test/java/com/thoughtworks/go/plugin/configrepo/contract/material/CRTfsMaterialTest.java
  server/src/main/java/com/thoughtworks/go/config/ConfigConverter.java
  server/src/test-fast/java/com/thoughtworks/go/config/ConfigConverterTest.java
Labels: materials, url-normalization

#6260 Minor UI updates to the new Add Pipelines page
  server/webapp/WEB-INF/rails/webpack/models/pipeline_configs/spec/stage_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/pipeline_configs/stage.ts
  server/webapp/WEB-INF/rails/webpack/views/components/buttons/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/switch/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/actions.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/components.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/components.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/scm_material_fields.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/stage_editor.tsx
Labels: improve-trial-experience

#6259 Better logging for access token requests (#5923)
  server/src/main/java/com/thoughtworks/go/domain/AccessToken.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/filters/AccessTokenAuthenticationFilter.java
  server/src/main/java/com/thoughtworks/go/server/service/AccessTokenService.java
  server/src/main/resources/config/logback.xml
Labels: enhancement

#6266 Remove enable_admin_access_tokens_spa toggle
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/java/com/thoughtworks/go/server/web/GoVelocityView.java
  server/src/main/resources/available.toggles
  server/webapp/WEB-INF/rails/app/helpers/application_helper.rb
  server/webapp/WEB-INF/rails/app/views/shared/_body_data_attrs.html.erb
  server/webapp/WEB-INF/rails/webpack/helpers/spa_base.tsx
  server/webapp/WEB-INF/rails/webpack/single_page_apps/header_footer_shim.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/site_menu/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/site_menu/spec/index_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/partials/site_header.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/partials/spec/site_header_spec.tsx
  server/webapp/WEB-INF/vm/shared/_header.vm
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/AdminAccessTokensController.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/spring/InitialContextProvider.java
  spark/spark-spa/src/main/resources/freemarker/layouts/component_layout.ftlh
  spark/spark-spa/src/main/resources/freemarker/layouts/single_page_app.ftlh
  spark/spark-spa/src/test/groovy/com/thoughtworks/go/spark/spa/AdminAccessTokensControllerTest.groovy
Labels: SPA, feature-toggle, technical-debt

#6264 Remove rails based environments api
  server/src/main/java/com/thoughtworks/go/server/SparkOrRailsToggle.java
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/webapp/WEB-INF/rails/app/controllers/api_v2/admin/environments_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v2/base_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v2/errors_controller.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v2/agent_summary_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v2/base_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v2/config/environment_config_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v2/config/environment_variable_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v2/config/environments_config_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v2/config/error_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v2/config/pipeline_config_summary_representer.rb
  server/webapp/WEB-INF/rails/config/routes.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v2/admin/environments_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v2/agent_summary_representer_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v2/config/environment_config_representer_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v2/config/environment_variable_representer_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v2/config/environments_config_representer_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v2/config/error_representer_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v2/config/pipeline_config_summary_representer_spec.rb
  server/webapp/WEB-INF/urlrewrite.xml
Labels: apis, technical-debt

#6282 Add Pipeline Page: Make sure users know about validation errors that may be obstructed from their view
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/actions.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/advanced_settings.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/components.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/components.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/non_scm_material_fields.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/scm_material_fields.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/spec/actions_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/spec/advanced_settings_spec.tsx
Labels: improve-trial-experience

#6284 Add validation for rules resources
  config/config-api/src/main/java/com/thoughtworks/go/config/AbstractDirective.java
  config/config-api/src/test/java/com/thoughtworks/go/config/AbstractDirectiveTest.java
Labels: secrets-management

#6285 Modify table component to have draggable rows
  server/webapp/WEB-INF/rails/webpack/views/components/table/index.scss
  server/webapp/WEB-INF/rails/webpack/views/components/table/index.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/components/table/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/table/spec/index_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/global/_mixins.scss
  server/webapp/WEB-INF/rails/webpack/views/global/_variables.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/kitchen_sink.tsx
Labels: ui / ux

#6303 Check if material has secret params before using them.
  server/src/main/java/com/thoughtworks/go/server/service/BuildAssignmentService.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/BuildAssignmentServiceTest.java
Labels: secrets-management

#6306 Update config repo Hg config view to support branch attribute
  server/webapp/WEB-INF/rails/webpack/models/materials/serialization.ts
  server/webapp/WEB-INF/rails/webpack/models/materials/spec/material_test_data.ts
  server/webapp/WEB-INF/rails/webpack/models/materials/spec/types_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/materials/types.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/config_repos/modals.tsx
Labels: config repo

#6304 Add editing pipelines, agents and env vars for environment with special characters in name (#5973)
  server/webapp/WEB-INF/rails/app/views/environments/_show_env.html.erb
Labels: bug-fix, environments, ui / ux

#6309 Use strong_etag for stale check in rails (#6278)
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/internal/environments_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/internal/resources_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/merged_environments_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/packages_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/pluggable_scms_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/plugin_settings_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/repositories_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/templates/authorization_controller.rb
  server/webapp/WEB-INF/rails/app/helpers/api_v1/profiles_controller_actions.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/internal/environments_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/internal/resources_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/merged_environments_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/packages_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/pluggable_scms_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/plugin_settings_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/repositories_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/templates/authorization_controller_spec.rb
Labels: apis, bug-fix

#6310 Fixed check connection issue on create new pipeline flow
  server/webapp/WEB-INF/rails/app/presenters/api_v1/admin/pipelines/materials/hg_material_representer.rb
  server/webapp/WEB-INF/rails/app/views/admin/pipelines/materials/_git_form.html.erb
  server/webapp/WEB-INF/rails/app/views/admin/pipelines/materials/_hg_form.html.erb
  server/webapp/WEB-INF/rails/spec/presenters/api_v1/admin/pipelines/materials/material_representer_spec.rb
Labels: bug-fix

#6312 Use `urlForCommandLine` to build HgCommand
  common/src/test/java/com/thoughtworks/go/config/materials/mercurial/HgMaterialTest.java
  domain/src/main/java/com/thoughtworks/go/config/materials/mercurial/HgMaterial.java
Labels: materials

#6313 Edit pipeline: Send password_changed flag in check connection.
  server/webapp/WEB-INF/rails/app/views/admin/materials/git/_form.html.erb
  server/webapp/WEB-INF/rails/app/views/admin/materials/hg/_form.html.erb
Labels: materials

#6314 Made Git and Hg material and material config PasswordAwareMaterial
  common/src/test/java/com/thoughtworks/go/config/materials/mercurial/HgMaterialTest.java
  config/config-api/src/main/java/com/thoughtworks/go/config/materials/git/GitMaterialConfig.java
  config/config-api/src/main/java/com/thoughtworks/go/config/materials/mercurial/HgMaterialConfig.java
  config/config-api/src/test/java/com/thoughtworks/go/config/materials/git/GitMaterialConfigTest.java
  config/config-api/src/test/java/com/thoughtworks/go/config/materials/mercurial/HgMaterialConfigTest.java
  config/config-api/src/test/java/com/thoughtworks/go/helper/MaterialConfigsMother.java
  domain/src/main/java/com/thoughtworks/go/config/materials/git/GitMaterial.java
  domain/src/main/java/com/thoughtworks/go/config/materials/mercurial/HgMaterial.java
  domain/src/test/java/com/thoughtworks/go/config/materials/git/GitMaterialTest.java
Labels: materials

#6319 Prefix material attributes classes with material name on create pipeline
  server/webapp/WEB-INF/rails/app/presenters/api_v1/admin/pipelines/materials/git_material_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v1/admin/pipelines/materials/hg_material_representer.rb
  server/webapp/WEB-INF/rails/app/views/admin/pipelines/materials/_git_form.html.erb
  server/webapp/WEB-INF/rails/app/views/admin/pipelines/materials/_hg_form.html.erb
Labels: materials

#6320 Fixed broken build on master because of changes done in #6314
  common/src/test/java/com/thoughtworks/go/server/service/MagicalMaterialAndMaterialConfigConversionTest.java
  domain/src/main/java/com/thoughtworks/go/domain/materials/git/GitMaterialInstance.java
  domain/src/main/java/com/thoughtworks/go/domain/materials/mercurial/HgMaterialInstance.java
Labels: materials

#6321 Bundle latest config repo plugins
  tw-go-plugins/build.gradle
Labels: config repo, plugins

#6323 Changes to HgMaterial secrets should consider #6298
  common/src/test/java/com/thoughtworks/go/config/materials/mercurial/HgMaterialTest.java
  common/src/test/java/com/thoughtworks/go/config/materials/mercurial/HgMaterialUpdaterTest.java
  domain/src/main/java/com/thoughtworks/go/config/materials/mercurial/HgMaterial.java
  domain/src/main/java/com/thoughtworks/go/domain/materials/mercurial/HgMaterialUpdater.java
Labels: url-normalization

#6329 Added error on config repo save
  server/webapp/WEB-INF/rails/webpack/views/pages/config_repos/index.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/config_repos/index.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/config_repos/modals.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/config_repos/spec/config_repos_widget_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/config_repos/spec/modals_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/config_repos/spec/test_data.ts
Labels: config repo

#6335 Migrate Plugin settings API to spark
  .gitignore
  api/api-plugin-settings-v1/build.gradle
  api/api-plugin-settings-v1/src/main/java/com/thoughtworks/go/apiv1/pluginsettings/PluginSettingsControllerV1.java
  api/api-plugin-settings-v1/src/main/java/com/thoughtworks/go/apiv1/pluginsettings/representers/PluginSettingsRepresenter.java
  api/api-plugin-settings-v1/src/test/groovy/com/thoughtworks/go/apiv1/pluginsettings/PluginSettingsControllerV1Test.groovy
  api/api-plugin-settings-v1/src/test/groovy/com/thoughtworks/go/apiv1/pluginsettings/representers/PluginSettingsRepresenterTest.groovy
  server/src/main/java/com/thoughtworks/go/server/SparkOrRailsToggle.java
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/webapp/WEB-INF/applicationContext-global.xml
  server/webapp/WEB-INF/urlrewrite.xml
  settings.gradle
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: apis

#6268 Remove rails based users page
  server/src/main/java/com/thoughtworks/go/server/SparkOrRailsToggle.java
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/webapp/WEB-INF/rails/app/controllers/admin/users_controller.rb
  server/webapp/WEB-INF/rails/app/views/admin/users/_user_results_table.html.erb
  server/webapp/WEB-INF/rails/app/views/admin/users/new.html.erb
  server/webapp/WEB-INF/rails/app/views/admin/users/roles.html.erb
  server/webapp/WEB-INF/rails/app/views/admin/users/search.html.erb
  server/webapp/WEB-INF/rails/app/views/admin/users/users.html.erb
  server/webapp/WEB-INF/rails/config/routes.rb
  server/webapp/WEB-INF/rails/spec/controllers/admin/users_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/views/admin/users/_user_results_table_html_spec.rb
  server/webapp/WEB-INF/rails/spec/views/admin/users/new_html_spec.rb
  server/webapp/WEB-INF/rails/spec/views/admin/users/roles_html_spec.rb
  server/webapp/WEB-INF/rails/spec/views/admin/users/search_html_spec.rb
  server/webapp/WEB-INF/rails/spec/views/admin/users/users_html_spec.rb
  server/webapp/WEB-INF/urlrewrite.xml
Labels: technical-debt

#6340 Do not build fedora-28 based docker gocd agent image
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy
Labels: docker-images
