Repository gocd/gocd, pull requests merged in 2019-08, with the labels that each got.

#6680 Validate as you type `name` component. Follows rules for identifiers (e.g., pipeline name, stage name, config repo id, etc)
  server/webapp/WEB-INF/rails/webpack/views/components/forms/common_validating_inputs.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/forms/input_fields.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/forms/live_validating_input.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/forms/spec/common_validating_inputs_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/forms/spec/live_validating_input_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/kitchen_sink.tsx
Labels: Add Pipeline, Pipelines as Code

#6707 Updated stage animation to use gif
  server/webapp/WEB-INF/rails/app/assets/images/building.gif
  server/webapp/WEB-INF/rails/app/assets/images/building.png
  server/webapp/WEB-INF/rails/app/assets/images/building.svg
  server/webapp/WEB-INF/rails/app/assets/images/failing.gif
  server/webapp/WEB-INF/rails/app/assets/images/failing.png
  server/webapp/WEB-INF/rails/app/assets/images/failing.svg
  server/webapp/WEB-INF/rails/app/assets/new_stylesheets/single_page_apps/new_dashboard.scss
  server/webapp/WEB-INF/rails/app/assets/stylesheets/new-theme.scss
  server/webapp/WEB-INF/rails/app/assets/stylesheets/patterns/_status_visualizations.scss
  server/webapp/WEB-INF/rails/app/assets/stylesheets/vm/_jef_override_for_old_ui.scss
  server/webapp/WEB-INF/rails/app/assets/stylesheets/vm/_structure_for_old_ui.scss
Labels: ui / ux

#6708 Add Debian Buster (10) based GoCD Agent docker image
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy
Labels: docker-images, installers

#6678 New pipeline button dropdown
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/webapp/WEB-INF/rails/app/assets/new_stylesheets/single_page_apps/new_dashboard.scss
  server/webapp/WEB-INF/rails/webpack/helpers/spark_routes.ts
  server/webapp/WEB-INF/rails/webpack/models/dashboard/dashboard_groups.js
  server/webapp/WEB-INF/rails/webpack/single_page_apps/new_dashboard.js
  server/webapp/WEB-INF/rails/webpack/views/dashboard/dashboard_groups_widget.js.msx
  server/webapp/WEB-INF/rails/webpack/views/dashboard/dashboard_widget.js.msx
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/NewDashboardController.java
  spark/spark-spa/src/main/resources/freemarker/new_dashboard/index.ftlh
Labels: Add Pipeline

#6717 Fix Elastic Profiles and Cluster Profiles modal sizing (#6715)
  server/webapp/WEB-INF/rails/webpack/views/components/counts/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/ellipsize/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/forms/form.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/forms/input_fields.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/key_value_pair/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/modal/entity_modal.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/modal/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/server_health_summary/server_health_messages_modal.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/site_menu/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/spinner/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/tab/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/table/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/tooltip/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/elastic_profiles/cluster_profile_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/elastic_profiles/cluster_profiles_modals.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/elastic_profiles/elastic_agent_profiles_modals.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/partials/site_header.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/advanced_settings.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/roles/role_modal_body.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/users/add_user_modal.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/users/user_actions_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/users/users_widget.tsx
Labels: bug-fix, elastic-agents

#6681 Rewrite internal command snippets api in spark
  .gitignore
  api/api-internal-command-snippets-v1/build.gradle
  api/api-internal-command-snippets-v1/src/main/java/com/thoughtworks/go/apiv1/internalcommandsnippets/InternalCommandSnippetsControllerV1.java
  api/api-internal-command-snippets-v1/src/main/java/com/thoughtworks/go/apiv1/internalcommandsnippets/representers/CommandSnippetRepresenter.java
  api/api-internal-command-snippets-v1/src/main/java/com/thoughtworks/go/apiv1/internalcommandsnippets/representers/CommandSnippetsRepresenter.java
  api/api-internal-command-snippets-v1/src/test/groovy/com/thoughtworks/go/apiv1/internalcommandsnippets/InternalCommandSnippetsControllerV1Test.groovy
  api/api-internal-command-snippets-v1/src/test/groovy/com/thoughtworks/go/apiv1/internalcommandsnippets/representers/CommandSnippetRepresenterTest.groovy
  api/api-internal-command-snippets-v1/src/test/groovy/com/thoughtworks/go/apiv1/internalcommandsnippets/representers/CommandSnippetsRepresenterTest.groovy
  server/webapp/WEB-INF/applicationContext-global.xml
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/internal/command_snippets_controller.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v1/command_snippet_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v1/command_snippets_representer.rb
  server/webapp/WEB-INF/rails/config/routes.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/internal/command_snippets_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v1/command_snippet_representer_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v1/command_snippets_representer_spec.rb
  server/webapp/WEB-INF/urlrewrite.xml
  settings.gradle
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: apis, technical-debt

#6728 Fix Template Authorization API (#6727)
  server/webapp/WEB-INF/urlrewrite.xml
Labels: apis, bug-fix, templates

#6732 Fix newSPA gradle task
  build.gradle
Labels: bug-fix, technical

#6736 Fixed jasmine test failure introduced in #6734
  server/webapp/WEB-INF/rails/webpack/views/components/buttons/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/wizard/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/wizard/spec/index_spec.tsx
Labels: tests

#6747 Initial skeleton of Agents SPA (#6711)
  server/webapp/WEB-INF/rails/webpack/models/new-agent/agents.ts
  server/webapp/WEB-INF/rails/webpack/models/new-agent/agents_crud.ts
  server/webapp/WEB-INF/rails/webpack/models/new-agent/spec/agents_spec.ts
  server/webapp/WEB-INF/rails/webpack/single_page_apps/new_agent.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new-agents/agents_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new-agents/spec/agents_widget_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agent.tsx
  server/webapp/WEB-INF/urlrewrite.xml
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/NewAgentController.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/spring/SpaControllers.java
Labels: agents, technical-debt, ui / ux

#6755 Redirect from '/admin/elastic_profiles' page to '/admin/elastic_agent_configurations'
  server/webapp/WEB-INF/urlrewrite.xml
Labels: bug-fix

#6698 Pipeline pause message is shown completely on dashboard.(#6640)
  server/webapp/WEB-INF/rails/app/assets/new_stylesheets/single_page_apps/new_dashboard.scss
Labels: Dashboard, bug-fix, ui / ux

#6688 Allow plugins to execute javascript as part of angular plugin view
  server/webapp/WEB-INF/rails/webpack/views/shared/angular_plugin_new.js.msx
Labels: bug-fix, plugins

#6773 Updated ConfigConverter
  server/src/main/java/com/thoughtworks/go/config/ConfigConverter.java
  server/src/test-fast/java/com/thoughtworks/go/config/ConfigConverterTest.java
Labels: pipeline configuration

#6774 Upgrade gradle-license-report from 1.7 to 1.9
  build.gradle
Labels: library-upgrade

#6776 [BUGFIX] Allow Add Pipeline page to render in older browsers
  server/webapp/WEB-INF/rails/webpack/helpers/compat.ts
  server/webapp/WEB-INF/rails/webpack/helpers/css_proxies.ts
  server/webapp/WEB-INF/rails/webpack/helpers/dom.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/task_editor.tsx
Labels: Add Pipeline, bug-fix

#6780 Introduce dropdown component
  server/webapp/WEB-INF/rails/webpack/views/components/dropdown/index.scss
  server/webapp/WEB-INF/rails/webpack/views/components/dropdown/index.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/components/dropdown/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/kitchen_sink.tsx
Labels: component, ui / ux

#6779 Upgrade css-loader to 3.X.X
  server/webapp/WEB-INF/rails/package.json
  server/webapp/WEB-INF/rails/webpack/config/loaders/css-loader.ts
  server/webapp/WEB-INF/rails/webpack/config/loaders/type-declarations-for-css-modules.js
  server/webapp/WEB-INF/rails/webpack/helpers/hack-font.scss
  server/webapp/WEB-INF/rails/webpack/helpers/spa_base.scss
  server/webapp/WEB-INF/rails/yarn.lock
Labels: technical-debt

#6783 Making wizard header and footer fixed.
  server/webapp/WEB-INF/rails/webpack/views/components/wizard/index.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/kitchen_sink.tsx
Labels: bug-fix, component

#6792 Fix plugin icon of elastic agents on the agents SPA (#6771)
  server/webapp/WEB-INF/rails/webpack/views/agents/agent_row_widget.js.msx
Labels: bug-fix, library-upgrade

#6804 Updated the bundled plugin
  tw-go-plugins/build.gradle
Labels: plugins

#6812 Fixed ts lint issues
  server/webapp/WEB-INF/rails/webpack/models/new_agent/agent_comparator.ts
  server/webapp/WEB-INF/rails/webpack/models/new_agent/agents.ts
  server/webapp/WEB-INF/rails/webpack/models/new_agent/agents_crud.ts
  server/webapp/WEB-INF/rails/webpack/models/new_agent/spec/agent_comaparator_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/new_agent/spec/agents_test_data.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agent.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/agent_header_panel.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/agent_status_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/agents_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/environments_and_resources_dropdown_button.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/spec/agent_header_panel_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/spec/agent_status_widget_spec.tsx
Labels: lint-issue

#6813 Fixed agent analytics issue on agents SPA
  server/webapp/WEB-INF/rails/webpack/views/agents/agent_row_widget.js.msx
Labels: bug-fix

#6814 Introduce Pipeline Config SPA Stage Settings Modal
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/spec/stage_configuration_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/stage_configuration.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/pipeline_config_create_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/spec/stages/settings/stage_settings_modal_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/spec/stages/settings/tabs/settings_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages/settings/stage_settings.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages/settings/stage_settings.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages/settings/stage_settings_modal.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages/settings/stage_settings_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages/settings/tabs/settings.tsx
Labels: improve-pipeline-config-ux, pipeline configuration, pipeline-config-spa

#6801 Add CaretDown and Forward Icon
  server/webapp/WEB-INF/rails/webpack/views/components/icons/index.scss
  server/webapp/WEB-INF/rails/webpack/views/components/icons/index.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/components/icons/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/kitchen_sink.tsx
Labels: improve-pipeline-config-ux, ui / ux

#6815 Fix for world-writable files in go-agent and go-server packages.
  installers/linux.gradle
Labels: bug-fix

#6822 Introduce Stage Permissions tab under Stage Settings Popup (#6740)
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/spec/stage_configuration_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/stage_configuration.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/spec/stages/settings/stage_settings_modal_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/spec/stages/settings/tabs/permissions_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/spec/stages/settings/tabs/settings_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages/settings/stage_settings.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages/settings/stage_settings.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages/settings/stage_settings_modal.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages/settings/tabs/permissions.tsx
Labels: improve-pipeline-config-ux, pipeline-config-spa, ui / ux

#6772 Fix compiler warnings for unused files
  server/webapp/WEB-INF/rails/webpack/config/loaders/ts-loader.ts
Labels: technical

#6821 [Pipeline Config SPA] Add Material and Pipeline Config models.
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/materials.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/materials_serialization.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/nameable_set.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/pipeline_config.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/spec/material_test_data.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/spec/materials_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/spec/nameamble_set_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/spec/pipeline_config_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/spec/stage_configuration_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/stage_configuration.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/create_pipeline_page.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/pipeline_config_create_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/spec/pipeline_config_create_widget_spec.tsx
Labels: improve-pipeline-config-ux, pipeline-config-spa

#6826 Reduce GoCD Server and Agent Docker Image size
  buildSrc/src/main/resources/gocd-docker-agent/Dockerfile.agent.ftl
  buildSrc/src/main/resources/gocd-docker-server/Dockerfile.server.ftl
Labels: docker-images, technical

#6825 Add optional documentation link to help text
  server/webapp/WEB-INF/rails/webpack/views/components/forms/input_fields.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/forms/spec/help_text_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/link/index.scss
  server/webapp/WEB-INF/rails/webpack/views/components/link/index.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/components/link/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/link/spec/index_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/kitchen_sink.tsx
Labels: pipeline-config-spa

#6828 Use Link component in footer, add rel attribute
  server/webapp/WEB-INF/rails/webpack/views/pages/partials/site_footer.tsx
Labels: Code Refactoring

#6830 Show Environment Variables On Stage Settings (#6740)
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/environment_variable_config.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/spec/environment_variable_config_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/spec/stage_configuration_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/new_pipeline_configs/stage_configuration.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/environment_variables_editor.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/environment_variables_editor.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/environment_variables_editor.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/spec/environment_variables_editor_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages/settings/stage_settings_modal.tsx
Labels: improve-pipeline-config-ux, pipeline-config-spa, ui / ux

#6833 Updated user information stored in DB
  server/src/main/java/com/thoughtworks/go/server/newsecurity/providers/AbstractPluginAuthenticationProvider.java
  server/src/main/java/com/thoughtworks/go/server/service/UserService.java
  server/src/test-fast/java/com/thoughtworks/go/server/newsecurity/providers/PasswordBasedPluginAuthenticationProviderTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/newsecurity/providers/WebBasedPluginAuthenticationProviderTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/UserServiceTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/UserServiceIntegrationTest.java
Labels: enhancement, users

#6834 New Agents SPA: Adding support for agent analytics
  server/webapp/WEB-INF/rails/webpack/helpers/spark_routes.ts
  server/webapp/WEB-INF/rails/webpack/models/shared/analytics_frame.ts
  server/webapp/WEB-INF/rails/webpack/models/shared/plugin_infos_new/analytics_plugin_capabilities.ts
  server/webapp/WEB-INF/rails/webpack/models/shared/plugin_infos_new/plugin_info.ts
  server/webapp/WEB-INF/rails/webpack/models/shared/plugin_infos_new/spec/plugin_info_spec.ts
  server/webapp/WEB-INF/rails/webpack/models/shared/plugin_infos_new/spec/test_data.ts
  server/webapp/WEB-INF/rails/webpack/models/shared/spec/analytics_frame_spec.ts
  server/webapp/WEB-INF/rails/webpack/views/agents/agent_analytics_widget.js.msx
  server/webapp/WEB-INF/rails/webpack/views/pages/analytics/analytics_iframe_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/analytics/analytics_interaction_manager.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/analytics/analytics_modal.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/analytics/analytics_namespace.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/analytics/index.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/analytics/index.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agent.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/agent_analytics_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/agents_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/index.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/index.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/spec/agent_analytics_widget_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/spec/agents_widget_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/page.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/spec/test_helper.tsx
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/NewAgentController.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/spring/SpaControllers.java
Labels: agents, analytics

#6836 Fix old rails and vm pages UI rendering issue (#6807)
  server/webapp/WEB-INF/rails/webpack/helpers/spa_base.scss
  server/webapp/WEB-INF/rails/webpack/helpers/spa_base.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/single_page_apps/hax-for-css.scss
  server/webapp/WEB-INF/rails/webpack/single_page_apps/hax-for-css.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/single_page_apps/hax-for-css.tsx
  server/webapp/WEB-INF/rails/webpack/views/global/_typography.scss
  server/webapp/WEB-INF/rails/webpack/views/global/common.scss
  spark/spark-spa/src/main/resources/freemarker/layouts/component_layout.ftlh
Labels: bug-fix, ui / ux

#6389 5587 warning in logs in rerunning job
  domain/src/main/java/com/thoughtworks/go/domain/Stage.java
  server/src/main/java/com/thoughtworks/go/server/service/BuildAssignmentService.java
Labels: bug-fix

#6846 Show message when no environments exists
  server/webapp/WEB-INF/rails/webpack/models/new_agent/agents_crud.ts
  server/webapp/WEB-INF/rails/webpack/views/components/spinner/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/agent_header_panel.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/environment_dropdown_button.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/index.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/resources_dropdown_button.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/spec/environment_dropdown_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/spec/resources_dropdown_button_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/spinner.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/new_agents/spinner.scss.d.ts
Labels: agents, technical-debt

#6837 Fixes for linux package installers
  buildSrc/src/main/groovy/com/thoughtworks/go/build/InstallerTypeAgent.groovy
  installers/linux/deb/after-upgrade.sh.erb
  installers/linux/rpm/after-upgrade.sh.erb
  installers/linux/shared/partials/_go-server-config-migration.sh.erb
Labels: bug-fix, installers

#6850 Fix for linux installers
  buildSrc/src/main/groovy/com/thoughtworks/go/build/InstallerTypeServer.groovy
Labels: bug-fix, installers

#6841 Radiobutton component
  server/webapp/WEB-INF/rails/webpack/views/components/forms/forms.scss
  server/webapp/WEB-INF/rails/webpack/views/components/forms/forms.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/components/forms/input_fields.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/kitchen_sink.tsx
Labels: pipeline-config-spa

#6851 Introduce stages widget to render scrollable stages (#6743)
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/pipeline_config_create_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages_widget.tsx
Labels: improve-pipeline-config-ux, pipeline-config-spa, ui / ux

#6852 Show server error on Pipeline Config SPA (#6771)
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/actions.tsx
Labels: bug-fix, library-upgrade

#6853 Honour disabled attribute for iconOnly Icon component
  server/webapp/WEB-INF/rails/webpack/views/components/icons/index.scss
  server/webapp/WEB-INF/rails/webpack/views/components/icons/index.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/components/icons/index.tsx
Labels: bug-fix, component, ui / ux
