Repository gocd/gocd, pull requests merged in 2019-06, with the labels that each got.

#6359 Migrate /go/about server information page to spark
  server/webapp/WEB-INF/rails/webpack/single_page_apps/server_info.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/server_info.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/server_info/index.scss
  server/webapp/WEB-INF/rails/webpack/views/pages/server_info/index.scss.d.ts
  server/webapp/WEB-INF/rails/webpack/views/pages/server_info/server_info_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/server_info/spec/server_info_widget_spec.tsx
  server/webapp/WEB-INF/urlrewrite.xml
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/ServerInfoController.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/spring/SpaControllers.java
  spark/spark-spa/src/test/groovy/com/thoughtworks/go/spark/spa/ServerInfoControllerTest.groovy
Labels: SPA, technical-debt

#6361 Remove rails based about page
  server/webapp/WEB-INF/rails/app/assets/stylesheets/new-css/about.scss
  server/webapp/WEB-INF/rails/app/controllers/about_controller.rb
  server/webapp/WEB-INF/rails/app/helpers/about_helper.rb
  server/webapp/WEB-INF/rails/app/views/about/show.html.erb
  server/webapp/WEB-INF/rails/config/routes.rb
  server/webapp/WEB-INF/rails/spec/helpers/about_helper_spec.rb
  server/webapp/WEB-INF/urlrewrite.xml
Labels: technical-debt

#6368 Upgrade filesize library from v3.5.10 to v4.1.2
  server/webapp/WEB-INF/rails/package.json
  server/webapp/WEB-INF/rails/yarn.lock
Labels: SPA, technical, technical-debt

#6280 Remove old backups page
  server/src/main/java/com/thoughtworks/go/server/SparkOrRailsToggle.java
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/src/test-integration/java/com/thoughtworks/go/server/web/UrlRewriterIntegrationTest.java
  server/webapp/WEB-INF/rails/app/controllers/admin/backup_controller.rb
  server/webapp/WEB-INF/rails/app/views/admin/backup/index.html.erb
  server/webapp/WEB-INF/rails/app/views/layouts/admin.html.erb
  server/webapp/WEB-INF/rails/app/views/shared/_dropdown_admin.html.erb
  server/webapp/WEB-INF/rails/config/routes.rb
  server/webapp/WEB-INF/rails/spec/controllers/admin/backup_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/views/admin/backup/index_html_spec.rb
  server/webapp/WEB-INF/rails/spec/views/layouts/admin_html_spec.rb
  server/webapp/WEB-INF/urlrewrite.xml
Labels: SPA, feature-toggle, technical-debt

#6203 Migrate Pluggable SCM API to spark
  .gitignore
  api/api-base/src/main/java/com/thoughtworks/go/api/representers/JsonReader.java
  api/api-base/src/test/groovy/com/thoughtworks/go/api/representers/JsonReaderTest.groovy
  api/api-scms-v1/build.gradle
  api/api-scms-v1/src/main/java/com/thoughtworks/go/apiv1/scms/SCMControllerV1.java
  api/api-scms-v1/src/main/java/com/thoughtworks/go/apiv1/scms/representers/SCMRepresenter.java
  api/api-scms-v1/src/main/java/com/thoughtworks/go/apiv1/scms/representers/SCMsRepresenter.java
  api/api-scms-v1/src/test/groovy/com/thoughtworks/go/apiv1/scms/SCMControllerV1Test.groovy
  api/api-scms-v1/src/test/groovy/com/thoughtworks/go/apiv1/scms/representers/SCMRepresenterTest.groovy
  api/api-scms-v1/src/test/groovy/com/thoughtworks/go/apiv1/scms/representers/SCMsRepresenterTest.groovy
  server/src/main/java/com/thoughtworks/go/server/SparkOrRailsToggle.java
  server/src/main/java/com/thoughtworks/go/server/service/EntityHashingService.java
  server/src/main/java/com/thoughtworks/go/server/service/GoConfigService.java
  server/src/main/java/com/thoughtworks/go/server/service/materials/PluggableScmService.java
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/src/test-fast/java/com/thoughtworks/go/server/service/materials/PluggableScmServiceTest.java
  server/webapp/WEB-INF/applicationContext-global.xml
  server/webapp/WEB-INF/urlrewrite.xml
  settings.gradle
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: apis

#6345 Fix Weak Etag issue for rails based index APIs (#6278)
  api/api-pipeline-groups-v1/src/test/groovy/com/thoughtworks/go/apiv1/admin/pipelinegroups/PipelineGroupsControllerV1Test.groovy
  config/config-api/src/main/java/com/thoughtworks/go/domain/PipelineGroups.java
  server/src/main/java/com/thoughtworks/go/server/service/EntityHashingService.java
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/internal/command_snippets_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/internal/pipelines_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/packages_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/pluggable_scms_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/repositories_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/security/auth_configs_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v4/admin/plugin_infos_controller.rb
  server/webapp/WEB-INF/rails/app/helpers/api_v1/profiles_controller_actions.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/internal/command_snippets_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/internal/pipelines_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/packages_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/pluggable_scms_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/repositories_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/security/auth_configs_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v4/admin/plugin_infos_controller_spec.rb
Labels: apis, bug-fix

#6375 Ignoring gocd-file-based-secrets-plugin.jar from license check
  server/build.gradle
Labels: plugins, secrets-management

#6374 Secret config api should handle invalid directive type.
  api/api-secret-configs-v1/src/main/java/com/thoughtworks/go/apiv1/secretconfigs/representers/RulesRepresenter.java
  api/api-secret-configs-v1/src/test/groovy/com/thoughtworks/go/apiv1/secretconfigs/representers/RulesRepresenterTest.groovy
  config/config-api/src/main/java/com/thoughtworks/go/config/rules/DirectiveType.java
Labels: secrets-management

#6379 Fixing check connection error when secret config is refered
  common/src/test/java/com/thoughtworks/go/config/materials/mercurial/HgMaterialTest.java
  domain/src/main/java/com/thoughtworks/go/config/materials/git/GitMaterial.java
  domain/src/main/java/com/thoughtworks/go/config/materials/mercurial/HgMaterial.java
  domain/src/main/java/com/thoughtworks/go/config/materials/perforce/P4Material.java
  domain/src/test/java/com/thoughtworks/go/config/materials/git/GitMaterialTest.java
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/internal/material_test_controller.rb
Labels: bug-fix, secrets-management

#6299 Introduce ConsoleLogRequestProcessor
  domain/src/main/java/com/thoughtworks/go/domain/JobIdentifier.java
  server/src/main/java/com/thoughtworks/go/server/service/plugins/processor/console/ConsoleLogAppendRequest.java
  server/src/main/java/com/thoughtworks/go/server/service/plugins/processor/console/ConsoleLogRequestProcessor.java
  server/src/main/java/com/thoughtworks/go/server/service/plugins/processor/console/MessageHandlerForConsoleLogRequestProcessor.java
  server/src/main/java/com/thoughtworks/go/server/service/plugins/processor/console/v1/ConsoleLogAppendRequest1_0.java
  server/src/main/java/com/thoughtworks/go/server/service/plugins/processor/console/v1/MessageHandlerForConsoleLogRequestProcessorImpl1_0.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/plugins/processor/console/v1/ConsoleLogRequestProcessorTest.java
Labels: elastic-agents, enhancement

#6371 Add toggle for password show or hide
  server/webapp/WEB-INF/rails/app/assets/javascripts/util.js
  server/webapp/WEB-INF/rails/app/assets/stylesheets/new-theme.scss
  server/webapp/WEB-INF/rails/app/views/admin/materials/shared/_password.html.erb
  server/webapp/WEB-INF/rails/app/views/admin/materials/shared/_plain_password.html.erb
Labels: secrets-management, ui / ux

#6398 Updating the file based secret plugin version
  tw-go-plugins/build.gradle
Labels: plugins, secrets-management

#6414 Revert "Turn off secret config SPA by default"
  server/src/main/resources/available.toggles
Labels: SPA, secrets-management

#6353 Run GoCD Docker Containers as non root user
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/BuildDockerImageTask.groovy
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/DistroBehavior.groovy
  buildSrc/src/main/resources/gocd-docker-agent/Dockerfile.agent.ftl
  buildSrc/src/main/resources/gocd-docker-agent/docker-entrypoint.sh
  buildSrc/src/main/resources/gocd-docker-server/Dockerfile.server.ftl
  buildSrc/src/main/resources/gocd-docker-server/docker-entrypoint.sh
  buildSrc/src/main/resources/gocd-docker-server/git-clone-config
  buildSrc/src/main/resources/gocd-docker-server/install-gocd-plugins
Labels: docker-images

#6549 Display toggle for secure environment variables
  server/webapp/WEB-INF/rails/app/assets/javascripts/environment_variable_edit.js
  server/webapp/WEB-INF/rails/app/views/admin/shared/_name_value.html.erb
  server/webapp/WEB-INF/rails/app/views/environments/_edit_environment_variables.html.erb
  server/webapp/WEB-INF/rails/app/views/environments/_environment_variable_entry.html.erb
Labels: ui / ux

#6550 Fixing the server image name
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/BuildDockerImageTask.groovy
Labels: docker-images

#6553 Build GoCD agent alpine 3.10 based docker image
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy
Labels: docker-images

#6554 Install procps on all docker distributions
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy
  installers/linux.gradle
Labels: docker-images

#6555 Updated rules validation on MDU
  server/src/main/java/com/thoughtworks/go/server/exceptions/RulesViolationException.java
  server/src/main/java/com/thoughtworks/go/server/service/RulesService.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/RulesServiceTest.java
Labels: secrets-management

#6547 Update footer banner message when server is in maintenance mode.
  base/src/main/java/com/thoughtworks/go/util/DateUtils.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/filters/ModeAwareFilter.java
  server/src/main/java/com/thoughtworks/go/server/service/MaintenanceModeService.java
  server/src/main/resources/server_in_maintenance_mode.html
  server/src/test-fast/java/com/thoughtworks/go/server/newsecurity/filters/ModeAwareFilterTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/MaintenanceModeServiceTest.java
  server/webapp/WEB-INF/rails/app/helpers/application_helper.rb
  server/webapp/WEB-INF/rails/app/views/shared/_body_data_attrs.html.erb
  server/webapp/WEB-INF/rails/spec/helpers/application_helper_spec.rb
  server/webapp/WEB-INF/rails/webpack/helpers/spa_base.tsx
  server/webapp/WEB-INF/rails/webpack/single_page_apps/header_footer_shim.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/partials/site_footer.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/partials/spec/site_footer_spec.tsx
  server/webapp/WEB-INF/vm/shared/_header.vm
  spark/spark-spa/src/main/resources/freemarker/layouts/component_layout.ftlh
  spark/spark-spa/src/main/resources/freemarker/layouts/single_page_app.ftlh
Labels: maintenance-mode, ui / ux

#6564 Updated rules validation on MDU
  config/config-api/src/main/java/com/thoughtworks/go/config/materials/MaterialConfigs.java
  config/config-api/src/test/java/com/thoughtworks/go/config/materials/MaterialConfigsTest.java
  server/src/main/java/com/thoughtworks/go/server/exceptions/RulesViolationException.java
  server/src/main/java/com/thoughtworks/go/server/service/GoConfigService.java
  server/src/main/java/com/thoughtworks/go/server/service/RulesService.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/GoConfigServiceTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/RulesServiceTest.java
Labels: secrets-management

#6582 #6328 - Cancel the scheduled elastic agent jobs on GoCD upgrade from version prior to 19.3.0.
  server/src/main/java/com/thoughtworks/go/server/service/ElasticAgentPluginService.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/ElasticAgentPluginServiceTest.java
Labels: bug-fix, elastic-agent-multi-cluster-support, elastic-agents
