Repository gocd/gocd, pull requests merged in 2019-12, with the labels that each got.

#7337 Fixes for Job Run History Page
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agent-job-run-history/agent_job_state_transitions_modal.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agent-job-run-history/index.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agent-job-run-history/index.scss.d.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agent-job-run-history/spec/agent_job_state_transitions_modal_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agent_job_run_history.tsx
Labels: SPA, agents

#7344 Updated table to receive the current sort order from sort handler
  server/src/main/webapp/WEB-INF/rails/webpack/models/agents/agent_comparator.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/agents/agents_vm.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/agents/spec/agent_vm_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/table/index.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/table/index.scss.d.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/table/index.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/table/spec/index_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agent-job-run-history/agent_job_run_history_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/kitchen_sink.tsx
Labels: SPA, agents

#7350 Show environments link for pipeline group and template admins (#7349)
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/site_menu/index.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/site_menu/spec/index_spec.tsx
Labels: SPA, environments, granular-auth

#7353 Fix read only templates page on pipeline config page (#7352)
  server/src/main/webapp/WEB-INF/rails/app/controllers/config_view/config_view_controller.rb
  server/src/main/webapp/WEB-INF/rails/app/controllers/config_view/templates_controller.rb
  server/src/main/webapp/WEB-INF/rails/app/helpers/config_view/config_view_helper.rb
  server/src/main/webapp/WEB-INF/rails/app/views/config_view/templates/_job_view.html.erb
  server/src/main/webapp/WEB-INF/rails/app/views/config_view/templates/_plugin_view.html.erb
  server/src/main/webapp/WEB-INF/rails/app/views/config_view/templates/show.html.erb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/config_view/templates_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/views/config_view/templates/_job_view_html_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/views/config_view/templates/show_html_spec.rb
Labels: bug-fix, pipeline configuration, templates

#7354 Do not include config repo pipelines to extract template from pipeline (#7318)
  server/src/main/webapp/WEB-INF/rails/webpack/models/internal_pipeline_structure/pipeline_structure.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/internal_pipeline_structure/spec/pipeline_structure_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates/modals.tsx
Labels: SPA, bug-fix, templates

#7361 Added RBAC doc link to default policy info message
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/roles/policy_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/roles/spec/policy_widget_spec.tsx
Labels: SPA, granular-auth

#7320 Environment config SPA fixes
  api/api-internal-environments-v1/src/main/java/com/thoughtworks/go/apiv1/internalenvironments/InternalEnvironmentsControllerV1.java
  api/api-internal-environments-v1/src/test/groovy/com/thoughtworks/go/apiv1/internalenvironments/InternalEnvironmentsControllerV1Test.groovy
  config/config-api/src/main/java/com/thoughtworks/go/config/exceptions/EntityType.java
  server/src/main/java/com/thoughtworks/go/server/service/AgentService.java
  server/src/main/webapp/WEB-INF/rails/webpack/helpers/spark_routes.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/dashboard/dashboard_groups.js
  server/src/main/webapp/WEB-INF/rails/webpack/models/environment_variables/spec/types_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/environment_variables/types.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/environment_environment_variables.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/environments.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/environments_apis.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/spec/environment_environment_variables_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/spec/environments_apis_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/spec/environments_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/environment_variables/environment_variable_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/environment_variables/index.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/environment_variables/index.scss.d.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/environment_variables/spec/index_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/config_repo_result.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/edit_agents_modal.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/edit_pipelines_modal.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/environment_body_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/environment_header_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/environments_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/models/agents_view_model.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/edit_agents_modal_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/edit_pipelines_modal_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/environment_body_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/environment_header_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/environments_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/models/agents_view_model_spec.ts
  server/src/test-fast/java/com/thoughtworks/go/server/service/AgentServiceTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/AgentServiceIntegrationTest.java
Labels: environments

#7218 Fixes for the new server config SPA -
  api/api-server-site-urls-config-v1/src/main/java/com/thoughtworks/go/apiv1/serversiteurlsconfig/ServerSiteUrlsConfigControllerV1.java
  api/api-server-site-urls-config-v1/src/test/groovy/com/thoughtworks/go/apiv1/serversiteurlsconfig/ServerSiteUrlsConfigControllerV1Test.groovy
  server/src/main/webapp/WEB-INF/rails/webpack/models/server-configuration/server_configuration.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/server-configuration/server_configuration_vm.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/server-configuration/spec/server_configuration_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/server-configuration/spec/server_configuration_vm_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/artifacts_management_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/confirm_modal.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/index.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/index.scss.d.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/job_timeout_configuration_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/mail_server_management_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/server_configuration_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/server_management_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/spec/artifact_management_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/spec/confirm_modal_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/spec/job_timeout_configuration_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/spec/mail_server_management_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/spec/server_configuration_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/spec/server_management_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server_configuration.tsx
Labels: server configuration, server-configuration-rewrite, ui / ux

#7364 Using PATCH method instead of PUT for updating agent associations on environment SPA
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/environments_apis.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/spec/environments_apis_spec.ts
Labels: bug-fix, environments, ui / ux

#7362 Templates SPA Fixes (#7356)(#7357)
  server/src/main/webapp/WEB-INF/rails/webpack/single_page_apps/admin_templates.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates/admin_templates_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates/modals.tsx
Labels: SPA, bug-fix, templates

#7375 Use latest read only templates view
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/view_and_edit_associated_template.js
  server/src/main/webapp/WEB-INF/rails/app/controllers/config_view/config_view_controller.rb
  server/src/main/webapp/WEB-INF/rails/app/controllers/config_view/templates_controller.rb
  server/src/main/webapp/WEB-INF/rails/app/helpers/config_view/config_view_helper.rb
  server/src/main/webapp/WEB-INF/rails/app/views/admin/stages/index.html.erb
  server/src/main/webapp/WEB-INF/rails/app/views/config_view/templates/_job_view.html.erb
  server/src/main/webapp/WEB-INF/rails/app/views/config_view/templates/_plugin_view.html.erb
  server/src/main/webapp/WEB-INF/rails/app/views/config_view/templates/show.html.erb
  server/src/main/webapp/WEB-INF/rails/config/routes.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/config_view/templates_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/view_and_edit_associated_template_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/views/config_view/templates/_job_view_html_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/views/config_view/templates/show_html_spec.rb
Labels: SPA, enhancement, technical-debt, templates

#7368 Remove Server State API
  base/src/main/java/com/thoughtworks/go/util/SystemEnvironment.java
  server/src/main/webapp/WEB-INF/rails/app/controllers/api/server_state_controller.rb
  server/src/main/webapp/WEB-INF/rails/config/routes.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/api/server_state_controller_spec.rb
Labels: apis

#7379 Update get stage instance API to remove id
  .gitignore
  api/api-stage-operations-v2/build.gradle
  api/api-stage-operations-v2/src/main/java/com/thoughtworks/go/apiv2/stageoperations/StageOperationsControllerV2.java
  api/api-stage-operations-v2/src/main/java/com/thoughtworks/go/apiv2/stageoperations/representers/JobHistoryItemRepresenter.java
  api/api-stage-operations-v2/src/main/java/com/thoughtworks/go/apiv2/stageoperations/representers/JobInstanceRepresenter.java
  api/api-stage-operations-v2/src/main/java/com/thoughtworks/go/apiv2/stageoperations/representers/JobStateTransitionRepresenter.java
  api/api-stage-operations-v2/src/main/java/com/thoughtworks/go/apiv2/stageoperations/representers/StageInstanceRepresenter.java
  api/api-stage-operations-v2/src/main/java/com/thoughtworks/go/apiv2/stageoperations/representers/StageInstancesRepresenter.java
  api/api-stage-operations-v2/src/main/java/com/thoughtworks/go/apiv2/stageoperations/representers/StageRepresenter.java
  api/api-stage-operations-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageoperations/StageOperationsControllerV2Test.groovy
  api/api-stage-operations-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageoperations/representers/JobHistoryItemRepresenterTest.groovy
  api/api-stage-operations-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageoperations/representers/JobInstanceRepresenterTest.groovy
  api/api-stage-operations-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageoperations/representers/JobStateTransitionRepresenterTest.groovy
  api/api-stage-operations-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageoperations/representers/StageInstanceRepresenterTest.groovy
  api/api-stage-operations-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageoperations/representers/StageInstancesRepresenterTest.groovy
  api/api-stage-operations-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageoperations/representers/StageRepresenterTest.groovy
  server/src/main/resources/applicationContext-global.xml
  settings.gradle
Labels: apis

#7219 Introduce versioned pipeline status API
  api/api-pipeline-operations-v1/src/main/java/com/thoughtworks/go/apiv1/pipelineoperations/PipelineOperationsControllerV1.java
  api/api-pipeline-operations-v1/src/main/java/com/thoughtworks/go/apiv1/pipelineoperations/representers/PipelineStatusModelRepresenter.java
  api/api-pipeline-operations-v1/src/test/groovy/com/thoughtworks/go/apiv1/pipelineoperations/PipelineOperationsControllerV1Test.groovy
  api/api-pipeline-operations-v1/src/test/groovy/com/thoughtworks/go/apiv1/pipelineoperations/representers/PipelineStatusModelRepresenterTest.groovy
  server/src/main/webapp/WEB-INF/urlrewrite.xml
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: apis

#7279 Bump up stage history api
  api/api-stage-operations-v2/src/main/java/com/thoughtworks/go/apiv2/stageoperations/StageOperationsControllerV2.java
  api/api-stage-operations-v2/src/main/java/com/thoughtworks/go/apiv2/stageoperations/representers/JobHistoryItemRepresenter.java
  api/api-stage-operations-v2/src/main/java/com/thoughtworks/go/apiv2/stageoperations/representers/StageInstanceRepresenter.java
  api/api-stage-operations-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageoperations/StageOperationsControllerV2Test.groovy
  api/api-stage-operations-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageoperations/representers/JobHistoryItemRepresenterTest.groovy
  api/api-stage-operations-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageoperations/representers/StageInstanceRepresenterTest.groovy
  api/api-stage-operations-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageoperations/representers/StageInstancesRepresenterTest.groovy
Labels: apis

#7271 Update Policy to support config repo
  api/api-config-repos-v2/src/main/java/com/thoughtworks/go/apiv2/configrepos/ConfigReposControllerV2.java
  api/api-config-repos-v2/src/main/java/com/thoughtworks/go/apiv2/configrepos/ConfigReposInternalControllerV2.java
  api/api-config-repos-v2/src/main/java/com/thoughtworks/go/apiv2/configrepos/representers/ConfigRepoWithResultListRepresenter.java
  api/api-config-repos-v2/src/main/java/com/thoughtworks/go/apiv2/configrepos/representers/ConfigRepoWithResultRepresenter.java
  api/api-config-repos-v2/src/test/groovy/com/thoughtworks/go/apiv2/configrepos/ConfigReposControllerV2Test.groovy
  api/api-config-repos-v2/src/test/groovy/com/thoughtworks/go/apiv2/configrepos/ConfigReposInternalControllerV2Test.groovy
  api/api-config-repos-v2/src/test/groovy/com/thoughtworks/go/apiv2/configrepos/representers/ConfigRepoWithResultListRepresenterTest.groovy
  api/api-config-repos-v2/src/test/groovy/com/thoughtworks/go/apiv2/configrepos/representers/ConfigRepoWithResultRepresenterTest.groovy
  config/config-api/src/main/java/com/thoughtworks/go/config/Role.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/SupportedEntity.java
  config/config-api/src/test/java/com/thoughtworks/go/config/policy/SupportedEntityTest.java
  server/src/main/java/com/thoughtworks/go/config/update/ConfigRepoCommand.java
  server/src/main/java/com/thoughtworks/go/config/update/DeleteConfigRepoCommand.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/filterchains/AuthorizeFilterChain.java
  server/src/main/webapp/WEB-INF/rails/webpack/models/config_repos/serialization.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/config_repos/spec/config_repos_crud_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/config_repos/spec/types_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/config_repos/types.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/site_menu/index.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/site_menu/spec/index_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/config_repos_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/spec/config_repo_attribute_helper_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/spec/config_repos_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/spec/test_data.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/roles.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/roles/policy_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/roles/spec/policy_widget_spec.tsx
  server/src/test-fast/java/com/thoughtworks/go/config/update/CreateConfigRepoCommandTest.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/DeleteConfigRepoCommandTest.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/UpdateConfigRepoCommandTest.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/ConfigReposController.java
  spark/spark-spa/src/test/groovy/com/thoughtworks/go/spark/spa/ConfigReposControllerTest.groovy
Labels: config repo, granular-auth

#7384 Move config-revisions API to internal endpoint (#7340)
  server/src/main/webapp/WEB-INF/rails/config/routes.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/api/configuration_controller_spec.rb
Labels: apis, technical

#7382 Disable deleting environment defined in config repo through Environment API.
  server/src/main/java/com/thoughtworks/go/config/update/DeleteEnvironmentCommand.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/DeleteEnvironmentCommandTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/EnvironmentConfigServiceIntegrationTest.java
Labels: apis, bug-fix, environments

#7389 Moving comment api for pipeline instance to spark
  api/api-pipeline-instance-v1/src/main/java/com/thoughtworks/go/apiv1/pipelineinstance/PipelineInstanceControllerV1.java
  api/api-pipeline-instance-v1/src/test/groovy/com/thoughtworks/go/apiv1/pipelineinstance/PipelineInstanceControllerV1Test.groovy
  config/config-api/src/main/java/com/thoughtworks/go/config/exceptions/NotImplementedException.java
  server/src/main/java/com/thoughtworks/go/server/service/PipelineHistoryService.java
  server/src/main/webapp/WEB-INF/rails/app/controllers/pipelines_controller.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/pipelines_controller_spec.rb
  server/src/main/webapp/WEB-INF/urlrewrite.xml
  server/src/test-fast/java/com/thoughtworks/go/server/service/PipelineHistoryServiceTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/PipelineHistoryServiceIntegrationTest.java
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: apis, pipeline-history

#7403 Show/Enable pipeline settings icons for config repository pipelines (#7401)
  server/src/main/java/com/thoughtworks/go/server/service/GoConfigService.java
  server/src/main/java/com/thoughtworks/go/server/service/ValueStreamMapService.java
  server/src/main/webapp/WEB-INF/rails/app/controllers/stages_controller.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/stages_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines/admin_pipelines_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines/admin_pipelines_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates/admin_templates_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/config_repo_result.tsx
  server/src/main/webapp/WEB-INF/vm/shared/_job_details_breadcrumbs.vm
  server/src/test-fast/java/com/thoughtworks/go/server/service/ValueStreamMapServiceTest.java
Labels: enhancement, pipeline configuration

#7413 Reduced the width of tooltip wrapper as the same was cut off
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/roles.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/roles/index.scss
Labels: SPA, bug-fix, granular-auth

#7414 Show edit pipeline gear icon for config repo pipelines (#7401)
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/page_header.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/spec/page_header_spec.tsx
  server/src/main/webapp/WEB-INF/vm/pipeline/_pipeline_history_list_jstemplate.vm
Labels: enhancement, pipeline-history

#7412 Package Material should generate valid material name when one not specified (#7345)
  domain/src/main/java/com/thoughtworks/go/config/materials/PackageMaterial.java
  domain/src/test/java/com/thoughtworks/go/config/materials/PackageMaterialTest.java
  server/src/main/webapp/WEB-INF/rails/spec/views/shared/_build_cause_html_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/views/shared/_build_cause_popup_html_spec.rb
Labels: bug-fix, config repo, materials, package materials

#7421 Fix for 7377
  plugin-infra/go-plugin-config-repo/src/main/java/com/thoughtworks/go/plugin/configrepo/contract/tasks/CRAbstractFetchTask.java
Labels: bug-fix

#7418 Environment SPA improvements
  server/src/main/webapp/WEB-INF/rails/webpack/models/environment_variables/spec/test_data.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/environment_variables/spec/types_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/environment_variables/types.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/environment_environment_variables.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/environments.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/spec/environment_environment_variables_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/spec/environments_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/spec/test_data.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/origin/spec/origin_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/origin/spec/test_data.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/environment_variables/environment_variable_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/environment_variables/index.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/environment_variables/index.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/config_repo_link.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/create_env_modal.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/edit_environment_variables_modal.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/edit_pipelines.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/edit_pipelines.scss.d.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/edit_pipelines_modal.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/environment_body_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/config_repo_link_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/create_env_modal_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/edit_pipelines_modal_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/shared/environment_variables_with_origin_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/shared/specs/environment_variables_with_origin_widget_spec.tsx
Labels: SPA, environments, ui / ux

#7425 Allow users to cancel stage on maintainance mode SPA (#7415)
  server/src/main/webapp/WEB-INF/rails/webpack/helpers/spark_routes.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/maintenance_mode.tsx
Labels: apis, bug-fix, maintenance-mode

#7427 Fixing no error on cancel task for tasks
  server/src/main/java/com/thoughtworks/go/config/update/PipelineConfigErrorCopier.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/UpdatePipelineConfigCommandTest.java
Labels: bug-fix

#7426 Allow users to rename pipeline group (#7402)
  api/api-pipeline-groups-v1/src/main/java/com/thoughtworks/go/apiv1/admin/pipelinegroups/PipelineGroupsControllerV1.java
  api/api-pipeline-groups-v1/src/test/groovy/com/thoughtworks/go/apiv1/admin/pipelinegroups/PipelineGroupsControllerV1Test.groovy
  server/src/main/java/com/thoughtworks/go/config/update/UpdatePipelineConfigsAuthCommand.java
  server/src/main/java/com/thoughtworks/go/config/update/UpdatePipelineConfigsCommand.java
  server/src/main/java/com/thoughtworks/go/server/service/PipelineConfigsService.java
  server/src/test-fast/java/com/thoughtworks/go/config/update/UpdatePipelineConfigsCommandTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/PipelineConfigsServiceTest.java
Labels: bug-fix, pipeline configuration

#7428 Use job state transition icon on agent job details page
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agent-job-run-history/agent_job_run_history_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agent-job-run-history/icon-state-transition.svg
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agent-job-run-history/index.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agent-job-run-history/index.scss.d.ts
Labels: SPA, agents

#7430 Remove command repository cache reload API
  server/src/main/webapp/WEB-INF/rails/app/controllers/api/commands_controller.rb
  server/src/main/webapp/WEB-INF/rails/config/routes.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/api/commands_controller_spec.rb
Labels: apis, technical

#7435 Revert "Support for edit action on Policy"
  api/api-base/src/test/groovy/com/thoughtworks/go/api/spring/ApiAuthenticationHelperTest.java
  api/api-config-repos-v2/src/main/java/com/thoughtworks/go/apiv2/configrepos/ConfigReposInternalControllerV2.java
  api/api-config-repos-v2/src/main/java/com/thoughtworks/go/apiv2/configrepos/representers/ConfigRepoWithResultListRepresenter.java
  api/api-config-repos-v2/src/main/java/com/thoughtworks/go/apiv2/configrepos/representers/ConfigRepoWithResultRepresenter.java
  api/api-config-repos-v2/src/test/groovy/com/thoughtworks/go/apiv2/configrepos/ConfigReposControllerV2Test.groovy
  api/api-config-repos-v2/src/test/groovy/com/thoughtworks/go/apiv2/configrepos/ConfigReposInternalControllerV2Test.groovy
  api/api-config-repos-v2/src/test/groovy/com/thoughtworks/go/apiv2/configrepos/representers/ConfigRepoWithResultListRepresenterTest.groovy
  api/api-config-repos-v2/src/test/groovy/com/thoughtworks/go/apiv2/configrepos/representers/ConfigRepoWithResultRepresenterTest.groovy
  api/api-internal-environments-v1/src/main/java/com/thoughtworks/go/apiv1/internalenvironments/InternalEnvironmentsControllerV1.java
  api/api-internal-environments-v1/src/main/java/com/thoughtworks/go/apiv1/internalenvironments/representers/MergedEnvironmentRepresenter.java
  api/api-internal-environments-v1/src/main/java/com/thoughtworks/go/apiv1/internalenvironments/representers/MergedEnvironmentsRepresenter.java
  api/api-internal-environments-v1/src/test/groovy/com/thoughtworks/go/apiv1/internalenvironments/InternalEnvironmentsControllerV1Test.groovy
  api/api-internal-environments-v1/src/test/groovy/com/thoughtworks/go/apiv1/internalenvironments/representers/MergedEnvironmentRepresenterTest.groovy
  config/config-api/src/main/java/com/thoughtworks/go/config/Role.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/AbstractDirective.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/SupportedAction.java
  config/config-api/src/test/java/com/thoughtworks/go/config/RoleConfigTest.java
  config/config-api/src/test/java/com/thoughtworks/go/config/policy/AllowTest.java
  config/config-api/src/test/java/com/thoughtworks/go/config/policy/DenyTest.java
  server/src/main/webapp/WEB-INF/rails/webpack/models/config_repos/serialization.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/config_repos/spec/config_repos_crud_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/config_repos/spec/types_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/config_repos/types.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/environments.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/spec/test_data.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/config_repos_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/spec/config_repo_attribute_helper_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/spec/config_repos_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/spec/test_data.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/create_env_modal.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/environment_body_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/environments_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/edit_pipelines_modal_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/environment_body_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/environments_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/models/pipelines_view_model_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/roles/policy_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/roles/spec/policy_widget_spec.tsx
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/SparkController.java
Labels: config repo

#7434 Fix for broken trigger with options
  api/api-dashboard-v3/src/test/groovy/com/thoughtworks/go/apiv3/dashboard/representers/PipelineInstanceRepresenterTest.groovy
  api/api-dashboard-v4/src/test/groovy/com/thoughtworks/go/apiv4/dashboard/representers/PipelineInstanceRepresenterTest.groovy
  api/api-pipeline-instance-v1/src/test/groovy/com/thoughtworks/go/apiv1/pipelineinstance/PipelineInstanceControllerV1Test.groovy
  server/src/main/webapp/WEB-INF/urlrewrite.xml
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: bug-fix

#7440 Render VSM for read only users
  server/src/main/java/com/thoughtworks/go/server/service/ValueStreamMapService.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/ValueStreamMapServiceTest.java
Labels: bug-fix, vsm

#7433 Add feature toggle to enable pipeline group config listing API
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/src/main/webapp/WEB-INF/rails/app/controllers/api/pipeline_groups_controller.rb
  server/src/main/webapp/WEB-INF/rails/app/controllers/application_controller.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/api/pipeline_groups_controller_spec.rb
Labels: apis, technical

#7444 Upgrade types/mithril to v2.0.2
  server/src/main/webapp/WEB-INF/rails/package.json
  server/src/main/webapp/WEB-INF/rails/webpack/jsx/mithril-component.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/buttons/index.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/buttons/sample/index.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/forms/input_fields.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/modal/entity_modal.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/modal/modal_manager.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/table/spec/index_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agents/agent_status_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agents/environment_dropdown_button.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agents/resources_dropdown_button.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/cluster_profile_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/kitchen_sink.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/maintenance_mode/running_jobs_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new_plugins/plugin_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pac/spec/builder_form_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_configs/stages/on_create/tasks_list_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipelines/template_editor.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipelines_as_code.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/roles/modals.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/roles/policy_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/secret_configs/rules_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/users/user_actions_widget.tsx
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: library-upgrade, technical, technical-debt

#7436 Show msg if anchor element is not found
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/anchor/anchor.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/anchor/spec/anchor_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines/admin_pipelines_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines/admin_pipelines_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates/admin_templates_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates/specs/admin_templates_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates/specs/modals_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates/specs/task_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/config_repos_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/spec/config_repos_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/environments_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/environments_widget_spec.tsx
Labels: SPA, bug-fix

#7448 Updating url for the pipeline comment
  api/api-pipeline-instance-v1/src/main/java/com/thoughtworks/go/apiv1/pipelineinstance/PipelineInstanceControllerV1.java
  api/api-pipeline-instance-v1/src/test/groovy/com/thoughtworks/go/apiv1/pipelineinstance/PipelineInstanceControllerV1Test.groovy
  server/src/main/webapp/WEB-INF/rails/webpack/helpers/spark_routes.ts
  server/src/main/webapp/WEB-INF/urlrewrite.xml
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: apis

#7450 Fix Pipeline History SPA comment rendering issue
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/comment_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/spec/comment_widget_spec.tsx
Labels: SPA, bug-fix, pipeline-history

#7454 Allow normal users to access materials check connection internal api endpoint (#7451)
  server/src/main/webapp/WEB-INF/rails/app/controllers/api_v1/admin/internal/material_test_controller.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/internal/material_test_controller_spec.rb
Labels: apis, bug-fix, config repo, granular-auth, materials

#7455 Attempt fixing failing windows jasmine build
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/spec/comment_widget_spec.tsx
Labels: technical

#7456 Config repository SPA fixes
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/config_repos_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/modals.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/spec/config_repos_widget_spec.tsx
Labels: SPA, bug-fix, config repo

#7466 Bug fix: Pipeline history pagination offset should be honoured by poller
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/spec/pipeline_activity_page_spec.tsx
Labels: SPA, bug-fix, pipeline-history

#7469 Config repo SPA link now visible to pipeline grp admin and template admin
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/site_menu/index.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/site_menu/spec/index_spec.tsx
Labels: bug-fix

#7471 Fix failing rpsecs
  server/src/main/webapp/WEB-INF/rails/spec/controllers/admin/jobs_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/admin/materials/dependency_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/admin/materials/material_controller_examples.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/admin/materials/pluggable_scm_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/admin/materials_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/admin/pipelines_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/admin/stages_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/admin/tasks/fetch_external_task_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/admin/tasks/fetch_task_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/admin/tasks/pluggable_task_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/admin/tasks/task_controller_examples.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/admin/tasks_controller_spec.rb
Labels: technical, technical-debt

#7475 Fixed tooltip positioning issue
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/tooltip/index.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/tooltip/index.scss.d.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/tooltip/index.tsx
Labels: bug-fix, component

#7477 Package Material should generate valid material name when one not specified (#7345)
  config/config-api/src/main/java/com/thoughtworks/go/config/materials/PackageMaterialConfig.java
  config/config-api/src/test/java/com/thoughtworks/go/config/materials/PackageMaterialConfigTest.java
  config/config-server/src/test/java/com/thoughtworks/go/config/MagicalGoConfigXmlLoaderTest.java
Labels: bug-fix

#7480 Attempt: to render the error response based on the Accept header
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/RoutesHelper.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/PipelineActivityController.java
  spark/spark-spa/src/test/groovy/com/thoughtworks/go/spark/spa/PipelineActivityControllerTest.groovy
Labels: bug-fix

#7485 Send appropriate environment variable json while editing environment on environments SPA (#7481)
  server/src/main/webapp/WEB-INF/rails/webpack/models/environment_variables/spec/types_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/environment_variables/types.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/spec/environments_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/environment_variables/environment_variable_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/environment_variables/index.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/edit_environment_variables_modal.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/spec/edit_environment_variables_modal_spec.tsx
Labels: SPA, bug-fix, environments

#7493 Time in milliseconds should not be rendered as string but as number
  api/api-pipeline-instance-v1/src/test/groovy/com/thoughtworks/go/apiv1/pipelineinstance/representers/JobHistoryItemRepresenterTest.groovy
  api/api-pipeline-instance-v1/src/test/groovy/com/thoughtworks/go/apiv1/pipelineinstance/representers/MaterialRevisionRepresenterTest.groovy
  api/api-pipeline-instance-v1/src/test/groovy/com/thoughtworks/go/apiv1/pipelineinstance/representers/ModificationRepresenterTest.groovy
  spark/spark-base/src/main/java/com/thoughtworks/go/api/base/JsonOutputWriter.java
Labels: bug-fix

#7494 Improve the position of send test mail button
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/server-configuration/index.scss
Labels: ui / ux

#7497 Fixed tests for time in milliseconds representation
  api/api-base/src/test/groovy/com/thoughtworks/go/api/representers/JsonOutputWriterTest.groovy
  api/api-compare-v1/src/main/java/com/thoughtworks/go/apiv1/compare/representers/JobHistoryItemRepresenter.java
  api/api-compare-v1/src/test/groovy/com/thoughtworks/go/apiv1/compare/representers/JobHistoryItemRepresenterTest.groovy
  api/api-job-instance-v1/src/test/groovy/com/thoughtworks/go/apiv1/jobinstance/representers/JobInstanceRepresenterTest.groovy
  api/api-job-instance-v1/src/test/groovy/com/thoughtworks/go/apiv1/jobinstance/representers/JobStateTransitionRepresenterTest.groovy
Labels: bug-fix

#7498 Bug fix: Handle failing stage status animation
  server/src/main/webapp/WEB-INF/rails/webpack/models/pipeline_activity/spec/test_data.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/index.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/index.scss.d.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/pipeline_run_info_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/spec/pipeline_run_info_widget_spec.tsx
Labels: SPA, bug-fix, pipeline-history

#7491 Move notification filter API to spark
  .gitignore
  api/api-notification-filter-v2/build.gradle
  api/api-notification-filter-v2/src/main/java/com/thoughtworks/go/apiv2/notificationfilter/NotificationFilterControllerV2.java
  api/api-notification-filter-v2/src/main/java/com/thoughtworks/go/apiv2/notificationfilter/representers/NotificationFilterRepresenter.java
  api/api-notification-filter-v2/src/main/java/com/thoughtworks/go/apiv2/notificationfilter/representers/NotificationFiltersRepresenter.java
  api/api-notification-filter-v2/src/test/groovy/com/thoughtworks/go/apiv2/notificationfilter/NotificationFilterControllerV2Test.groovy
  api/api-notification-filter-v2/src/test/groovy/com/thoughtworks/go/apiv2/notificationfilter/representers/NotificationFilterRepresenterTest.groovy
  api/api-notification-filter-v2/src/test/groovy/com/thoughtworks/go/apiv2/notificationfilter/representers/NotificationFiltersRepresenterTest.groovy
  common/src/main/java/com/thoughtworks/go/domain/User.java
  common/src/test/java/com/thoughtworks/go/domain/UserTest.java
  config/config-api/src/main/java/com/thoughtworks/go/config/exceptions/EntityType.java
  domain/src/main/java/com/thoughtworks/go/domain/StageEvent.java
  server/src/main/java/com/thoughtworks/go/server/service/EntityHashingService.java
  server/src/main/java/com/thoughtworks/go/server/service/UserService.java
  server/src/main/resources/applicationContext-global.xml
  server/src/main/webapp/WEB-INF/urlrewrite.xml
  server/src/test-fast/java/com/thoughtworks/go/server/service/UserServiceTest.java
  settings.gradle
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: apis

#7499 Updating java dependencies
  agent/build.gradle
  build.gradle
  config/config-api/build.gradle
  config/config-server/build.gradle
  server/build.gradle
  server/src/main/webapp/WEB-INF/rails/Gemfile.lock
Labels: technical-debt

#7502 Attempt to fix agent fatJar verification
  agent/build.gradle
Labels: build-script

#7504 Reverting urlrewrite to 3.2.0
  build.gradle
Labels: technical-debt

#7510 Removed fanin APIs
  server/src/main/java/com/thoughtworks/go/server/service/dd/reporting/ReportingDependencyFanInNode.java
  server/src/main/java/com/thoughtworks/go/server/service/dd/reporting/ReportingFanInGraph.java
  server/src/main/java/com/thoughtworks/go/server/service/dd/reporting/ReportingFanInGraphContext.java
  server/src/main/java/com/thoughtworks/go/server/service/dd/reporting/ReportingFanInNode.java
  server/src/main/java/com/thoughtworks/go/server/service/dd/reporting/ReportingFanInNodeFactory.java
  server/src/main/java/com/thoughtworks/go/server/service/dd/reporting/ReportingFaninScmMaterial.java
  server/src/main/java/com/thoughtworks/go/server/service/dd/reporting/ReportingRootFanInNode.java
  server/src/main/webapp/WEB-INF/rails/app/controllers/api/fanin_trace_controller.rb
  server/src/main/webapp/WEB-INF/rails/config/routes.rb
  server/src/main/webapp/WEB-INF/rails/lib/java_imports.rb
Labels: apis

#7520 Build script fix: Updating version of asm jar for server module in verify task
  server/build.gradle
Labels: build-script

#7441 Config repository API v3
  .gitignore
  api/api-config-repos-v3/build.gradle
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/ConfigRepoWithResult.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/ConfigReposControllerV3.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/ConfigReposInternalControllerV3.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/ConfigRepoConfigRepresenterV3.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/ConfigRepoWithResultListRepresenter.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/ConfigRepoWithResultRepresenter.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/ConfigReposConfigRepresenterV3.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/EnvironmentConfigRepresenter.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/GitMaterialRepresenter.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/HgMaterialRepresenter.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/MaterialRepresenter.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/MaterialsRepresenter.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/P4MaterialRepresenter.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/PartialConfigParseResultRepresenter.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/PartialConfigRepresenter.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/PipelineConfigRepresenter.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/PipelineGroupRepresenter.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/SvnMaterialRepresenter.java
  api/api-config-repos-v3/src/main/java/com/thoughtworks/go/apiv3/configrepos/representers/TfsMaterialRepresenter.java
  api/api-config-repos-v3/src/test/groovy/com/thoughtworks/go/apiv3/configrepos/ConfigReposControllerV3Test.groovy
  api/api-config-repos-v3/src/test/groovy/com/thoughtworks/go/apiv3/configrepos/ConfigReposInternalControllerV3Test.groovy
  server/src/main/resources/applicationContext-global.xml
  server/src/main/webapp/WEB-INF/rails/webpack/helpers/spark_routes.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/config_repos/config_repos_crud.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/config_repos/defined_structures.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/config_repos/spec/config_repos_crud_spec.ts
  server/src/main/webapp/WEB-INF/urlrewrite.xml
  settings.gradle
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: apis, config repo
