Repository gocd/gocd, pull requests merged in 2019-07, with the labels that each got.

#6587 Fixes issue # 6585
  server/webapp/WEB-INF/rails/app/views/admin/pipelines/_basic_new_pipeline_fields.html.erb
Labels: secrets-management

#6590 Remove agent upgrade related debug logs (#5212) (#4469)
  agent/src/main/java/com/thoughtworks/go/agent/service/AgentUpgradeService.java
  server/src/main/java/com/thoughtworks/go/server/controller/AgentRegistrationController.java
Labels: technical-debt

#6576 Fix installer upgrade on ubuntu and centos
  installers/linux/deb/before-upgrade.sh.erb
  installers/linux/rpm/after-upgrade.sh.erb
  installers/linux/shared/partials/_go-agent_post_install_message.sh.erb
  installers/linux/shared/partials/_go-server_post_install_message.sh.erb
  installers/windows.gradle
  installers/windows/go-agent-custom-page.nsi
  installers/windows/go-agent.nsi
  installers/windows/go-base.nsi
Labels: bug-fix, installers

#6603 Fix upgradeApi gradle task to appropriately generate component scan package name
  build.gradle
Labels: technical

#6606 Do not hardcode schemaVersion in XML Loader specs
  config/config-server/src/test/java/com/thoughtworks/go/config/MagicalGoConfigXmlLoaderTest.java
Labels: technical

#6608 Remove unused rails based Agents related representer and spec
  server/webapp/WEB-INF/rails/app/presenters/api_v4/build_details_representer.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v4/build_details_representer_spec.rb
Labels: agents, apis, technical

#6614 Upgrade essential node packages
  server/webapp/WEB-INF/rails/package.json
  server/webapp/WEB-INF/rails/spec/webpack/helpers/fixup-stacktraces.js
  server/webapp/WEB-INF/rails/webpack/helpers/form_helper.js.msx
  server/webapp/WEB-INF/rails/webpack/models/maintenance_mode/material.ts
  server/webapp/WEB-INF/rails/webpack/models/users/user_filters.ts
  server/webapp/WEB-INF/rails/webpack/models/users/users.ts
  server/webapp/WEB-INF/rails/webpack/views/components/ellipsize/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/forms/autocomplete.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/modal/entity_modal.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/elastic_profiles/cluster_profile_widget.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/kitchen_sink.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/pipelines/spec/pipeline_info_editor_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/roles/modals.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/users.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/users/spec/user_actions_widget_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/users/spec/users_widget_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/shared/schmodal.js.msx
  server/webapp/WEB-INF/rails/yarn.lock
Labels: technical-debt

#6609 Remove rails based plugin infos API v4
  server/webapp/WEB-INF/rails/app/controllers/api_v4/admin/plugin_infos_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v4/base_controller.rb
  server/webapp/WEB-INF/rails/app/controllers/api_v4/errors_controller.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/base_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/analytics_capabilities_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/analytics_plugin_info_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/artifact_capabilities_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/artifact_plugin_info_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/authorization_capabilities_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/authorization_plugin_info_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/base_plugin_info_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/config_repo_plugin_info_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/elastic_plugin_capabilities_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/elastic_plugin_info_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/notification_plugin_info_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/package_repository_plugin_info_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/pluggable_instance_settings_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/pluggable_task_plugin_info_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/plugin_configuration_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/plugin_info_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/plugin_infos_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/plugin_view_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/plugin/scm_plugin_info_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v4/shared/error_representer.rb
  server/webapp/WEB-INF/rails/config/routes.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v4/admin/plugin_infos_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v4/plugin/elastic_plugin_capabilities_representer_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v4/plugin/pluggable_instance_settings_representer_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v4/plugin/plugin_info_representer_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v4/plugin/plugin_infos_representer_spec.rb
Labels: apis, technical

#6617 Fix broken build due to removal of plugin info api v4
  server/webapp/WEB-INF/rails/app/assets/javascripts/pipeline_export.js
  server/webapp/WEB-INF/rails/webpack/helpers/spark_routes.ts
  server/webapp/WEB-INF/rails/webpack/models/shared/plugin_infos.js
  server/webapp/WEB-INF/rails/webpack/models/shared/plugin_infos_new/plugin_info_crud.ts
Labels: technical, technical-debt

#6612 Internal API endpoint to support PaC add pipeline page
  .gitignore
  api/api-pipelines-as-code-internal-v1/build.gradle
  api/api-pipelines-as-code-internal-v1/src/main/java/com/thoughtworks/go/apiv1/pipelinesascodeinternal/PipelinesAsCodeInternalControllerV1.java
  api/api-pipelines-as-code-internal-v1/src/test/groovy/com/thoughtworks/go/apiv1/pipelinesascodeinternal/PipelinesAsCodeInternalControllerV1Test.groovy
  server/src/main/java/com/thoughtworks/go/server/service/GoConfigService.java
  server/src/main/java/com/thoughtworks/go/server/service/PipelineConfigService.java
  server/webapp/WEB-INF/applicationContext-global.xml
  server/webapp/WEB-INF/urlrewrite.xml
  settings.gradle
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/SparkController.java
Labels: Add Pipeline, Pipelines as Code

#6610 Remove rails based unversioned stages history API
  server/webapp/WEB-INF/rails/app/controllers/api/stages_controller.rb
  server/webapp/WEB-INF/rails/config/routes.rb
  server/webapp/WEB-INF/rails/spec/controllers/api/stages_controller_spec.rb
Labels: apis, technical

#6616 Send create agent request for jobs requiring elastic agent when they are rescheduled by GoCD (#6615)
  server/src/main/java/com/thoughtworks/go/server/messaging/JobStatusListener.java
  server/src/main/java/com/thoughtworks/go/server/messaging/elasticagents/CreateAgentMessage.java
  server/src/main/java/com/thoughtworks/go/server/service/ElasticAgentPluginService.java
  server/src/test-fast/java/com/thoughtworks/go/server/messaging/JobStatusListenerTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/messaging/JobStatusListenerIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/ScheduleServiceIntegrationTest.java
  server/src/test-shared/java/com/thoughtworks/go/server/dao/DatabaseAccessHelper.java
Labels: bug-fix, console-log, elastic-agents, scheduling

#6623 Fix RPM installer upgrades on docker (#6622)
  installers/linux.gradle
  installers/linux/rpm/after-upgrade.sh.erb
  installers/linux/rpm/post-tran.sh.erb
Labels: bug-fix, installers

#6625 Draggable spec failure fix on Safari
  server/webapp/WEB-INF/rails/webpack/views/components/table/spec/index_spec.tsx
Labels: ui / ux

#6624 Update datasharing url to be v3
  base/src/main/java/com/thoughtworks/go/util/SystemEnvironment.java
Labels: data-sharing

#6629 Fix Internal Server Error on Packages API due to missing md5ForEntity method (#6628)
  server/src/main/java/com/thoughtworks/go/server/service/EntityHashingService.java
Labels: apis, bug-fix, package materials

#6633 Updating ldap authentication plugin version
  tw-go-plugins/build.gradle
Labels: plugins

#6632 Fix Internal Server Error on Package Repositories API due to missing md5ForEntity method (#6630)
  server/src/main/java/com/thoughtworks/go/server/service/EntityHashingService.java
Labels: apis, bug-fix, package materials

#6635 Fix Internal Server Error on internal command snippet API due to missing md5ForEntity method(#6634)
  server/src/main/java/com/thoughtworks/go/server/service/EntityHashingService.java
  server/src/main/java/com/thoughtworks/go/server/service/lookups/CommandSnippets.java
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/internal/command_snippets_controller.rb
Labels: apis, bug-fix

#6636 Use concrete Packages class instead of List<PackageDefinition> for md5ForEntity
  config/config-api/src/main/java/com/thoughtworks/go/domain/packagerepository/Packages.java
  server/src/main/java/com/thoughtworks/go/server/service/EntityHashingService.java
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/packages_controller.rb
Labels: technical

#6639 Update README.md.ftl
  buildSrc/src/main/resources/gocd-docker-agent/README.md.ftl
Labels: docker-images

#6558 Remove rails based plugin settings API
  server/src/main/java/com/thoughtworks/go/server/SparkOrRailsToggle.java
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/plugin_settings_controller.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v1/config/plugin_settings_representer.rb
  server/webapp/WEB-INF/rails/config/routes.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/plugin_settings_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v1/config/plugin_settings_representer_spec.rb
  server/webapp/WEB-INF/urlrewrite.xml
Labels: apis, technical-debt

#6559 Remove rails based auth config API
  server/src/main/java/com/thoughtworks/go/server/SparkOrRailsToggle.java
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/security/auth_configs_controller.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v1/security/auth_config_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v1/security/auth_configs_representer.rb
  server/webapp/WEB-INF/rails/config/routes.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/security/auth_configs_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v1/security/auth_config_representer_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v1/security/auth_configs_representer_spec.rb
  server/webapp/WEB-INF/urlrewrite.xml
Labels: apis, technical-debt

#6644 Remove rails based pluggable scms API
  server/src/main/java/com/thoughtworks/go/server/SparkOrRailsToggle.java
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/webapp/WEB-INF/rails/app/controllers/api_v1/admin/pluggable_scms_controller.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v1/scms/pluggable_scm_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v1/scms/pluggable_scm_summary_representer.rb
  server/webapp/WEB-INF/rails/app/presenters/api_v1/scms/pluggable_scms_representer.rb
  server/webapp/WEB-INF/rails/config/routes.rb
  server/webapp/WEB-INF/rails/spec/controllers/api_v1/admin/pluggable_scms_controller_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v1/scms/pluggable_scm_representer_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v1/scms/pluggable_scm_summary_representer_spec.rb
  server/webapp/WEB-INF/rails/spec/presenters/api_v1/scms/pluggable_scms_representer_spec.rb
  server/webapp/WEB-INF/urlrewrite.xml
Labels: apis, technical-debt

#6653 Remove pipeline config API v6
  .gitignore
  api/api-pipeline-config-v6/build.gradle
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/PipelineConfigControllerV6.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/ParamRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/PipelineConfigRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/TimerRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/DependencyMaterialRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/FilterRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/GitMaterialRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/HgMaterialRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/MaterialRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/PackageMaterialRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/PerforceMaterialRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/PluggableScmMaterialRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/ScmMaterialRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/SvnMaterialRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/TfsMaterialRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/trackingtool/ExternalTrackingToolRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/trackingtool/MingleTrackingToolRepresenter.java
  api/api-pipeline-config-v6/src/main/java/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/trackingtool/TrackingToolRepresenter.java
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/PipelineConfigControllerV6Test.groovy
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/ParamRepresenterTest.groovy
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/PipelineConfigRepresenterTest.groovy
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/TimerRepresenterTest.groovy
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/DependencyMaterialRepresenterTest.groovy
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/FilterRepresenterTest.groovy
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/GitMaterialRepresenterTest.groovy
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/HgMaterialRepresenterTest.groovy
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/MaterialRepresenterTrait.groovy
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/PackageMaterialRepresenterTest.groovy
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/PerforceMaterialRepresenterTest.groovy
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/PluggableScmMaterialRepresenterTest.groovy
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/SvnMaterialRepresenterTest.groovy
  api/api-pipeline-config-v6/src/test/groovy/com/thoughtworks/go/apiv6/admin/pipelineconfig/representers/materials/TfsMaterialRepresenterTest.groovy
  settings.gradle
Labels: apis, pipeline configuration

#6654 Removed config-repos version v1
  .gitignore
  api/api-config-repos-v1/build.gradle
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/ConfigRepoWithResult.java
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/ConfigReposControllerV1.java
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/ConfigReposInternalControllerV1.java
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/representers/ConfigRepoConfigRepresenterV1.java
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/representers/ConfigRepoWithResultListRepresenter.java
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/representers/ConfigRepoWithResultRepresenter.java
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/representers/ConfigReposConfigRepresenterV1.java
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/representers/GitMaterialRepresenter.java
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/representers/HgMaterialRepresenter.java
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/representers/MaterialRepresenter.java
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/representers/P4MaterialRepresenter.java
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/representers/PartialConfigParseResultRepresenter.java
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/representers/SvnMaterialRepresenter.java
  api/api-config-repos-v1/src/main/java/com/thoughtworks/go/apiv1/configrepos/representers/TfsMaterialRepresenter.java
  api/api-config-repos-v1/src/test/groovy/com/thoughtworks/go/apiv1/configrepos/ConfigReposControllerV1Test.groovy
  api/api-config-repos-v1/src/test/groovy/com/thoughtworks/go/apiv1/configrepos/ConfigReposInternalControllerV1Test.groovy
  api/api-config-repos-v1/src/test/groovy/com/thoughtworks/go/apiv1/configrepos/representers/ConfigRepoConfigRepresenterV1Test.groovy
  api/api-config-repos-v1/src/test/groovy/com/thoughtworks/go/apiv1/configrepos/representers/ConfigRepoWithResultListRepresenterTest.groovy
  api/api-config-repos-v1/src/test/groovy/com/thoughtworks/go/apiv1/configrepos/representers/ConfigRepoWithResultRepresenterTest.groovy
  api/api-config-repos-v1/src/test/groovy/com/thoughtworks/go/apiv1/configrepos/representers/ConfigReposConfigRepresenterV1Test.groovy
  api/api-config-repos-v1/src/test/groovy/com/thoughtworks/go/apiv1/configrepos/representers/GitMaterialRepresenterTest.groovy
  api/api-config-repos-v1/src/test/groovy/com/thoughtworks/go/apiv1/configrepos/representers/HgMaterialRepresenterTest.groovy
  api/api-config-repos-v1/src/test/groovy/com/thoughtworks/go/apiv1/configrepos/representers/MaterialRepresenterTest.groovy
  api/api-config-repos-v1/src/test/groovy/com/thoughtworks/go/apiv1/configrepos/representers/P4MaterialRepresenterTest.groovy
  api/api-config-repos-v1/src/test/groovy/com/thoughtworks/go/apiv1/configrepos/representers/PartialConfigParseResultRepresenterTest.groovy
  api/api-config-repos-v1/src/test/groovy/com/thoughtworks/go/apiv1/configrepos/representers/SvnMaterialRepresenterTest.groovy
  api/api-config-repos-v1/src/test/groovy/com/thoughtworks/go/apiv1/configrepos/representers/TfsMaterialRepresenterTest.groovy
  server/webapp/WEB-INF/applicationContext-global.xml
  settings.gradle
Labels: apis, config repo, technical

#6662 Remove show_secret_config_spa toggle as the secret management feature is released
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/java/com/thoughtworks/go/server/web/GoVelocityView.java
  server/src/main/resources/available.toggles
  server/webapp/WEB-INF/rails/app/helpers/application_helper.rb
  server/webapp/WEB-INF/rails/app/views/shared/_body_data_attrs.html.erb
  server/webapp/WEB-INF/rails/webpack/helpers/spa_base.tsx
  server/webapp/WEB-INF/rails/webpack/single_page_apps/header_footer_shim.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/site_menu/index.tsx
  server/webapp/WEB-INF/rails/webpack/views/components/site_menu/spec/index_spec.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/partials/site_header.tsx
  server/webapp/WEB-INF/rails/webpack/views/pages/partials/spec/site_header_spec.tsx
  server/webapp/WEB-INF/vm/shared/_header.vm
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/SecretConfigsController.java
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/spring/InitialContextProvider.java
  spark/spark-spa/src/main/resources/freemarker/layouts/component_layout.ftlh
  spark/spark-spa/src/main/resources/freemarker/layouts/single_page_app.ftlh
Labels: feature-toggle, secrets-management, technical, technical-debt

#6671 Fix Linux Installers (#6666)
  buildSrc/src/main/groovy/com/thoughtworks/go/build/InstallerTypeAgent.groovy
  buildSrc/src/main/groovy/com/thoughtworks/go/build/InstallerTypeServer.groovy
  installers/linux.gradle
Labels: bug-fix, installers

#6676 Use {server,agent} work dir specified from older installations (#6674)
  installers/linux/shared/partials/_go-agent-config-migration.sh.erb
  installers/linux/shared/partials/_go-server-config-migration.sh.erb
Labels: bug-fix, installers

#6689 Remove sysvinit-tools dependency from RPM distro
  installers/linux.gradle
Labels: bug-fix, installers

#6692 Fix README-running-multiple-agents.md to create /var/lib/go-agent/run instead of /var/run/go-agent
  installers/go-agent/release/README-running-multiple-agents.md
Labels: installers

#6699 Allow exiting GoCD docker containers by sending SIGINT ctrl-c signal
  buildSrc/src/main/resources/gocd-docker-agent/docker-entrypoint.sh
  buildSrc/src/main/resources/gocd-docker-server/docker-entrypoint.sh
Labels: bug-fix, docker-images
