Repository gocd/gocd, pull requests merged in 2020-12, with the labels that each got.

#8806 Bump up spring and spring security to latest
  build.gradle
Labels: library-upgrade

#8848 Upgrade libraries #000
  agent-bootstrapper/build.gradle
  agent-launcher/build.gradle
  agent/build.gradle
  api/api-version-infos-v1/src/main/java/com/thoughtworks/go/apiv1/versioninfos/representers/VersionInfoRepresenter.java
  dependencies.gradle
  server-launcher/build.gradle
  server/build.gradle
  server/src/main/webapp/WEB-INF/rails/Gemfile
  server/src/main/webapp/WEB-INF/rails/Gemfile.lock
  server/src/test-integration/java/com/thoughtworks/go/server/web/UrlRewriterIntegrationTest.java
Labels: library-upgrade

#8860 Reverting junit5 upgrade #000
  agent/build.gradle
  dependencies.gradle
  server/build.gradle
Labels: library-upgrade

#8857 SCMMaterial changes #000
  api/api-server-maintenance-mode-v1/src/test/groovy/com/thoughtworks/go/apiv1/servermaintenancemode/representers/MaintenanceModeInfoRepresenterTest.groovy
  common/src/test/java/com/thoughtworks/go/config/materials/perforce/P4MaterialTest.java
  common/src/test/java/com/thoughtworks/go/config/materials/tfs/TfsMaterialTest.java
  common/src/test/java/com/thoughtworks/go/domain/materials/DummyMaterial.java
  common/src/test/java/com/thoughtworks/go/domain/materials/svn/SvnMaterialTest.java
  common/src/test/java/com/thoughtworks/go/server/service/MagicalMaterialAndMaterialConfigConversionTest.java
  domain/src/main/java/com/thoughtworks/go/config/materials/Materials.java
  domain/src/main/java/com/thoughtworks/go/config/materials/ScmMaterial.java
  domain/src/main/java/com/thoughtworks/go/config/materials/git/GitMaterial.java
  domain/src/main/java/com/thoughtworks/go/config/materials/mercurial/HgMaterial.java
  domain/src/main/java/com/thoughtworks/go/config/materials/perforce/P4Material.java
  domain/src/main/java/com/thoughtworks/go/config/materials/svn/SvnMaterial.java
  domain/src/main/java/com/thoughtworks/go/config/materials/tfs/TfsMaterial.java
  domain/src/main/java/com/thoughtworks/go/domain/materials/TestingMaterial.java
  domain/src/main/java/com/thoughtworks/go/domain/materials/tfs/TfsMaterialInstance.java
  domain/src/test/java/com/thoughtworks/go/helper/MaterialsMother.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/MaterialServiceTest.java
  server/src/test-integration/java/com/thoughtworks/go/domain/materials/tfs/TfsMaterialPersistenceTest.java
Labels: materials

#8895 Prevent gson serialization from serializing cipher-related instances
  common/src/main/java/com/thoughtworks/go/remote/Serialization.java
  common/src/test/java/com/thoughtworks/go/remote/SerializationTest.java
  config/config-api/src/test/java/com/thoughtworks/go/helper/ReversingEncrypter.java
  server/src/test-fast/java/com/thoughtworks/go/config/plugin/ConfigRepoPluginTest.java
Labels: agents, security

#8900 Improve UX - add search functionality on page
  server/src/main/webapp/WEB-INF/rails/webpack/models/internal_pipeline_structure/pipeline_structure.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/internal_pipeline_structure/spec/pipeline_structure_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/environments.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/new-environments/spec/environments_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pluggable_scms.tsx
Labels: ui / ux

#8898 Agent server comms over json
  .gitignore
  agent/src/main/java/com/thoughtworks/go/agent/AgentHTTPClientController.java
  agent/src/main/java/com/thoughtworks/go/agent/GoHttpClientHttpInvokerRequestExecutor.java
  agent/src/main/java/com/thoughtworks/go/agent/RemotingClient.java
  agent/src/main/java/com/thoughtworks/go/agent/ResponseHelpers.java
  agent/src/main/resources/applicationContext.xml
  agent/src/test/java/com/thoughtworks/go/agent/AgentHTTPClientControllerTest.java
  api/api-internal-agent-v1/build.gradle
  api/api-internal-agent-v1/src/main/java/com/thoughtworks/go/apiv1/internalagent/InternalAgentControllerV1.java
  api/api-internal-agent-v1/src/main/java/com/thoughtworks/go/apiv1/internalagent/representers/AgentInstructionRepresenter.java
  api/api-internal-agent-v1/src/main/java/com/thoughtworks/go/apiv1/internalagent/representers/GetCookieRequestRepresenter.java
  api/api-internal-agent-v1/src/main/java/com/thoughtworks/go/apiv1/internalagent/representers/GetWorkRequestRepresenter.java
  api/api-internal-agent-v1/src/main/java/com/thoughtworks/go/apiv1/internalagent/representers/IsIgnoredRequestRepresenter.java
  api/api-internal-agent-v1/src/main/java/com/thoughtworks/go/apiv1/internalagent/representers/PingRequestRepresenter.java
  api/api-internal-agent-v1/src/main/java/com/thoughtworks/go/apiv1/internalagent/representers/ReportCompleteStatusRequestRepresenter.java
  api/api-internal-agent-v1/src/main/java/com/thoughtworks/go/apiv1/internalagent/representers/ReportCurrentStatusRequestRepresenter.java
  api/api-internal-agent-v1/src/main/java/com/thoughtworks/go/apiv1/internalagent/representers/WorkRepresenter.java
  api/api-internal-agent-v1/src/test/groovy/com/thoughtworks/go/apiv1/templateauthorization/InternalAgentControllerV1Test.groovy
  api/api-internal-agent-v1/src/test/groovy/com/thoughtworks/go/apiv1/templateauthorization/representers/AgentInstanceRepresenterTest.groovy
  api/api-internal-agent-v1/src/test/groovy/com/thoughtworks/go/apiv1/templateauthorization/representers/GetCookieRequestRepresenterTest.groovy
  api/api-internal-agent-v1/src/test/groovy/com/thoughtworks/go/apiv1/templateauthorization/representers/GetWorkRequestRepresenterTest.groovy
  api/api-internal-agent-v1/src/test/groovy/com/thoughtworks/go/apiv1/templateauthorization/representers/IsIgnoredRequestRepresenterTest.groovy
  api/api-internal-agent-v1/src/test/groovy/com/thoughtworks/go/apiv1/templateauthorization/representers/PingRequestRepresenterTest.groovy
  api/api-internal-agent-v1/src/test/groovy/com/thoughtworks/go/apiv1/templateauthorization/representers/ReportCompleteStatusRequestRepresenterTest.groovy
  api/api-internal-agent-v1/src/test/groovy/com/thoughtworks/go/apiv1/templateauthorization/representers/ReportCurrentStatusRequestRepresenterTest.groovy
  api/api-internal-agent-v1/src/test/groovy/com/thoughtworks/go/apiv1/templateauthorization/representers/WorkRepresenterTest.groovy
  common/src/main/java/com/thoughtworks/go/remote/Serialization.java
  common/src/main/java/com/thoughtworks/go/remote/request/GetCookieRequest.java
  common/src/main/java/com/thoughtworks/go/util/URLService.java
  common/src/test/java/com/thoughtworks/go/agent/testhelpers/FakeBuildRepositoryRemote.java
  common/src/test/java/com/thoughtworks/go/remote/SerializationTest.java
  common/src/test/java/com/thoughtworks/go/remote/work/BuildRepositoryRemoteStub.java
  domain/src/main/java/com/thoughtworks/go/config/materials/AbstractMaterial.java
  domain/src/main/java/com/thoughtworks/go/config/materials/Materials.java
  domain/src/main/java/com/thoughtworks/go/config/materials/dependency/DependencyMaterial.java
  domain/src/main/java/com/thoughtworks/go/domain/materials/Material.java
  domain/src/test/java/com/thoughtworks/go/helper/ModificationsMother.java
  server/src/main/java/com/thoughtworks/go/domain/cctray/CcTrayBreakersCalculator.java
  server/src/main/java/com/thoughtworks/go/server/dao/PipelineSqlMapDao.java
  server/src/main/java/com/thoughtworks/go/server/messaging/BuildRepositoryMessageProducer.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/filterchains/AuthorizeFilterChain.java
  server/src/main/java/com/thoughtworks/go/server/presentation/models/MaterialRevisionsJsonBuilder.java
  server/src/main/resources/applicationContext-global.xml
  server/src/main/webapp/WEB-INF/rails/app/helpers/materials_helper.rb
  server/src/main/webapp/WEB-INF/urlrewrite.xml
  settings.gradle
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: agents, apis

#8909 File adapter for de-serialization of File object
  common/src/main/java/com/thoughtworks/go/remote/Serialization.java
Labels: agents

#8919 Remove logging nd syncing of the des cipher
  server/src/main/java/com/thoughtworks/go/addon/businesscontinuity/ConfigFileType.java
  server/src/main/java/com/thoughtworks/go/addon/businesscontinuity/primary/controller/PrimaryStatusProviderController.java
  server/src/main/java/com/thoughtworks/go/addon/businesscontinuity/primary/service/GoFilesStatusProvider.java
  server/src/main/java/com/thoughtworks/go/addon/businesscontinuity/standby/service/PrimaryServerEndPoint.java
  server/src/test-fast/java/com/thoughtworks/go/addon/businesscontinuity/primary/controller/PrimaryStatusProviderControllerTest.java
  server/src/test-fast/java/com/thoughtworks/go/addon/businesscontinuity/primary/service/GoFilesStatusProviderTest.java
  server/src/test-fast/java/com/thoughtworks/go/addon/businesscontinuity/standby/controller/DashBoardControllerTest.java
  server/src/test-fast/java/com/thoughtworks/go/addon/businesscontinuity/standby/service/StandbyFileSyncServiceTest.java
Labels: technical-debt
