Repository gocd/gocd, pull requests merged in 2020-01, with the labels that each got.

#7508 Migrate Material test API from rails to spark
  .gitignore
  api/api-internal-material-test-v1/build.gradle
  api/api-internal-material-test-v1/src/main/java/com/thoughtworks/go/apiv1/internalmaterialtest/InternalMaterialTestControllerV1.java
  api/api-internal-material-test-v1/src/test/groovy/com/thoughtworks/go/apiv1/internalmaterialtest/InternalMaterialTestControllerV1Test.groovy
  common/src/test/java/com/thoughtworks/go/domain/materials/AbstractMaterialTest.java
  domain/src/main/java/com/thoughtworks/go/config/materials/AbstractMaterial.java
  domain/src/main/java/com/thoughtworks/go/domain/materials/Material.java
  server/src/main/resources/applicationContext-global.xml
  server/src/main/webapp/WEB-INF/rails/webpack/helpers/spark_routes.ts
  server/src/main/webapp/WEB-INF/urlrewrite.xml
  settings.gradle
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: apis

#7530 Add a toggle to fall back to rails based test connection API
  server/src/main/java/com/thoughtworks/go/server/SparkOrRailsToggle.java
  server/src/main/java/com/thoughtworks/go/server/service/support/toggle/Toggles.java
  server/src/main/resources/available.toggles
  server/src/main/webapp/WEB-INF/rails/webpack/helpers/spark_routes.ts
  server/src/main/webapp/WEB-INF/urlrewrite.xml
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: apis

#7531 Fix for incorrect icon for cancelled jobs
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/new-theme.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/patterns/_status_visualizations.scss
Labels: SPA, ui / ux

#7446 Updated Stage History API v2 to support cursor-based pagination
  api/api-pipeline-instance-v1/src/test/groovy/com/thoughtworks/go/apiv1/pipelineinstance/PipelineInstanceControllerV1Test.groovy
  api/api-stage-instance-v2/src/main/java/com/thoughtworks/go/apiv2/stageinstance/StageInstanceControllerV2.java
  api/api-stage-instance-v2/src/main/java/com/thoughtworks/go/apiv2/stageinstance/representers/StageInstancesRepresenter.java
  api/api-stage-instance-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageinstance/StageInstanceControllerV2Test.groovy
  api/api-stage-instance-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageinstance/representers/StageInstancesRepresenterTest.groovy
  server/src/main/java/com/thoughtworks/go/server/dao/StageDao.java
  server/src/main/java/com/thoughtworks/go/server/dao/StageSqlMapDao.java
  server/src/main/java/com/thoughtworks/go/server/service/PipelineHistoryService.java
  server/src/main/java/com/thoughtworks/go/server/service/StageService.java
  server/src/main/resources/com/thoughtworks/go/server/dao/maps/Stage.xml
  server/src/test-fast/java/com/thoughtworks/go/server/dao/StageSqlMapDaoTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/PipelineHistoryServiceTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/StageServiceTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/dao/StageSqlMapDaoIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/StageServiceIntegrationTest.java
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: apis

#7529 Remove rails helpers
  server/src/main/webapp/WEB-INF/rails/app/controllers/api_v1/notification_filters_controller.rb
  server/src/main/webapp/WEB-INF/rails/app/helpers/agents_helper.rb
  server/src/main/webapp/WEB-INF/rails/app/helpers/api_v1/profiles_controller_actions.rb
  server/src/main/webapp/WEB-INF/rails/app/helpers/api_v1/users_helper.rb
  server/src/main/webapp/WEB-INF/rails/app/helpers/server_helper.rb
  server/src/main/webapp/WEB-INF/rails/app/helpers/sortable_table_helper.rb
  server/src/main/webapp/WEB-INF/rails/app/helpers/users_helper.rb
  server/src/main/webapp/WEB-INF/rails/spec/helpers/agents_helper_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/helpers/sortable_table_helper_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/helpers/users_helper_spec.rb
Labels: technical-debt

#7528 Remove old dashboard related code
  server/src/main/java/com/thoughtworks/go/server/domain/user/PipelineSelections.java
  server/src/main/java/com/thoughtworks/go/server/service/PipelineHistoryService.java
  server/src/test-fast/java/com/thoughtworks/go/server/domain/user/PipelineSelectionsTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/PipelineHistoryServiceTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/persistence/PipelineRepositoryIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/PipelineHistoryServiceIntegrationTest.java
Labels: Dashboard, technical-debt

#7535 Render validation errors for invalid Pipeline Group API update request (#7534)
  api/api-pipeline-groups-v1/src/main/java/com/thoughtworks/go/apiv1/admin/pipelinegroups/representers/AuthorizationRepresenter.java
  api/api-pipeline-groups-v1/src/test/groovy/com/thoughtworks/go/apiv1/admin/pipelinegroups/representers/AuthorizationRepresenterTest.groovy
  server/src/main/java/com/thoughtworks/go/config/update/UpdatePipelineConfigsCommand.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/PipelineConfigsServiceIntegrationTest.java
Labels: apis, bug-fix

#7463 Updated Job History API v1 to support cursor based pagination
  api/api-base/src/main/java/com/thoughtworks/go/api/ApiController.java
  api/api-compare-v1/src/main/java/com/thoughtworks/go/apiv1/compare/InternalCompareControllerV1.java
  api/api-job-instance-v1/src/main/java/com/thoughtworks/go/apiv1/jobinstance/JobInstanceControllerV1.java
  api/api-job-instance-v1/src/main/java/com/thoughtworks/go/apiv1/jobinstance/representers/JobInstancesRepresenter.java
  api/api-job-instance-v1/src/test/groovy/com/thoughtworks/go/apiv1/jobinstance/JobInstanceControllerV1Test.groovy
  api/api-job-instance-v1/src/test/groovy/com/thoughtworks/go/apiv1/jobinstance/representers/JobInstancesRepresenterTest.groovy
  api/api-pipeline-instance-v1/src/main/java/com/thoughtworks/go/apiv1/pipelineinstance/PipelineInstanceControllerV1.java
  api/api-pipeline-instance-v1/src/test/groovy/com/thoughtworks/go/apiv1/pipelineinstance/PipelineInstanceControllerV1Test.groovy
  api/api-stage-instance-v2/src/main/java/com/thoughtworks/go/apiv2/stageinstance/StageInstanceControllerV2.java
  api/api-stage-instance-v2/src/test/groovy/com/thoughtworks/go/apiv2/stageinstance/StageInstanceControllerV2Test.groovy
  server/src/main/java/com/thoughtworks/go/server/dao/JobInstanceDao.java
  server/src/main/java/com/thoughtworks/go/server/dao/JobInstanceSqlMapDao.java
  server/src/main/java/com/thoughtworks/go/server/service/JobInstanceService.java
  server/src/main/java/com/thoughtworks/go/server/service/PipelineHistoryService.java
  server/src/main/java/com/thoughtworks/go/server/service/ServiceConstants.java
  server/src/main/java/com/thoughtworks/go/server/service/StageService.java
  server/src/main/resources/com/thoughtworks/go/server/dao/maps/JobInstance.xml
  server/src/test-fast/java/com/thoughtworks/go/server/dao/JobInstanceSqlMapDaoTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/JobInstanceServiceTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/PipelineHistoryServiceTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/StageServiceTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/dao/JobInstanceSqlMapDaoIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/JobInstanceServiceIntegrationTest.java
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: apis

#7544 Update Pipeline Group Edit Modal
  server/src/main/webapp/WEB-INF/rails/webpack/models/admin_pipelines/admin_pipelines.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/admin_pipelines/specs/admin_pipelines_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/authorization/authorization.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/authorization/specs/authorization_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines/edit_pipeline_group.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines/edit_pipeline_group.scss.d.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines/edit_pipeline_group_modal.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines/spec/edit_pipeline_group_modal_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipelines/actions.scss
Labels: ui / ux

#7561 Fix for failing /bin/bash task
  config/config-api/src/main/java/com/thoughtworks/go/config/ExecTask.java
  config/config-api/src/test/java/com/thoughtworks/go/config/ExecTaskTest.java
Labels: bug-fix

#7586 Implement rules for Elastic Agent Profiles (#7549)
  api/api-elastic-profile-v2/src/main/java/com/thoughtworks/go/apiv2/elasticprofile/ElasticProfileControllerV2.java
  api/api-elastic-profile-v2/src/test/groovy/com/thoughtworks/go/apiv2/elasticprofile/ElasticProfileControllerV2Test.groovy
  api/api-roles-config-v3/src/main/java/com/thoughtworks/go/apiv3/rolesconfig/representers/DirectiveRepresenter.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/AbstractDirective.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/Allow.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/Deny.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/Directive.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/PolicyAware.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/elasticagents/ElasticAgentProfilesAbstractDirective.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/elasticagents/ElasticAgentProfilesAllowDirective.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/elasticagents/ElasticAgentProfilesDenyDirective.java
  config/config-api/src/test/java/com/thoughtworks/go/config/policy/AllowTest.java
  config/config-api/src/test/java/com/thoughtworks/go/config/policy/DenyTest.java
  config/config-api/src/test/java/com/thoughtworks/go/config/policy/elasticagents/ElasticAgentProfilesAllowDirectiveTest.java
  config/config-api/src/test/java/com/thoughtworks/go/config/policy/elasticagents/ElasticAgentProfilesDenyDirectiveTest.java
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/spring/AbstractAuthenticationHelper.java
Labels: apis, elastic-agents, granular-auth

#7573 Recompute Dashboard Cache when Pipeline Group Config Changes (#7572)
  server/src/main/java/com/thoughtworks/go/server/dashboard/GoDashboardActivityListener.java
  server/src/test-fast/java/com/thoughtworks/go/server/dashboard/GoDashboardActivityListenerTest.java
Labels: Dashboard, bug-fix

#7587 Parse failed config repos on Elastic Profile entity change
  server/src/main/java/com/thoughtworks/go/config/ConfigReposMaterialParseResultManager.java
  server/src/test-fast/java/com/thoughtworks/go/config/ConfigReposMaterialParseResultManagerTest.java
Labels: bug-fix

#7590 Allow access to elastic agent profiles based on cluster profile policy (#7549)
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/AbstractDirective.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/Allow.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/Deny.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/elasticagents/ClusterProfilesAllowDirective.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/elasticagents/ClusterProfilesDenyDirective.java
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/elasticagents/ElasticAgentProfilesAbstractDirective.java
  config/config-api/src/test/java/com/thoughtworks/go/config/policy/elasticagents/ClusterProfilesAllowDirectiveTest.java
  config/config-api/src/test/java/com/thoughtworks/go/config/policy/elasticagents/ClusterProfilesDenyDirectiveTest.java
  config/config-api/src/test/java/com/thoughtworks/go/config/policy/elasticagents/ElasticAgentProfilesAllowDirectiveTest.java
  config/config-api/src/test/java/com/thoughtworks/go/config/policy/elasticagents/ElasticAgentProfilesDenyDirectiveTest.java
Labels: apis, elastic-agents, granular-auth

#7591 Removing old pipeline history page
  server/src/main/java/com/thoughtworks/go/server/controller/PipelineHistoryController.java
  server/src/main/webapp/WEB-INF/rails/app/controllers/pipelines_controller.rb
  server/src/main/webapp/WEB-INF/rails/config/routes.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/api/pipelines_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/controllers/pipelines_controller_spec.rb
  server/src/main/webapp/WEB-INF/rails/spec/models/pipeline_history_api_model_spec.rb
  server/src/main/webapp/WEB-INF/vm/pipeline/_material_revisions_popup.vm
  server/src/main/webapp/WEB-INF/vm/pipeline/_pipeline_history_list_jstemplate.vm
  server/src/main/webapp/WEB-INF/vm/pipeline/pipeline_history.vm
  server/src/test-integration/java/com/thoughtworks/go/server/service/PipelineHistoryControllerIntegrationTest.java
Labels: pipeline-history

#7606 Handle notification filter validation
  api/api-notification-filter-v2/src/main/java/com/thoughtworks/go/apiv2/notificationfilter/NotificationFilterControllerV2.java
  api/api-notification-filter-v2/src/main/java/com/thoughtworks/go/apiv2/notificationfilter/representers/NotificationFilterRepresenter.java
  api/api-notification-filter-v2/src/test/groovy/com/thoughtworks/go/apiv2/notificationfilter/NotificationFilterControllerV2Test.groovy
  common/src/main/java/com/thoughtworks/go/domain/NotificationFilter.java
  common/src/main/java/com/thoughtworks/go/domain/User.java
  common/src/test/java/com/thoughtworks/go/domain/NotificationFilterTest.java
  server/src/main/java/com/thoughtworks/go/server/service/UserService.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/UserServiceTest.java
Labels: apis

#7608 Introduce Elastic Agent Profiles API v3 (#7549)
  .gitignore
  api/api-elastic-profile-v3/build.gradle
  api/api-elastic-profile-v3/src/main/java/com/thoughtworks/go/apiv3/elasticprofile/ElasticProfileControllerV3.java
  api/api-elastic-profile-v3/src/main/java/com/thoughtworks/go/apiv3/elasticprofile/representers/ElasticProfileRepresenter.java
  api/api-elastic-profile-v3/src/main/java/com/thoughtworks/go/apiv3/elasticprofile/representers/ElasticProfilesRepresenter.java
  api/api-elastic-profile-v3/src/test/groovy/com/thoughtworks/go/apiv3/elasticprofile/ElasticProfileControllerV3Test.groovy
  api/api-elastic-profile-v3/src/test/groovy/com/thoughtworks/go/apiv3/elasticprofile/representers/ElasticProfileRepresenterTest.groovy
  api/api-elastic-profile-v3/src/test/groovy/com/thoughtworks/go/apiv3/elasticprofile/representers/ElasticProfilesRepresenterTest.groovy
  server/src/main/resources/applicationContext-global.xml
  settings.gradle
Labels: apis, elastic-agents, granular-auth

#7611 Allow normal users to access elastic agent configurations page (#7549)
  api/api-elastic-profile-v3/src/main/java/com/thoughtworks/go/apiv3/elasticprofile/ElasticProfileControllerV3.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/filterchains/AuthorizeFilterChain.java
  server/src/main/webapp/WEB-INF/rails/webpack/models/elastic_profiles/cluster_profiles_crud.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/elastic_profiles/elastic_agent_profiles_crud.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/elastic_profiles/spec/cluster_profiles_crud_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/elastic_profiles/spec/types_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/elastic_profiles/types.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/cluster_profile_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/cluster_profiles_modals.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/elastic_agent_profiles_modals.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/elastic_profiles_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/spec/cluster_profiles_modals_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/spec/cluster_profiles_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/spec/elastic_agent_profiles_modals_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/spec/elastic_profile_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/spec/elastic_profiles_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/spec/test_data.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agents.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agents/wizard.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agents/wizard_spec.tsx
  spark/spark-spa/src/main/java/com/thoughtworks/go/spark/spa/ElasticAgentConfigurationsController.java
  spark/spark-spa/src/test/groovy/com/thoughtworks/go/spark/spa/ElasticAgentConfigurationsControllerTest.groovy
Labels: SPA, elastic-agents, granular-auth

#7613 Apply Policy permissions for elastic profiles usage API (#7549)
  api/api-elastic-profile-operation-v1/src/main/java/com/thoughtworks/go/apiv1/elasticprofileoperation/ElasticProfileOperationControllerV1.java
  api/api-elastic-profile-operation-v1/src/test/groovy/com/thoughtworks/go/apiv1/elasticprofileoperation/ElasticProfileOperationControllerV1Test.groovy
Labels: SPA, apis, elastic-agents, granular-auth

#7633 Fixing enterprise build
  server/src/main/resources/com/thoughtworks/go/server/dao/maps/JobInstance.xml
  server/src/test-integration/java/com/thoughtworks/go/server/dao/JobInstanceSqlMapDaoIntegrationTest.java
Labels: bug-fix

#7647 Allow specifying colon separator only for elastic agent profile permission (#7549)
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/AbstractDirective.java
  config/config-api/src/test/java/com/thoughtworks/go/config/policy/AbstractDirectiveTest.java
Labels: elastic-agents, granular-auth

#7570 Update UI for admin permissions on pipeline grp edit modal
  server/src/main/webapp/WEB-INF/rails/webpack/models/admin_pipelines/admin_pipelines.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/admin_pipelines/specs/admin_pipelines_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/authorization/authorization.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/authorization/specs/authorization_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines/spec/edit_pipeline_group_modal_spec.tsx
Labels: bug-fix

#7652 Fixes for Elastic Agent Configurations Page (#7549)(#7649)
  api/api-elastic-profile-operation-v1/src/main/java/com/thoughtworks/go/apiv1/elasticprofileoperation/ElasticProfileOperationControllerV1.java
  api/api-elastic-profile-operation-v1/src/test/groovy/com/thoughtworks/go/apiv1/elasticprofileoperation/ElasticProfileOperationControllerV1Test.groovy
  api/api-elastic-profile-v2/src/main/java/com/thoughtworks/go/apiv2/elasticprofile/ElasticProfileControllerV2.java
  api/api-elastic-profile-v2/src/test/groovy/com/thoughtworks/go/apiv2/elasticprofile/ElasticProfileControllerV2Test.groovy
  api/api-elastic-profile-v3/src/main/java/com/thoughtworks/go/apiv3/elasticprofile/ElasticProfileControllerV3.java
  api/api-elastic-profile-v3/src/test/groovy/com/thoughtworks/go/apiv3/elasticprofile/ElasticProfileControllerV3Test.groovy
  config/config-api/src/main/java/com/thoughtworks/go/config/policy/elasticagents/ElasticAgentProfilesAllowDirective.java
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/table/index.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/cluster_profile_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/elastic_agent_profiles_modals.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/spec/cluster_profiles_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agents/wizard.tsx
Labels: bug-fix, elastic-agents, granular-auth

#7648 Update internal pipelines structure API
  api/api-internal-pipeline-structure-v1/src/main/java/com/thoughtworks/go/apiv1/internalpipelinestructure/InternalPipelineStructureControllerV1.java
  api/api-internal-pipeline-structure-v1/src/main/java/com/thoughtworks/go/apiv1/internalpipelinestructure/representers/InternalPipelineStructuresRepresenter.java
  api/api-internal-pipeline-structure-v1/src/test/groovy/com/thoughtworks/go/apiv1/internalpipelinestructure/InternalPipelineStructureControllerV1Test.groovy
  api/api-internal-pipeline-structure-v1/src/test/groovy/com/thoughtworks/go/apiv1/internalpipelinestructure/representers/InternalPipelineStructuresRepresenterTest.groovy
  server/src/main/webapp/WEB-INF/rails/webpack/helpers/spark_routes.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/internal_pipeline_structure/pipeline_structure.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/internal_pipeline_structure/pipeline_structure_crud.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/internal_pipeline_structure/spec/pipeline_structure_crud_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/internal_pipeline_structure/spec/pipeline_structure_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines.tsx
  server/src/main/webapp/WEB-INF/urlrewrite.xml
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/Routes.java
Labels: SPA

#7656 Pipeline Grp Admin should receive a 403 on create if group doesnot exist
  spark/spark-base/src/main/java/com/thoughtworks/go/spark/spring/AbstractAuthenticationHelper.java
  spark/spark-base/src/test/groovy/com/thoughtworks/go/spark/SecurityServiceTrait.groovy
Labels: apis, bug-fix, pipeline configuration

#7675 Fix read only templates view styles on the pipeline config edit page
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates/modals.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates/modals.scss.d.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates/modals.tsx
Labels: bug-fix, ui / ux

#7653 Remove dead code
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/elastic_agent_profiles_modals.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agent_configurations/spec/elastic_agent_profiles_modals_spec.tsx
Labels: technical, technical-debt
