Repository gocd/gocd, pull requests merged in 2020-11, with the labels that each got.

#8712 Fix comparison spa failure for view users
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/compare.tsx
Labels: bug-fix

#8715 Fixed the incorrect console log link
  server/src/main/webapp/WEB-INF/rails/webpack/views/dashboard/stage_overview/index.tsx
Labels: bug-fix, ui / ux

#8713 Fix issues related to autoUpdate UI
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/forms/input_fields.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipelines/material_auto_update_toggle.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipelines/spec/material_auto_update_toggle_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pluggable_scms/index.scss
Labels: bug-fix, ui / ux

#8761 Fix for pipeline activity misalignment issue
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/index.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/index.scss.d.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/pipeline_activity_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/show_force_build_action_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/spec/pipeline_activity_widget_spec.tsx
Labels: SPA, bug-fix, ui / ux

#8776 If the window is in the background, even if the tab is active, reduce the polling interval by a factor of 3.
  server/src/main/webapp/WEB-INF/rails/webpack/helpers/ajax_poller.ts
Labels: performance, ui / ux

#8775 Make the ignore_for_scheduling field readonly on pipeline config edit spa
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipelines/non_scm_material_fields.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipelines/spec/non_scm_material_fields_spec.tsx
Labels: bug-fix, ui / ux

#8778 Agent, job resource matching is case-insensitive #8774
  config/config-api/src/main/java/com/thoughtworks/go/config/Agent.java
  config/config-api/src/test/java/com/thoughtworks/go/domain/AgentTest.java
Labels: agents

#8782 Update pipeline activity page
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/index.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/index.scss.d.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/pipeline_activity_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/pipeline_run_info_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/show_force_build_action_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/spec/pipeline_activity_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity/spec/pipeline_run_info_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/spec/pipeline_activity_page_spec.tsx
Labels: ui / ux

#8794 Use latest version of API for secret config spa
  server/src/main/webapp/WEB-INF/rails/webpack/models/secret_configs/secret_configs_crud.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/secret_configs/spec/secret_configs_crud_spec.ts
Labels: SPA, bug-fix
