Repository gocd/gocd, pull requests merged in 2023-11, with the labels that each got.

#12197 Remove EOL Alpine 3.15 container image
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/BuildDockerImageTask.groovy
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy
Labels: container-images

#12200 Correct agent status startup tests
  agent/src/test/java/com/thoughtworks/go/agent/statusapi/AgentStatusHttpdTest.java
Labels: agents, tests, java

#12201 Revert "ui-dev: bump google-protobuf from 3.24.4 to 3.25.0 in /server/src/main/webapp/WEB-INF/rails"
  server/src/main/webapp/WEB-INF/rails/Gemfile.lock
Labels: dependencies, ruby

#12202 Replace nanohttpd server with JDK builtin httpserver
  agent/build.gradle
  agent/src/main/java/com/thoughtworks/go/agent/statusapi/AgentStatusHttpd.java
  agent/src/main/java/com/thoughtworks/go/agent/statusapi/HttpHandler.java
  agent/src/main/java/com/thoughtworks/go/agent/statusapi/IsConnectedToServerV1.java
  agent/src/test/java/com/thoughtworks/go/agent/statusapi/AgentStatusHttpdTest.java
  base/src/main/java/com/thoughtworks/go/util/SystemEnvironment.java
  buildSrc/dependency-check-suppress.xml
  dependencies.gradle
Labels: agents, technical-debt, java

#12203 Tidy some warnings in plugin related infra code
  base/src/main/java/com/thoughtworks/go/util/FileUtil.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/common/settings/PluginSettingsMetadataLoaderTest.java
  plugin-infra/go-plugin-infra/src/main/java/com/thoughtworks/go/plugin/infra/DefaultPluginManager.java
  server/src/main/java/com/thoughtworks/go/server/service/plugins/builder/DefaultPluginInfoFinder.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/plugins/builder/DefaultPluginInfoFinderTest.java
Labels: technical-debt, java

#12207 Bump transitive dependencies
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12208 Revert "ui-dev: bump google-protobuf from 3.24.4 to 3.25.0 in /server/src/main/webapp/WEB-INF/rails"
  server/src/main/webapp/WEB-INF/rails/Gemfile.lock
Labels: dependencies, ruby

#12215 Clean up some unused scripts
  .github/dependabot.yml
  commandline/src/test/java/com/thoughtworks/go/util/ProcessWrapperTest.java
  scripts/.rbenv-gemsets
  scripts/Gemfile
  scripts/Gemfile.lock
  scripts/package-lock.json
  scripts/package.json
  scripts/trigger-dependabot-prs
  scripts/update-package-json
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: technical-debt

#12217 Clean up unnecessary JRuby imports of Java classses
  server/src/main/webapp/WEB-INF/rails/lib/java_imports.rb
  server/src/main/webapp/WEB-INF/rails/spec/support/java_spec_imports.rb
Labels: technical-debt, ruby

#12218 Make Gradle dev prepare leaner by not including test code
  build.gradle
  buildSrc/src/main/groovy/com/thoughtworks/go/build/ExecuteUnderRailsTask.groovy
  server/build.gradle
  server/rails.gradle
Labels: build-script

#12264 Revert "Bump com.fasterxml.jackson:jackson-bom from 2.15.3 to 2.16.0"
  dependencies.gradle
Labels: dependencies, java

#12265 Tidy test JsonOutputWriter and test handling
  api/api-base/src/test/groovy/com/thoughtworks/go/api/representers/JsonOutputWriterTest.groovy
  spark/spark-base/src/main/java/com/thoughtworks/go/api/base/JsonOutputWriter.java
  spark/spark-base/src/main/java/com/thoughtworks/go/api/base/OutputWriter.java
Labels: technical-debt, java

#12299 Don't log liquibase summaries to console
  db-support/db-migration/src/main/java/com/thoughtworks/go/server/database/migration/DatabaseMigrator.java
  db-support/db-migration/src/test/java/com/thoughtworks/go/server/database/migration/LiquibaseMigrationTest.java
Labels: technical, java

#12300 Fix console log menu scroll pinning
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/build_detail_page.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/console_log_tailing.js
Labels: ui / ux, console-log, bug-fix

#12303 Bump transitive dependencies
  server/src/main/webapp/WEB-INF/rails/package.json
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12318 Lock google-protobuf at < 3.25.0
  server/src/main/webapp/WEB-INF/rails/Gemfile
  server/src/main/webapp/WEB-INF/rails/Gemfile.lock
Labels: dependencies, ruby

#12319 De-dupe transitives again
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12322 Force-upgrade version of jasmine used by karma-jasmine to v5
  server/src/main/webapp/WEB-INF/rails/package.json
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript
