Repository gocd/gocd, pull requests merged in 2023-12, with the labels that each got.

#12325 Revert "ui-dev: bump nio4r from 2.6.1 to 2.7.0 in /server/src/main/webapp/WEB-INF/rails"
  server/src/main/webapp/WEB-INF/rails/Gemfile.lock
Labels: dependencies, ruby

#12321 Upgrade OWASP Dependency check to v9
  build.gradle
Labels: build-script, dependencies

#12333 Bump Gradle to 8.5
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
Labels: build-script, dependencies

#12335 Upgrade perforce repos to 23.2
  common/src/test/resources/data/p4TicketedRepo/db.counters
  common/src/test/resources/data/p4TicketedRepo/db.depot
  common/src/test/resources/data/p4TicketedRepo/db.domain
  common/src/test/resources/data/p4TicketedRepo/db.revtr
  common/src/test/resources/data/p4TicketedRepo/db.upgrades
  common/src/test/resources/data/p4TicketedRepo/journal
  common/src/test/resources/data/p4TicketedRepo/state.xu
  common/src/test/resources/data/p4TicketedRepoWindows/db.counters
  common/src/test/resources/data/p4TicketedRepoWindows/db.depot
  common/src/test/resources/data/p4TicketedRepoWindows/db.domain
  common/src/test/resources/data/p4TicketedRepoWindows/db.revtr
  common/src/test/resources/data/p4TicketedRepoWindows/db.upgrades
  common/src/test/resources/data/p4TicketedRepoWindows/journal
  common/src/test/resources/data/p4TicketedRepoWindows/state.xu
  common/src/test/resources/data/p4repo/db.counters
  common/src/test/resources/data/p4repo/db.depot
  common/src/test/resources/data/p4repo/db.domain
  common/src/test/resources/data/p4repo/db.revtr
  common/src/test/resources/data/p4repo/db.upgrades
  common/src/test/resources/data/p4repo/journal
  common/src/test/resources/data/p4repo/state.xu
  common/src/test/resources/data/p4repoWindows/db.counters
  common/src/test/resources/data/p4repoWindows/db.depot
  common/src/test/resources/data/p4repoWindows/db.domain
  common/src/test/resources/data/p4repoWindows/db.revtr
  common/src/test/resources/data/p4repoWindows/db.upgrades
  common/src/test/resources/data/p4repoWindows/journal
  common/src/test/resources/data/p4repoWindows/state.xu
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/packagematerial/NewPackageMaterialMetadataLoader.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/packagematerial/PackageMaterialMetadataLoader.java
Labels: tests

#12337 Workaround auto-closing pipeline material dependency stage selection on Chrome <= 120 on MacOS Sonama
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipelines/non_scm_material_fields.tsx
Labels: ui / ux, bug-fix

#12340 De-duplicate transitive dependencies
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12344 Revert "Bump org.ysb33r.gradle:grolifant-herd from 2.0.0 to 2.1.0"
  dependencies.gradle
Labels: dependencies, java

#12353 Switch server default image to Alpine 3.19 + add Alpine 3.19 builds
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy
  settings-docker.gradle
Labels: container-images

#12355 Migrate UI to build modern UI with sass-embedded
  server/src/main/webapp/WEB-INF/rails/package.json
  server/src/main/webapp/WEB-INF/rails/webpack/config/loaders/css-loader.ts
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: build-script, dependencies, javascript

#12356 Rollback selenium-webdriver to 4.15.0
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12363 Revert "Bump org.ysb33r.gradle:grolifant-herd from 2.0.0 to 2.1.1"
  dependencies.gradle
Labels: dependencies, java

#12368 Minor technical fixes
  server/src/main/java/com/thoughtworks/go/server/cache/GoCache.java
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/ajax_refresher.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/stage_detail_ajax_refresher.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/ajax_refresher_spec.js
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: technical-debt

#12358 Replace legacy JS ModalBox with native HTML Dialog
  buildSrc/src/main/resources/license-for-javascript-not-in-yarn.json
  server/src/main/webapp/WEB-INF/rails/app/assets/images/g9/backgrounds/bg_glass_gradient.png
  server/src/main/webapp/WEB-INF/rails/app/assets/images/g9/backgrounds/overlay_modal_action_row.png
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/application.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/lib/modalbox-1.6.1.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/stage_history.js
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/_module.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/_structure.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css/_ui.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css_sass/gadgets/_modals.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css_sass/global/_layout.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css_sass/go-pages/_admin.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/new-theme.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/vm/_structure_for_old_ui.scss
  server/src/main/webapp/WEB-INF/rails/app/views/stages/_stage_history.html.erb
Labels: technical-debt, javascript

#12376 Bump transitive deps
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12383 Remove workaround that fixes unnecessary transitive dependencies from Jetty
  development-utility/development-server/build.gradle
  jetty/build.gradle
  server-launcher/build.gradle
Labels: dependencies, java

#12389 Fix disappearing second+ stages on VSM view after clicking a stage
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/vsm_renderer.js
  spark/spark-spa/src/main/resources/freemarker/analytics/index.ftlh
Labels: vsm, ui / ux, bug-fix

#12212 fix: templates in alphabetical order
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/clicky_pipeline_config/spec/tabs/pipeline/stage/pipeline_template_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/clicky_pipeline_config/tabs/pipeline/stage/pipeline_template_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipelines/spec/template_editor_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipelines/template_editor.tsx
Labels: templates, ui / ux

#12391 Minor JavaScript dependency bumps
  server/src/main/webapp/WEB-INF/rails/package.json
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12392 Correct display of "cancelled by" for stage runs other than that being viewed
  server/src/main/java/com/thoughtworks/go/server/ui/StageSummaryModel.java
  server/src/main/webapp/WEB-INF/rails/app/views/stages/_other_stage_runs.html.erb
  server/src/test-fast/java/com/thoughtworks/go/server/ui/StageSummaryModelTest.java
Labels: ui / ux, stage-overview

#12397 Bump momentjs to 2.30.0
  buildSrc/src/main/resources/license-for-javascript-not-in-yarn.json
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/application.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/lib/moment-2.29.4.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/lib/moment-2.30.0.js
  server/src/main/webapp/WEB-INF/rails/package.json
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12407 Remove old IE hacks and dead SCSS
  build.gradle
  server/src/main/resources/backup_in_progress.html
  server/src/main/resources/server_in_maintenance_mode.html
  server/src/main/webapp/WEB-INF/rails/app/assets/images/bg-header-tabs-current.png
  server/src/main/webapp/WEB-INF/rails/app/assets/images/bg-header-tabs.png
  server/src/main/webapp/WEB-INF/rails/app/assets/images/g9/button_select_icon.png
  server/src/main/webapp/WEB-INF/rails/app/assets/images/g9/button_select_icon_dark.png
  server/src/main/webapp/WEB-INF/rails/app/assets/images/g9/logo_go.png
  server/src/main/webapp/WEB-INF/rails/app/assets/images/icon-warning-small.gif
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/old_application.js
  server/src/main/webapp/WEB-INF/rails/app/assets/new_stylesheets/frameworks.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/new_stylesheets/shared/_mixins.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/_layout.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/_module.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/_structure.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css/_application-old.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css/_build_detail.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css/_global.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css/_rounded_corner.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css/_stage-detail.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css/admin-tab.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css/navigation.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css/reset-fonts-grids.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css/transparent_message.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css_sass/base/_mixins.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css_sass/components/_messages.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css_sass/components/_navbar.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css_sass/gadgets/_dropdowns.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css_sass/global/_layout.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css_sass/go-pages/_admin.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/new-theme.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/patterns/_buttons.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/patterns/_forms.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/patterns/_messages.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/patterns/_tables.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/patterns/_tabs.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/structure/_application.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/views/_admin_pipelines_snippet.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/views/_stages.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/vm/_jef_override_for_old_ui.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/vm/_layout_for_old_ui.scss
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/vm/_structure_for_old_ui.scss
  server/src/main/webapp/WEB-INF/rails/webpack/helpers/digest.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/mixins/errors_consumer.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/switch/index.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/dashboard/sortable_view_tabs.js.msx
  server/src/main/webapp/WEB-INF/rails/webpack/views/global/_mixins.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/clicky_pipeline_config/spec/tabs/job/job_settings_tab_content_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/partials/spec/site_footer_spec.tsx
Labels: technical-debt

#12411 Ensure login errors are visible with the login form
  server/src/main/webapp/WEB-INF/rails/app/assets/images/g9/icon_config_changed_16.png
  server/src/main/webapp/WEB-INF/rails/app/assets/images/g9/stage_bar_cancelled_icon.png
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/login_page/login_page_widget.scss
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: ui / ux, bug-fix

#12412 Add back assets/images accidentally removed
  server/src/main/webapp/WEB-INF/rails/app/assets/images/g9/backgrounds/bg_header_default.png
  server/src/main/webapp/WEB-INF/rails/app/assets/images/g9/icon_config_changed_16.png
  server/src/main/webapp/WEB-INF/rails/app/assets/images/g9/stage_bar_cancelled_icon.png
Labels: technical-debt

#12417 Switch from sassc-rails to dartsass-sprockets
  server/src/main/webapp/WEB-INF/rails/Gemfile
  server/src/main/webapp/WEB-INF/rails/Gemfile.lock
Labels: dependencies, ruby
