Repository gocd/gocd, pull requests merged in 2023-07, with the labels that each got.

#11730 Bump Gradle to 8.2
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
Labels: build-script, dependencies

#11735 Avoid relying on Gradle base convention properties
  installers/build.gradle
  installers/generic.gradle
  installers/osx.gradle
  installers/release-notes.gradle
Labels: build-script

#11764 Revert font family naming to be compatible with FontAwesome 4
  server/src/main/webapp/WEB-INF/rails/app/assets/new_stylesheets/_font-awesome-glyphs.scss.erb
  server/src/main/webapp/WEB-INF/rails/app/assets/new_stylesheets/_font-awesome-sprockets.scss
  server/src/main/webapp/WEB-INF/rails/webpack/single_page_apps/global.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/global/_fontawesome.scss
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/partials/site_footer.scss
Labels: ui / ux

#11633 Add support for additional OAuth2/OIDC verification between redirects in authorization extensions
  api/api-access-token-v1/src/main/java/com/thoughtworks/go/apiv1/accessToken/CurrentUserAccessTokenControllerV1.java
  api/api-access-token-v1/src/test/groovy/com/thoughtworks/go/apiv1/accessToken/CurrentUserAccessTokenControllerV1Test.groovy
  common/src/main/java/com/thoughtworks/go/server/domain/Version.java
  common/src/test/java/com/thoughtworks/go/server/domain/VersionTest.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/authorization/AuthorizationExtension.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/authorization/AuthorizationMessageConverter.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/authorization/AuthorizationPluginConstants.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/authorization/v1/AuthenticationResponseDTO.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/authorization/v1/AuthorizationMessageConverterV1.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/authorization/v1/CapabilitiesDTO.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/authorization/v1/SupportedAuthTypeDTO.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/authorization/v1/UserDTO.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/authorization/v1/VerifyConnectionResponseDTO.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/authorization/v2/AuthorizationMessageConverterV2.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/authorization/v2/AuthorizationServerUrlResponseDTO.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/authorization/AuthorizationExtensionTest.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/authorization/v1/AuthenticationResponseDTOTest.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/authorization/v1/AuthorizationMessageConverterV1Test.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/authorization/v1/CapabilitiesDTOTest.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/authorization/v1/VerifyConnectionResponseDTOTest.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/authorization/v2/AuthorizationMessageConverterV2Test.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/authorization/v2/AuthorizationServerUrlResponseDTOTest.java
  plugin-infra/go-plugin-domain/src/main/java/com/thoughtworks/go/plugin/domain/authorization/AuthorizationServerUrlResponse.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/controllers/AuthenticationController.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/providers/WebBasedPluginAuthenticationProvider.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/utils/SessionUtils.java
  server/src/test-fast/java/com/thoughtworks/go/server/newsecurity/controllers/AuthenticationControllerTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/newsecurity/providers/WebBasedPluginAuthenticationProviderTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/newsecurity/utils/SessionUtilsTest.java
Labels: plugins, authentication

#11765 Remove duplicate artifact extension V1 code
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/artifact/ArtifactExtension.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/artifact/ArtifactMessageConverterV1.java
  plugin-infra/go-plugin-access/src/main/java/com/thoughtworks/go/plugin/access/artifact/ArtifactMessageConverterV2.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/artifact/ArtifactExtensionForV1Test.groovy
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/artifact/ArtifactExtensionTestBase.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/artifact/ArtifactMessageConverterV2Test.java
Labels: technical-debt, java

#11767 Fix console FontAwesome references
  server/src/main/resources/server_in_maintenance_mode.html
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css/_console-log.scss
Labels: ui / ux

#11766 Remove old standalone rest/html views of artifact folders
  common/src/main/java/com/thoughtworks/go/agent/URLService.java
  common/src/main/java/com/thoughtworks/go/domain/DirHandler.java
  common/src/main/java/com/thoughtworks/go/domain/FileHandler.java
  config/config-api/src/main/java/com/thoughtworks/go/config/materials/dependency/DependencyMaterialConfig.java
  domain/src/main/java/com/thoughtworks/go/config/materials/dependency/DependencyMaterial.java
  server/src/main/java/com/thoughtworks/go/server/controller/ArtifactsController.java
  server/src/main/java/com/thoughtworks/go/server/controller/JobController.java
  server/src/main/java/com/thoughtworks/go/server/controller/actions/JsonAction.java
  server/src/main/java/com/thoughtworks/go/server/dao/StageSqlMapDao.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/filterchains/AuthenticationFilterChain.java
  server/src/main/java/com/thoughtworks/go/server/newsecurity/filterchains/AuthorizeFilterChain.java
  server/src/main/java/com/thoughtworks/go/server/presentation/models/JobDetailPresentationModel.java
  server/src/main/java/com/thoughtworks/go/server/view/artifacts/LocalArtifactsView.java
  server/src/main/java/com/thoughtworks/go/server/web/ArtifactFolder.java
  server/src/main/java/com/thoughtworks/go/server/web/FileModelAndView.java
  server/src/main/java/com/thoughtworks/go/server/web/JsonArtifactFolderViewFactory.java
  server/src/main/java/com/thoughtworks/go/server/web/JsonArtifactViewFactory.java
  server/src/main/java/com/thoughtworks/go/server/web/ZipArtifactFolderViewFactory.java
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css/_application-old.scss
  server/src/main/webapp/WEB-INF/urlrewrite.xml
  server/src/main/webapp/WEB-INF/vm/build_detail/_artifacts.ftlh
  server/src/main/webapp/WEB-INF/vm/rest/html.ftlh
  server/src/main/webapp/WEB-INF/vm/shared/_artifacts.ftlh
  server/src/test-fast/java/com/thoughtworks/go/server/controller/ArtifactsControllerTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/newsecurity/filterchains/AuthenticationFilterChainTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/presentation/models/JobDetailPresentationModelJMockTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/presentation/models/JobDetailPresentationModelTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/view/freemarker/BuildDetailPageFreeMarkerTemplateTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/controller/ArtifactsControllerIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/functional/helpers/CSVResponse.java
  server/src/test-integration/java/com/thoughtworks/go/server/persistence/MaterialRepositoryIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/web/UrlRewriterIntegrationTest.java
Labels: technical-debt, java

#11768 ui-dev: Bump transitive js dependencies
  server/src/main/webapp/WEB-INF/rails/package.json
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#11772 Fix export to config repo of fetch artifact tasks without pipeline name set
  server/src/main/java/com/thoughtworks/go/config/ConfigConverter.java
  server/src/test-fast/java/com/thoughtworks/go/config/ConfigConverterTest.java
Labels: pipeline configuration, config repo, bug-fix

#11771 Bump bundled JDK version to 17.0.8+7
  build.gradle
Labels: installers, container-images, dependencies, java

#11783 Fix display of build detail timestamps icon
  server/src/main/webapp/WEB-INF/rails/app/assets/stylesheets/css/_build_detail.scss
  server/src/main/webapp/WEB-INF/vm/build_detail/_build_output_raw.ftlh
Labels: ui / ux

#11784 Release script tidy-ups
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/BuildDockerImageTask.groovy
  installers/linux/deb/after-install.sh.erb
  installers/linux/deb/after-upgrade.sh.erb
  installers/linux/deb/before-upgrade.sh.erb
  installers/linux/rpm/after-install.sh.erb
  installers/linux/rpm/after-upgrade.sh.erb
  installers/linux/rpm/before-upgrade.sh.erb
Labels: build-script

#11785 Bump ehcache to core-only releases of 2.11.x
  build.gradle
  dependencies.gradle
  server/build.gradle
  spark/spark-spa/build.gradle
Labels: dependencies, java

#11791 Fix stage history pagination handling
  server/rails.gradle
  server/src/main/webapp/WEB-INF/rails/app/helpers/application_helper.rb
  server/src/main/webapp/WEB-INF/rails/config/routes.rb
  server/src/main/webapp/WEB-INF/urlrewrite.xml
  server/src/test-integration/java/com/thoughtworks/go/server/web/UrlRewriterIntegrationTest.java
Labels: ui / ux, bug-fix, stage-overview

#11801 ui-dev: Bump transitive dependencies
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#11802 Add support for scanning images with trivy via ignore file
  buildSrc/.trivyignore
  buildSrc/dependency-check-suppress.xml
Labels: build-script

#11813 Remove CentOS 7 container support/agent image
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy
Labels: container-images

#11814 Upgrade Foundation for Sites to 6.7.5
  server/src/main/webapp/WEB-INF/rails/app/assets/new_stylesheets/_settings.scss
  server/src/main/webapp/WEB-INF/rails/package.json
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new_plugins/foundation_hax.scss
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: ui / ux, dependencies, javascript

#11815 Tidy some linting/indenting of legacy JS
  server/src/main/webapp/WEB-INF/rails/.eslintignore
  server/src/main/webapp/WEB-INF/rails/.eslintrc-old.json
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/ajax_refresher.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/ajax_refreshers.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/build_detail.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/build_detail_page.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/build_summary_observer.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/console_log_ansi_colors.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/console_log_foldable_section.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/console_log_observer.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/console_log_tailing.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/console_scroller.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/css_toggling.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/dashboard_periodical_executor.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/field_state_replicator.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/json_to_css.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/log_output_transformer.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/micro_content_popup.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/old_application.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/prototype_overrides.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/stage_detail_ajax_refresher.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/stage_history.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/tabs.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/timer_observer.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/transmessage.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/util.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/vsm.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/vsm_analytics_pipeline_panel.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/vsm_graph.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/vsm_node.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/vsm_renderer.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/websocket_wrapper.js
  server/src/main/webapp/WEB-INF/rails/package.json
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/ajax_refresher_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/ajax_refreshers_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/build_detail_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/build_summary_observer_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/console_log_foldable_section_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/dashboard_periodical_executor_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/field_state_replicator_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/helpers/jsunitHelpersForMigratedTests.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/json_to_css_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/log_output_transformer_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/stage_details_ajax_refresher_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/stage_history_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/toggle_css_class_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/util_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/value_stream_map_renderer_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/value_stream_map_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/vsm_graph_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/vsm_node_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/websocket_wrapper_spec.js
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: technical-debt, javascript

#11816 Tidy linting rules to match as much as possible
  server/src/main/webapp/WEB-INF/rails/.eslintrc-old.json
  server/src/main/webapp/WEB-INF/rails/.eslintrc.json
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/console_log_socket.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/log_output_transformer.js
  server/src/main/webapp/WEB-INF/rails/spec/webpack/models/dashboard/trigger_with_options_info_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/webpack/views/dashboard/pipeline_widget_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/webpack/views/shared/analytics_iframe_widget_spec.js
  server/src/main/webapp/WEB-INF/rails/spec/webpack/views/shared/dropdown_spec.js
  server/src/main/webapp/WEB-INF/rails/webpack/helpers/form_helper.js.msx
  server/src/main/webapp/WEB-INF/rails/webpack/models/shared/frame.js
  server/src/main/webapp/WEB-INF/rails/webpack/rails-shared/plugin-endpoint.js
  server/src/main/webapp/WEB-INF/rails/webpack/views/analytics/global_metrics.js.msx
  server/src/main/webapp/WEB-INF/rails/webpack/views/analytics/pipeline_metrics.js.msx
  server/src/main/webapp/WEB-INF/rails/webpack/views/dashboard/pipeline_analytics_widget.js.msx
  server/src/main/webapp/WEB-INF/rails/webpack/views/shared/analytics_iframe_widget.js.msx
  server/src/main/webapp/WEB-INF/rails/webpack/views/shared/schmodal.js.msx
Labels: technical-debt, javascript

#11818 Remove some more unnecessary browsers from targeting
  server/src/main/webapp/WEB-INF/rails/.babelrc
Labels: build-script, javascript

#11819 Agent links from stage details jobs tab no longer work
  server/src/main/webapp/WEB-INF/rails/app/helpers/application_helper.rb
Labels: ui / ux, bug-fix

#11817 Upgrade JQuery used by legacy JS to 3.7.0
  buildSrc/dependency-check-suppress.xml
  buildSrc/src/main/resources/license-for-javascript-not-in-yarn.json
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/application.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/lib/jquery-2.2.4.js
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/lib/jquery-3.7.0.js
  server/src/main/webapp/WEB-INF/rails/spec/javascripts/stage_history_spec.js
Labels: dependencies, javascript
