Repository gocd/gocd, pull requests merged in 2024-04, with the labels that each got.

#12677 Fixes #4011
  buildSrc/src/main/groovy/com/thoughtworks/go/build/InstallerTypeAgent.groovy
  buildSrc/src/main/groovy/com/thoughtworks/go/build/InstallerTypeServer.groovy
  installers/linux/shared/before-install.sh.erb
Labels: installers, bug-fix

#12709 Bump + de-duplicate transitives
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12710 Bump bundled JRE to 17.0.11+9
  build.gradle
Labels: installers, container-images, dependencies

#10520 Change GoCD to no longer force links to open in new windows/tabs
  server/src/main/resources/server_in_maintenance_mode.html
  server/src/main/webapp/WEB-INF/rails/webpack/models/shared/spec/version_updater_spec.ts
  server/src/main/webapp/WEB-INF/rails/webpack/models/shared/version_updater.ts
  server/src/main/webapp/WEB-INF/rails/webpack/views/components/link/spec/index_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/dashboard/stage_overview/job_agent_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/dashboard/stage_overview/jobs_list_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/dashboard/stage_overview/spec/stage_overview_header_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/dashboard/stage_overview/stage_overview_header.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/access_tokens/access_tokens_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_pipelines/admin_pipelines_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/admin_templates/admin_templates_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agent-job-run-history/agent_job_run_history_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/agents.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/auth_configs/auth_configs_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/clicky_pipeline_config/tab_handler.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/clicky_pipeline_config/widgets/job_editor_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/compare.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/config_repos/config_repos_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/elastic_agents.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/maintenance_mode/maintenance_mode_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/maintenance_mode/spec/maintenance_mode_widget_spec.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/materials/materials_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/materials/modal.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/config_repo_link.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/edit_pipelines_modal.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new-environments/environments_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/new_preferences.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/package_repositories/package_repositories_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/partials/site_footer.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipeline_activity.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pipelines.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/pluggable_scms/pluggable_scms_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/plugins.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/preferences/notifications_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/roles/policy_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/roles/roles_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/pages/secret_configs/secret_configs_widget.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/shared/environment_variables_with_origin_widget.tsx
Labels: ui / ux, javascript, no stalebot

#12717 Bump transitive dependencies
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12719 Add agent images based on Ubuntu 24.04 LTS (Noble)
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy
Labels: container-images

#12712 Replace bundled deb/rpm x64 JRE with arch-independent package deps
  installers/linux.gradle
  installers/linux/deb/after-install.sh.erb
Labels: installers

#12723 Bump transitive dependencies
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript
