Repository gocd/gocd, pull requests merged in 2024-01, with the labels that each got.

#12421 Workaround Groovy AssertJ issue
  api/api-base/src/test/groovy/com/thoughtworks/go/api/representers/JsonOutputWriterTest.groovy
Labels: tests, dependencies, java

#12422 Update README-running-multiple-agents.md
  installers/go-agent/release/README-running-multiple-agents.md
Labels: agents, installers

#12431 Bump transitive dependencies
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12443 Disable use of udev for the OSHI system information library
  agent/src/main/java/com/thoughtworks/go/agent/service/SystemInfo.java
  agent/src/test/java/com/thoughtworks/go/agent/service/SystemInfoTest.java
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/Distro.groovy
  dependencies.gradle
Labels: agents, container-images

#12445 Bump javascript dependencies
  server/src/main/webapp/WEB-INF/rails/package.json
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12447 Prefer contenthash to chunkhash in another place
  server/src/main/webapp/WEB-INF/rails/webpack/config/webpack.config.ts
Labels: build-script, javascript

#12451 Bump and consolidate JS transitive deps
  server/src/main/webapp/WEB-INF/rails/package.json
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12456 Bump packaged JDK to 17.0.10
  build.gradle
  buildSrc/src/main/groovy/com/thoughtworks/go/build/AdoptiumVersion.groovy
  buildSrc/src/main/groovy/com/thoughtworks/go/build/LicenseReport.groovy
  buildSrc/src/main/groovy/com/thoughtworks/go/build/docker/DistroBehavior.groovy
  installers/linux.gradle
  installers/osx.gradle
  installers/windows.gradle
Labels: installers, container-images, dependencies

#12470 Bump transitive dependencies
  buildSrc/src/main/groovy/com/thoughtworks/go/build/AdoptiumVersion.groovy
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12475 Consolidate deps
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript

#12483 Bump @types/node to 20.11.13
  server/src/main/webapp/WEB-INF/rails/package.json
  server/src/main/webapp/WEB-INF/rails/yarn.lock
Labels: dependencies, javascript
