Repository gocd/gocd, pull requests merged in 2025-01, with the labels that each got.

#13381 Workaround sporadic failure of VSM JS tests
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/vsm_renderer.js
Labels: vsm, ui / ux, tests

#13393 Fix re-display of stage overview models on VSM pages
  server/src/main/webapp/WEB-INF/rails/webpack/single_page_apps/stage_overview_shim_for_vsm.tsx
Labels: vsm, bug-fix, stage-overview

#13398 Fix display of stage overview models for VSM nodes which have periods in their IDs
  server/src/main/webapp/WEB-INF/rails/app/assets/javascripts/vsm_renderer.js
  server/src/main/webapp/WEB-INF/rails/webpack/single_page_apps/stage_overview_shim_for_vsm.tsx
Labels: vsm, bug-fix, stage-overview

#13399 Avoid multiple stage overviews being displayed on VSM when server is slow to return model
  server/src/main/webapp/WEB-INF/rails/webpack/single_page_apps/stage_overview_shim_for_vsm.tsx
  server/src/main/webapp/WEB-INF/rails/webpack/views/dashboard/models/stage_overview_state.js
Labels: vsm, stage-overview

#13410 Remove need for ruby to test process forking
  commandline/src/main/java/com/thoughtworks/go/util/command/CommandLine.java
  commandline/src/test/java/com/thoughtworks/go/util/ProcessWrapperTest.java
  commandline/src/test/resources/executables/dump-environment.jsh
  commandline/src/test/resources/executables/echo.jsh
  domain/build.gradle
  domain/src/test/java/com/thoughtworks/go/domain/materials/perforce/P4Fixture.java
  domain/src/test/java/com/thoughtworks/go/domain/materials/perforce/PerforceFixture.java
  domain/src/test/java/com/thoughtworks/go/helper/P4TestRepo.java
  util/src/test/resources/executables/dump-environment.rb
  util/src/test/resources/executables/echo-all-input.rb
  util/src/test/resources/executables/echo-input.rb
  util/src/test/resources/executables/echo.rb
Labels: tests

#13411 Speed up slowish test
  server/src/test-integration/java/com/thoughtworks/go/server/messaging/activemq/ActiveMqTest.java
Labels: tests

#13412 Fix likely issue with waiting for p4d to start
  domain/src/test/java/com/thoughtworks/go/helper/P4TestRepo.java
Labels: tests

#13439 Increase UI responsiveness by decreasing default refresh interval to 5 seconds
  base/src/main/java/com/thoughtworks/go/util/SystemEnvironment.java
  server/src/main/webapp/WEB-INF/rails/webpack/helpers/constants.ts
Labels: ui / ux

#13433 Bump pre-packaged JDK to 21.0.6+7
  build.gradle
Labels: installers, dependencies

#13446 Fix all warnings, sufficiently to compile with warnings-as-errors
  base/src/main/java/com/thoughtworks/go/domain/BaseCollection.java
  build.gradle
  common/src/test/java/com/thoughtworks/go/server/transaction/TestTransactionTemplate.java
  config/config-api/src/main/java/com/thoughtworks/go/config/PluginProfiles.java
  domain/src/test/java/com/thoughtworks/go/config/materials/PackageMaterialTest.java
  domain/src/test/java/com/thoughtworks/go/config/materials/mercurial/HgMaterialTest.java
  domain/src/test/java/com/thoughtworks/go/config/materials/perforce/P4MaterialTest.java
  domain/src/test/java/com/thoughtworks/go/config/materials/scm/PluggableSCMMaterialTest.java
  domain/src/test/java/com/thoughtworks/go/config/materials/tfs/TfsMaterialTest.java
  domain/src/test/java/com/thoughtworks/go/domain/materials/svn/SvnMaterialTest.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/elastic/ElasticAgentExtensionV4Test.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/pluggabletask/PluggableTaskPluginInfoBuilderTest.java
  plugin-infra/go-plugin-access/src/test/java/com/thoughtworks/go/plugin/access/pluggabletask/PluggableTaskPreferenceLoaderTest.java
  plugin-infra/go-plugin-api-internal/src/main/java/com/thoughtworks/go/plugin/api/config/Options.java
  plugin-infra/go-plugin-config-repo/src/test/java/com/thoughtworks/go/plugin/configrepo/contract/AbstractCRTest.java
  plugin-infra/go-plugin-infra/src/test/java/com/thoughtworks/go/plugin/infra/DefaultPluginManagerTest.java
  plugin-infra/go-plugin-infra/src/test/java/com/thoughtworks/go/plugin/infra/FelixGoPluginOSGiFrameworkTest.java
  server/src/main/java/com/thoughtworks/go/config/security/permissions/PipelinePermission.java
  server/src/main/java/com/thoughtworks/go/server/GoServer.java
  server/src/main/java/com/thoughtworks/go/server/materials/DependencyMaterialUpdateNotifier.java
  server/src/main/java/com/thoughtworks/go/server/persistence/AgentDao.java
  server/src/test-fast/java/com/thoughtworks/go/config/GoConfigPluginServiceTest.java
  server/src/test-fast/java/com/thoughtworks/go/domain/cctray/CcTrayActivityListenerTest.java
  server/src/test-fast/java/com/thoughtworks/go/domain/cctray/CcTrayConfigChangeHandlerTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/dao/PipelineStateDaoCachingTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/dao/StageSqlMapDaoTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/dao/UserSqlMapDaoTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/dashboard/GoDashboardActivityListenerTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/dashboard/GoDashboardCurrentStateLoaderTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/initializers/ApplicationInitializerTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/materials/MaterialUpdateListenerFactoryTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/messaging/PluginMessageQueueHandlerTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/newsecurity/filters/AbstractReAuthenticationFilterTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/AccessTokenServiceTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/AdminServiceTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/AgentServiceTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/BackupServiceTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/PipelineLockServiceTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/PipelineSchedulerTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/StubGoCache.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/TimerSchedulerTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/UserServiceTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/plugins/validators/authorization/RoleConfigurationValidatorTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/service/support/ConfigInfoProviderTest.java
  server/src/test-fast/java/com/thoughtworks/go/server/web/InterceptorInjectorTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/dao/UserSqlMapDaoIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/persistence/MaterialRepositoryIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/ChangesetServiceIntegrationTest.java
  server/src/test-integration/java/com/thoughtworks/go/server/service/ConfigDbStateRepositoryIntegrationTest.java
Labels: technical

#13448 Correct test
  server/src/test-fast/java/com/thoughtworks/go/server/dao/StageSqlMapDaoTest.java
Labels: technical

#13449 Fix test properly
  server/src/test-fast/java/com/thoughtworks/go/server/dao/StageSqlMapDaoTest.java
Labels: technical

#13451 [post-release] Bump up GoCD Version to 25.2.0
  build.gradle
Labels: technical

#13452 Remove misleading comments
  server/src/test-shared/java/com/thoughtworks/go/ClearSingleton.java
  server/src/test-shared/java/com/thoughtworks/go/domain/valuestreammap/VSMTestHelper.java
  server/src/test-shared/java/com/thoughtworks/go/server/dao/DatabaseAccessHelper.java
  server/src/test-shared/java/com/thoughtworks/go/util/GoConfigFileHelper.java
Labels: technical-debt
